import { defaultPiperVoiceId, synthesizeVoiceWorkerAudio } from "./voiceWorker.js";

export const audioRenderJobVersion = 1;
export const renderJobStoragePrefix = "novelverse.audioRenderJobs.v1";
export const renderClipStates = ["not_rendered", "queued", "rendering", "rendered", "failed", "cancelled", "skipped"];
const speechTypes = new Set(["narrator", "dialogue", "thought", "internal_thought"]);

export function isSpeechClip(clip = {}, track = {}) { return speechTypes.has(clip.clipType || clip.type) || ["narrator", "character"].includes(track.type); }
export function getRenderJobStorageKey(projectId, novelId, chapterId) { return `${renderJobStoragePrefix}:${projectId || "project"}:${novelId || "global"}:${chapterId || "chapter"}`; }
export function orderedSpeechClips(project = {}) { return (project.tracks || []).flatMap((track) => (track.clips || []).filter((clip) => isSpeechClip(clip, track)).map((clip) => ({ ...clip, trackId: track.id, trackName: track.name, trackType: track.type }))).sort((a, b) => (Number(a.sourceOrder ?? a.start) || 0) - (Number(b.sourceOrder ?? b.start) || 0)); }
export function stableAudioCacheHash(input = {}) { const keys = ["sourceText", "provider", "voiceId", "language", "rate", "pitch", "volume", "emotion", "pauseBefore", "pauseAfter"]; const stable = keys.map((key) => `${key}:${key === "sourceText" ? String(input[key] || "").trim() : input[key] ?? ""}`).join("|"); let h = 2166136261; for (let i = 0; i < stable.length; i += 1) { h ^= stable.charCodeAt(i); h = Math.imul(h, 16777619); } return `ar1_${(h >>> 0).toString(16)}`; }
export function getClipRenderPayload(clip = {}, project = {}) { return { sourceText: String(clip.sourceText || "").trim(), provider: "narrator", voiceId: clip.voiceId || clip.voice || defaultPiperVoiceId, language: clip.language || project.language || "uk", rate: Number(clip.rate ?? 1), pitch: Number(clip.pitch ?? 1), volume: Number(clip.volume ?? 1), emotion: clip.emotion || "neutral", speaker: clip.speaker || "Narrator", characterId: clip.characterId || "narrator", pauseBefore: Number(clip.pauseBefore ?? 0), pauseAfter: Number(clip.pauseAfter ?? 0) }; }
export function createRenderJob({ projectId, novelId, chapterId, totalClips = 0 } = {}) { const now = new Date().toISOString(); return { version: audioRenderJobVersion, jobId: `render_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, projectId, novelId, chapterId, status: "idle", currentClipIndex: 0, totalClips, completedClipIds: [], failedClipIds: [], skippedClipIds: [], startedAt: null, updatedAt: now, completedAt: null, cancelledAt: null, error: "", progressPercent: 0, cacheHitCount: 0, maxRetryCount: 2 }; }
export function sanitizeRenderJob(job, fallback = {}) { try { if (!job || typeof job !== "object") throw new Error("bad"); const total = Math.max(0, Number(job.totalClips ?? fallback.totalClips ?? 0)); const completed = Array.isArray(job.completedClipIds) ? job.completedClipIds : []; const failed = Array.isArray(job.failedClipIds) ? job.failedClipIds : []; return { ...createRenderJob(fallback), ...job, version: audioRenderJobVersion, totalClips: total, currentClipIndex: Math.max(0, Number(job.currentClipIndex) || 0), completedClipIds: completed, failedClipIds: failed, skippedClipIds: Array.isArray(job.skippedClipIds) ? job.skippedClipIds : [], progressPercent: total ? Math.round((completed.length / total) * 100) : 0, status: ["idle", "queued", "rendering", "paused", "completed", "failed", "cancelled"].includes(job.status) ? job.status : "idle" }; } catch { return { ...createRenderJob(fallback), status: "idle", error: "Recovered from corrupted saved render job." }; } }
export function saveRenderJob(job, storage = globalThis.localStorage) { storage?.setItem(getRenderJobStorageKey(job.projectId, job.novelId, job.chapterId), JSON.stringify(sanitizeRenderJob(job))); return job; }
export function loadRenderJob(meta = {}, storage = globalThis.localStorage) { const raw = storage?.getItem(getRenderJobStorageKey(meta.projectId, meta.novelId, meta.chapterId)); if (!raw) return null; try { return sanitizeRenderJob(JSON.parse(raw), meta); } catch { return sanitizeRenderJob(null, meta); } }
export function applyClipRenderState(project, clipId, patch) { return { ...project, tracks: (project.tracks || []).map((track) => ({ ...track, clips: (track.clips || []).map((clip) => clip.id === clipId ? { ...clip, renderState: patch.state || clip.renderState || "not_rendered", ...patch } : clip) })) }; }
export function buildChapterPlaybackManifest(project = {}) { return { version: 1, projectId: project.id || project.projectId || `${project.novelId || "global"}:${project.chapterId || "chapter"}`, novelId: project.novelId, chapterId: project.chapterId, tracks: { speech: true, ambience: false, music: false, sfx: false }, items: orderedSpeechClips(project).flatMap((clip) => [{ type: "silence", clipId: clip.id, duration: Number(clip.pauseBefore || 0), position: "before" }, { type: "speech", clipId: clip.id, audioUrl: clip.audioUrl || "", cacheHash: clip.audioCacheHash || stableAudioCacheHash(getClipRenderPayload(clip, project)), speaker: clip.speaker, text: clip.sourceText }, { type: "silence", clipId: clip.id, duration: Number(clip.pauseAfter || 0), position: "after" }]).filter((item) => item.type === "speech" || item.duration > 0) }; }
export function classifyRenderError(error) { if (error?.name === "AbortError") return "cancelled request"; if (globalThis.navigator && !globalThis.navigator.onLine) return "worker offline"; if (error?.status === 401) return "HTTP 401 unauthorized"; if (error?.status === 429) return "HTTP 429 rate limited"; if (error?.status >= 500) return "HTTP 5xx worker error"; return error?.message || "worker offline"; }
export class AudioRenderQueue { constructor({ project, storage = globalThis.localStorage, synthesize = synthesizeVoiceWorkerAudio, onUpdate = () => {}, maxRetryCount = 2, retryBaseDelay = 25 } = {}) { this.project = project; this.storage = storage; this.synthesize = synthesize; this.onUpdate = onUpdate; this.maxRetryCount = maxRetryCount; this.retryBaseDelay = retryBaseDelay; this.controllers = new Map(); this.inFlight = new Set(); this.paused = false; this.cancelled = false; this.cache = new Map(); }
 async render({ clipIds = null, retryFailedOnly = false } = {}) { const clips = orderedSpeechClips(this.project).filter((c) => (!clipIds || clipIds.includes(c.id)) && (!retryFailedOnly || c.renderState === "failed")); let job = sanitizeRenderJob(loadRenderJob({ projectId: this.project.id || this.project.projectId, novelId: this.project.novelId, chapterId: this.project.chapterId }, this.storage), { projectId: this.project.id || this.project.projectId, novelId: this.project.novelId, chapterId: this.project.chapterId, totalClips: clips.length }); job = { ...job, status: "rendering", totalClips: clips.length, startedAt: job.startedAt || new Date().toISOString(), error: "" }; for (let i = 0; i < clips.length; i += 1) { const clip = clips[i]; while (this.paused && !this.cancelled) await new Promise((r) => setTimeout(r, 20)); if (this.cancelled) { job.cancelledAt = new Date().toISOString(); job.status = "cancelled"; break; } if (clip.renderState === "rendered" && clip.audioUrl) { job.completedClipIds = [...new Set([...job.completedClipIds, clip.id])]; continue; } job.currentClipIndex = i; const result = await this.renderClip(clip); if (result.status === "rendered") job.completedClipIds = [...new Set([...job.completedClipIds, clip.id])]; else job.failedClipIds = [...new Set([...job.failedClipIds, clip.id])]; job.progressPercent = clips.length ? Math.round((job.completedClipIds.length / clips.length) * 100) : 100; job.updatedAt = new Date().toISOString(); saveRenderJob(job, this.storage); this.onUpdate({ job, clip, result }); } if (job.status !== "cancelled") job = { ...job, status: job.failedClipIds.length ? "failed" : "completed", completedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; saveRenderJob(job, this.storage); this.onUpdate({ job }); return job; }
 async renderClip(clip) { if (this.inFlight.has(clip.id)) return { status: "skipped", reason: "duplicate request prevented" }; this.inFlight.add(clip.id); const payload = getClipRenderPayload(clip, this.project); const hash = stableAudioCacheHash(payload); try { if (this.cache.has(hash)) return { status: "rendered", cached: true, hash, audio: this.cache.get(hash) }; for (let attempt = 0; attempt <= this.maxRetryCount; attempt += 1) { try { const controller = new AbortController(); this.controllers.set(clip.id, controller); const audio = await this.synthesize({ text: payload.sourceText, sourceText: payload.sourceText, provider: payload.provider, voice: payload.voiceId, language: payload.language, signal: controller.signal, options: payload }); if (!audio?.blob) throw new Error("malformed audio response"); this.cache.set(hash, audio); return { status: "rendered", cached: false, hash, audio, attempts: attempt + 1 }; } catch (error) { if (this.cancelled || error?.name === "AbortError") return { status: "cancelled", error: classifyRenderError(error), hash }; if (attempt >= this.maxRetryCount) return { status: "failed", error: classifyRenderError(error), hash }; await new Promise((r) => setTimeout(r, this.retryBaseDelay * 2 ** attempt)); } } } finally { this.controllers.delete(clip.id); this.inFlight.delete(clip.id); } return { status: "failed", error: "unknown render failure", hash }; }
 pause() { this.paused = true; } resume() { this.paused = false; } cancel() { this.cancelled = true; for (const controller of this.controllers.values()) controller.abort(); } }
export function revokeClipObjectUrl(clip) { if (clip?.audioUrl?.startsWith("blob:")) URL.revokeObjectURL(clip.audioUrl); }
