export const SOUND_DESIGN_PLAN_VERSION = 1;
export const SOUND_DESIGN_MODES = Object.freeze({ MANUAL: "manual", ASSISTED: "assisted", FULL_AUTO: "full_auto" });
export const SOUND_CONFIDENCE_THRESHOLDS = Object.freeze({ high: .78, medium: .52 });
export const AMBIENCE_CATEGORIES = Object.freeze(["indoor room tone", "forest", "city", "village", "road", "carriage", "ship", "sea", "rain", "storm", "wind", "fire", "cave", "dungeon", "battlefield", "crowd", "tavern", "palace", "temple", "night", "silence"]);
export const SFX_CATEGORIES = Object.freeze(["footsteps", "doors", "weapons", "impacts", "cloth", "objects", "magic", "monsters", "animals", "vehicles", "weather", "environment", "crowd", "body movement"]);

const ambienceRules = [
  ["storm", /\b(storm|thunder|lightning)\b/iu], ["rain", /\b(rain|drizzle|downpour)\b/iu], ["forest", /\b(forest|woods?|trees?|leaves)\b/iu], ["city", /\b(city|street|alley|traffic)\b/iu], ["village", /\b(village|hamlet)\b/iu], ["carriage", /\b(carriage|wagon)\b/iu], ["road", /\b(road|path|trail|journey)\b/iu], ["ship", /\b(ship|deck|sailor)\b/iu], ["sea", /\b(sea|ocean|waves?|shore)\b/iu], ["wind", /\b(wind|breeze|gust)\b/iu], ["fire", /\b(fire|flames?|hearth|campfire)\b/iu], ["cave", /\b(cave|cavern)\b/iu], ["dungeon", /\b(dungeon|cell|prison)\b/iu], ["battlefield", /\b(battlefield|battle|army|siege)\b/iu], ["tavern", /\b(tavern|inn|alehouse)\b/iu], ["palace", /\b(palace|throne room|royal hall)\b/iu], ["temple", /\b(temple|shrine|sanctuary)\b/iu], ["crowd", /\b(crowd|market|festival|audience)\b/iu], ["night", /\b(night|midnight|moonlight)\b/iu], ["indoor room tone", /\b(room|hall|chamber|inside|door)\b/iu],
];
const sfxRules = [
  ["footsteps", /\b(footsteps?|steps?|boots?|walked|ran)\b/giu], ["doors", /\b(doors?|gates?)\b/giu], ["weapons", /\b(swords?|blades?|guns?|arrows?|weapons?)\b/giu], ["impacts", /\b(crashed|exploded|struck|impact|shattered)\b/giu], ["cloth", /\b(cloak|cloth|dress rustled)\b/giu], ["objects", /\b(glass|cup|book|keys?|coins?)\b/giu], ["magic", /\b(spell|magic|portal|enchanted)\b/giu], ["monsters", /\b(monster|dragon|demon|beast roared)\b/giu], ["animals", /\b(horse|dog|wolf|bird|cat)\b/giu], ["vehicles", /\b(carriage|wagon|car|train|vehicle)\b/giu], ["weather", /\b(thunder|lightning|rain struck|wind howled)\b/giu], ["crowd", /\b(crowd cheered|applause|mob shouted)\b/giu], ["body movement", /\b(gasped|fell|stood|knelt)\b/giu],
];
const revealRx = /\b(truth|revealed|realized|secret|confessed)\b/iu;
const peakRx = /\b(screamed|wept|kissed|died|victory|despair)\b/iu;
const shockRx = /\b(shock|stunned|frozen|exploded|gunshot)\b/iu;
const clamp = (n, min = 0, max = 1) => Math.min(max, Math.max(min, Number(n) || 0));
const round = (n) => Number(n.toFixed(2));
const hash = (value) => { let h = 2166136261; for (const c of String(value)) h = Math.imul(h ^ c.charCodeAt(0), 16777619); return (h >>> 0).toString(36); };
const sceneText = (scene, project) => String(scene.text || scene.sourceText || (project?.tracks || []).flatMap((t) => t.clips || []).filter((c) => c.sceneId === (scene.sceneId || scene.id)).map((c) => c.sourceText).join(" "));
const timeline = (scene) => ({ start: Number(scene.timeline?.start ?? scene.startTime ?? 0), duration: Math.max(.1, Number(scene.timeline?.duration ?? scene.duration ?? 12)) });

export function classifyAmbience(text = "", metadata = {}) {
  const haystack = `${metadata.location || ""} ${metadata.environment || ""} ${metadata.weather || ""} ${metadata.timeOfDay || ""} ${text}`;
  const found = ambienceRules.filter(([, rx]) => rx.test(haystack)).map(([category]) => category);
  const category = found[0] || "indoor room tone";
  return { category, alternatives: [...new Set(found)].slice(1, 3), confidence: found.length ? .86 : .57, reason: found.length ? `Matched explicit ${category} environment evidence.` : "No explicit location; a subtle neutral room tone protects dialogue." };
}
export function classifySfx(text = "") {
  const cues = [];
  for (const [category, rx] of sfxRules) { rx.lastIndex = 0; for (const match of text.matchAll(rx)) cues.push({ category, label: match[0], index: match.index, confidence: ["impacts", "weapons", "weather"].includes(category) ? .84 : .68, confidenceReason: `Explicit ${category} event appears in source text.` }); }
  return cues.sort((a, b) => a.index - b.index).filter((cue, index, all) => !all.slice(0, index).some((old) => old.category === cue.category && cue.index - old.index < 45)).slice(0, 4);
}
function matchAsset(type, tags, assets = [], selected = null) {
  if (selected) { const chosen = assets.find((asset) => asset.id === selected.id || asset.id === selected || asset.reference === selected.reference); if (chosen) return chosen; }
  const candidates = assets.filter((asset) => asset.type === type);
  return candidates.find((asset) => tags.every((tag) => (asset.tags || []).includes(tag))) || candidates.find((asset) => (asset.tags || []).some((tag) => tags.includes(tag)) || asset.category === tags[0]) || null;
}
function cueAsset(type, tags, assets, prior) { const asset = matchAsset(type, tags, assets, prior?.assetReference); return { assetReference: asset ? { id: asset.id, reference: asset.reference || "", userSelected: Boolean(prior?.assetReference?.userSelected) } : null, missingAsset: !asset }; }
function confidence(value, reason) { return { value: round(value), level: value >= .78 ? "high" : value >= .52 ? "medium" : "low", reason }; }

function buildScene(source, productionScene, project, options, prior) {
  if (prior?.manuallyLocked) return structuredClone(prior);
  const text = sceneText(source, project); const time = timeline(source); const meta = source.metadata || {}; const ambience = classifyAmbience(text, meta);
  const intensity = clamp(productionScene?.intensity ?? .35); const priorAmbience = prior?.ambienceLayers?.[0];
  const ambienceTags = [ambience.category]; const ambienceAsset = cueAsset("ambience", ambienceTags, options.assets, priorAmbience);
  const ambienceLayers = ambience.category === "silence" ? [] : [{ category: ambience.category, label: ambience.category, startTime: time.start, endTime: round(time.start + time.duration), loop: true, volume: round((productionScene?.sceneType === "travel" ? .32 : .18) + intensity * .08), fadeIn: 1.5, fadeOut: 1.5, pan: 0, intensity: round(intensity), ducking: .55, requiredAssetTags: ambienceTags, ...ambienceAsset, optional: false }];
  if (ambience.alternatives[0] && ambienceLayers.length < 2) { const category = ambience.alternatives[0]; ambienceLayers.push({ ...ambienceLayers[0], category, label: category, volume: .12, intensity: .25, requiredAssetTags: [category], ...cueAsset("ambience", [category], options.assets, prior?.ambienceLayers?.find((x) => x.category === category)), optional: true }); }
  const musicAllowed = !["dialogue", "quiet scene"].includes(productionScene?.sceneType) && options.sceneIndex % 2 === 0 && time.duration >= 8;
  const musicTags = [productionScene?.emotionalArc || "calm"];
  const musicCues = musicAllowed ? [{ cueId: `music_${source.id || source.sceneId}`, mood: musicTags[0], intensity: round(Math.min(.45, intensity * .5)), startTime: round(time.start + Math.min(2, time.duration * .1)), endTime: round(time.start + time.duration), fadeIn: 2.5, fadeOut: 2.5, loopRecommendation: time.duration > 45, duckingStrength: .62, transitionRole: productionScene?.transitionOut?.type === "ambience bridge" ? "music bridge" : "underscore", requiredAssetTags: musicTags, ...cueAsset("music", musicTags, options.assets, prior?.musicCues?.[0]), optional: true }] : [];
  const detected = classifySfx(text); const sfxCues = detected.map((item, index) => { const cueId = `sfx_${source.id || source.sceneId}_${item.category}_${index}`; const priorCue = prior?.sfxCues?.find((x) => x.cueId === cueId); const tags = [item.category, item.label.toLowerCase()]; return { cueId, sourceClipId: (project?.tracks || []).flatMap((t) => t.clips || []).find((c) => c.sceneId === (source.id || source.sceneId) && String(c.sourceText).includes(item.label))?.id || null, sourceTextReference: item.label, category: item.category, label: item.label, timingOffset: round(Math.min(time.duration - .1, (item.index / Math.max(1, text.length)) * time.duration)), duration: item.category === "impacts" ? 1.2 : .8, intensity: item.category === "impacts" ? .72 : .42, volume: item.category === "impacts" ? .62 : .38, pan: 0, requiredAssetTags: tags, ...cueAsset("sfx", tags, options.assets, priorCue), optional: !["impacts", "weapons"].includes(item.category), confidence: confidence(item.confidence, item.confidenceReason) }; });
  const silenceRegions = [];
  if (revealRx.test(text)) silenceRegions.push({ startTime: round(time.start + time.duration * .42), endTime: round(time.start + time.duration * .42 + .65), reason: "Silence before revelation", optional: false });
  if (peakRx.test(text) || shockRx.test(text)) silenceRegions.push({ startTime: round(time.start + time.duration * .82), endTime: round(Math.min(time.start + time.duration, time.start + time.duration * .82 + .55)), reason: shockRx.test(text) ? "Silence after major impact or shock" : "Silence after emotional peak", optional: true });
  const sceneConfidence = confidence((ambience.confidence + (detected.length ? detected.reduce((s, x) => s + x.confidence, 0) / detected.length : .65)) / 2, `${ambience.reason} ${detected.length ? "Priority events were selected rather than sonifying every verb." : "No scene-important SFX event was found."}`);
  const transitionType = ({ crossfade: "ambience crossfade", "ambience bridge": "ambience crossfade", silence: "silence cut", "hard cut": "hard cut" })[productionScene?.transitionOut?.type] || "fade to silence";
  return { sceneId: source.id || source.sceneId, location: meta.location || productionScene?.ambiencePlan?.sceneLocation || "unspecified", environment: meta.environment || ambience.category, weather: meta.weather || productionScene?.ambiencePlan?.weather || "unspecified", timeOfDay: meta.timeOfDay || "unspecified", ambienceLayers, musicCues, sfxCues, silenceRegions, transitionPlan: { type: transitionType, duration: productionScene?.transitionOut?.length ?? 1.2, preservesProductionIntent: true, sourceIntent: productionScene?.transitionOut?.type || null }, dynamicRangePlan: { speechDominant: true, musicDucking: .62, ambienceDucking: .55, sfxTransientLimitDb: -6, loudnessTargetLufs: productionScene?.sceneType === "battle" ? -18 : -20, peakTargetDb: -1, preventCumulativeClipping: true }, confidence: sceneConfidence, manuallyLocked: Boolean(prior?.manuallyLocked), sourceFingerprint: hash(text) };
}

export function createSoundDesignPlan(productionPlan, project, options = {}) {
  const mode = Object.values(SOUND_DESIGN_MODES).includes(options.mode) ? options.mode : SOUND_DESIGN_MODES.ASSISTED; const prior = options.previousPlan; const sources = project?.scenes || productionPlan?.scenes || [];
  const scenePlans = sources.map((source, sceneIndex) => buildScene(source, productionPlan?.scenes?.find((x) => x.sceneId === (source.id || source.sceneId)), project, { ...options, sceneIndex }, prior?.scenePlans?.find((x) => x.sceneId === (source.id || source.sceneId))));
  const now = new Date().toISOString(); const plan = { soundDesignPlanId: options.soundDesignPlanId || prior?.soundDesignPlanId || `sound_design_${hash(productionPlan?.productionPlanId || project?.chapterId)}`, productionPlanId: productionPlan?.productionPlanId || null, mixerProjectId: options.mixerProject?.mixerProjectId || productionPlan?.mixerProjectId || null, projectId: project?.id || project?.projectId || productionPlan?.projectId || null, novelId: project?.novelId || productionPlan?.novelId || null, chapterId: project?.chapterId || productionPlan?.chapterId || null, version: SOUND_DESIGN_PLAN_VERSION, mode, status: "cue_plan_ready", scenePlans, globalSettings: { maxAmbienceLayers: 2, constantMusic: false, speechPriority: true, defaultMusicDucking: .62, defaultAmbienceDucking: .55, sfxTransientLimitDb: -6, lowFrequencyAmbience: "sparingly" }, assetRequirements: scenePlans.flatMap((s) => [...s.ambienceLayers, ...s.musicCues, ...s.sfxCues].filter((c) => c.missingAsset).map((c) => ({ sceneId: s.sceneId, tags: c.requiredAssetTags, category: c.category || c.mood }))), warnings: [], confidence: confidence(scenePlans.reduce((sum, s) => sum + s.confidence.value, 0) / Math.max(1, scenePlans.length), "Average of scene evidence and cue relevance confidence."), createdAt: prior?.createdAt || now, updatedAt: now };
  plan.warnings = getSoundDesignWarnings(plan); return plan;
}

const allCues = (scene) => [...scene.ambienceLayers.map((c) => ({ ...c, cueType: "ambience", cueId: c.cueId || `ambience_${scene.sceneId}_${c.category}` })), ...scene.musicCues.map((c) => ({ ...c, cueType: "music" })), ...scene.sfxCues.map((c) => ({ ...c, cueType: "sfx" }))];
export function shouldApplyCue(cue, mode) { const value = cue.confidence?.value ?? .8; if (mode === SOUND_DESIGN_MODES.MANUAL || value < SOUND_CONFIDENCE_THRESHOLDS.medium) return false; return mode === SOUND_DESIGN_MODES.FULL_AUTO ? value >= SOUND_CONFIDENCE_THRESHOLDS.high : value >= SOUND_CONFIDENCE_THRESHOLDS.medium; }
export function applySoundDesignPlan(mixer, plan) {
  if (!mixer) throw new Error("Build a mixer project before applying sound design."); const original = structuredClone(mixer); const trackTypes = { ambience: "ambience", music: "music", sfx: "sound_effects" }; const overrides = {};
  const tracks = mixer.tracks.map((track) => { const generated = plan.scenePlans.filter((s) => !s.manuallyLocked).flatMap((scene) => allCues(scene).filter((cue) => trackTypes[cue.cueType] === track.trackType && shouldApplyCue(cue, plan.mode) && !cue.missingAsset).map((cue) => { const clipId = `sd_${cue.cueId}`; const clip = { clipId, sourceClipId: cue.sourceClipId || cue.cueId, sceneId: scene.sceneId, startTime: cue.startTime ?? ((mixer.tracks.flatMap((t) => t.clips).find((c) => c.sceneId === scene.sceneId)?.startTime || 0) + (cue.timingOffset || 0)), duration: Math.max(.1, (cue.endTime != null ? cue.endTime - cue.startTime : cue.duration)), fadeIn: cue.fadeIn || 0, fadeOut: cue.fadeOut || 0, volume: cue.volume ?? cue.intensity ?? .3, pan: cue.pan || 0, loop: Boolean(cue.loop || cue.loopRecommendation), audioReference: cue.assetReference.reference, missingAudio: false, soundDesignOverride: true }; overrides[clipId] = { sceneId: scene.sceneId, cueId: cue.cueId, cueType: cue.cueType, before: null, after: clip, confidence: cue.confidence || scene.confidence, reason: cue.confidence?.reason || scene.confidence.reason }; return clip; })); return { ...track, clips: [...track.clips, ...generated].sort((a, b) => a.startTime - b.startTime) }; });
  return { ...mixer, tracks, soundDesign: { planId: plan.soundDesignPlanId, original, overrides, appliedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() };
}
export function revertSoundDesignPlan(mixer, { sceneId, cueId } = {}) { if (!mixer?.soundDesign?.original) return mixer; if (!sceneId && !cueId) return structuredClone(mixer.soundDesign.original); const remove = new Set(Object.entries(mixer.soundDesign.overrides).filter(([, x]) => (!sceneId || x.sceneId === sceneId) && (!cueId || x.cueId === cueId)).map(([id]) => id)); return { ...mixer, tracks: mixer.tracks.map((t) => ({ ...t, clips: t.clips.filter((c) => !remove.has(c.clipId)) })), soundDesign: { ...mixer.soundDesign, overrides: Object.fromEntries(Object.entries(mixer.soundDesign.overrides).filter(([id]) => !remove.has(id))) } }; }
export function generateSoundDesignDiff(before, after) { const changes = Object.entries(after?.soundDesign?.overrides || {}).map(([clipId, x]) => ({ clipId, sceneId: x.sceneId, cueId: x.cueId, changeType: x.before ? "modified" : "added", assetChange: x.before?.audioReference !== x.after.audioReference, timingChange: x.before?.startTime !== x.after.startTime, confidence: x.confidence, reason: x.reason, preservedManualEdit: false })); return { addedCues: changes.filter((x) => x.changeType === "added"), removedCues: [], modifiedCues: changes.filter((x) => x.changeType === "modified"), assetChanges: changes.filter((x) => x.assetChange), timingChanges: changes.filter((x) => x.timingChange), preservedManualEdits: (before?.tracks || []).flatMap((t) => t.clips).filter((c) => c.manuallyEdited).map((c) => c.clipId), changes }; }
export function getSoundDesignWarnings(plan) { const warnings = []; const add = (code, message, sceneId, cueId) => warnings.push({ code, message, sceneId, cueId }); for (const scene of plan.scenePlans) { const cues = allCues(scene); cues.filter((c) => c.missingAsset).forEach((c) => add("missing-asset", `No registered asset matches ${c.requiredAssetTags.join(", ")}.`, scene.sceneId, c.cueId)); cues.filter((c) => (c.confidence?.value ?? scene.confidence.value) < .52).forEach((c) => add("low-confidence-cue", "Cue remains a suggestion only.", scene.sceneId, c.cueId)); if (cues.length > 7) add("excessive-cue-density", "Cue density may mask speech.", scene.sceneId); if (scene.sfxCues.some((c, i, a) => a.slice(0, i).some((x) => x.category === c.category && Math.abs(x.timingOffset - c.timingOffset) < 1.5))) add("repeated-sfx", "Repeated SFX are too close together.", scene.sceneId); if (scene.sfxCues.filter((c) => c.volume > .6).length > 1) add("overlapping-loud-effects", "Multiple strong transients may overlap.", scene.sceneId); if (scene.ambienceLayers.length > plan.globalSettings.maxAmbienceLayers) add("ambience-conflict", "Too many simultaneous ambience layers.", scene.sceneId); if (scene.musicCues.length > 1) add("music-conflict", "Overlapping music cues conflict.", scene.sceneId); if (cues.some((c) => (c.volume || c.intensity) > .7)) add("speech-masking-risk", "A loud cue may mask dialogue; ducking is required.", scene.sceneId); const energy = cues.reduce((sum, c) => sum + (c.volume || c.intensity || 0), 0); if (energy > 2.6) add("clipping-risk", "Cumulative cue gain may clip.", scene.sceneId); if (!scene.transitionPlan?.type) add("unresolved-transition", "Scene transition is unresolved.", scene.sceneId); } return warnings; }
export function calculateSoundDesignScore(plan) { const warnings = getSoundDesignWarnings(plan); const count = (code) => warnings.filter((w) => w.code === code).length; const score = (n) => Math.max(0, Math.min(100, Math.round(n))); const result = { speechClarity: score(100 - count("speech-masking-risk") * 14 - count("clipping-risk") * 8), ambienceConsistency: score(96 - count("ambience-conflict") * 18), musicRestraint: score(100 - count("music-conflict") * 20 - Math.max(0, plan.scenePlans.flatMap((s) => s.musicCues).length / Math.max(1, plan.scenePlans.length) - .6) * 30), sfxRelevance: score(94 - count("repeated-sfx") * 12 - count("low-confidence-cue") * 5), transitionQuality: score(96 - count("unresolved-transition") * 20), assetCompleteness: score(100 - count("missing-asset") * 7), dynamicRange: score(98 - count("clipping-risk") * 18 - count("excessive-cue-density") * 10) }; result.overallScore = round(Object.values(result).reduce((a, b) => a + b, 0) / 7); return result; }
export function generateSoundDesignReport(plan) { return { soundDesignPlanId: plan.soundDesignPlanId, chapterOverview: `${plan.scenePlans.length} scenes planned in ${plan.mode} mode.`, sceneBySceneCuePlan: plan.scenePlans, ambienceSummary: plan.scenePlans.flatMap((s) => s.ambienceLayers.map((c) => ({ sceneId: s.sceneId, ...c }))), musicSummary: plan.scenePlans.flatMap((s) => s.musicCues.map((c) => ({ sceneId: s.sceneId, ...c }))), sfxSummary: plan.scenePlans.flatMap((s) => s.sfxCues.map((c) => ({ sceneId: s.sceneId, ...c }))), silenceSummary: plan.scenePlans.flatMap((s) => s.silenceRegions.map((c) => ({ sceneId: s.sceneId, ...c }))), missingAssets: plan.assetRequirements, warnings: getSoundDesignWarnings(plan), confidence: plan.confidence, scores: calculateSoundDesignScore(plan), generatedAt: new Date().toISOString() }; }
export function migrateSoundDesignPlan(input, fallback = {}) { let raw; try { raw = typeof input === "string" ? JSON.parse(input) : input; } catch { return null; } if (!raw || typeof raw !== "object") return null; const now = new Date().toISOString(); return { soundDesignPlanId: raw.soundDesignPlanId || `sound_design_${hash(raw.chapterId || "recovered")}`, productionPlanId: raw.productionPlanId || null, mixerProjectId: raw.mixerProjectId || null, projectId: raw.projectId || fallback.projectId || null, novelId: raw.novelId || null, chapterId: raw.chapterId || null, version: SOUND_DESIGN_PLAN_VERSION, mode: Object.values(SOUND_DESIGN_MODES).includes(raw.mode) ? raw.mode : SOUND_DESIGN_MODES.MANUAL, status: raw.status || "draft", scenePlans: (Array.isArray(raw.scenePlans) ? raw.scenePlans : raw.scenes || []).map((s, i) => ({ location: "unspecified", environment: "unspecified", weather: "unspecified", timeOfDay: "unspecified", ambienceLayers: [], musicCues: [], sfxCues: [], silenceRegions: [], transitionPlan: {}, dynamicRangePlan: {}, confidence: confidence(0, "Migrated legacy scene."), ...s, sceneId: s.sceneId || s.id || `scene_${i + 1}`, manuallyLocked: Boolean(s.manuallyLocked) })), globalSettings: raw.globalSettings || {}, assetRequirements: Array.isArray(raw.assetRequirements) ? raw.assetRequirements : [], warnings: Array.isArray(raw.warnings) ? raw.warnings : [], confidence: raw.confidence?.value != null ? raw.confidence : confidence(raw.confidence || 0, "Migrated plan confidence."), createdAt: raw.createdAt || now, updatedAt: now }; }
export function serializeSoundDesignPlan(plan) { return JSON.stringify(migrateSoundDesignPlan(plan), null, 2); }
export function saveSoundDesignPlan(plan, storage = globalThis.localStorage) { const safe = migrateSoundDesignPlan(plan); if (!safe) throw new Error("Malformed sound-design plan."); storage?.setItem(`novelverse.soundDesign.v1:${safe.projectId}:${safe.version}`, serializeSoundDesignPlan(safe)); return safe; }
export function loadSoundDesignPlan(projectId, storage = globalThis.localStorage) { try { return migrateSoundDesignPlan(storage?.getItem(`novelverse.soundDesign.v1:${projectId}:${SOUND_DESIGN_PLAN_VERSION}`)); } catch { return null; } }
export function invalidateSoundDesignScenes(plan, productionPlan, project) { const production = new Map((productionPlan?.scenes || []).map((s) => [s.sceneId, s])); return { ...plan, productionPlanId: productionPlan?.productionPlanId || plan.productionPlanId, scenePlans: plan.scenePlans.map((s) => { if (s.manuallyLocked) return s; const source = (project?.scenes || []).find((x) => (x.id || x.sceneId) === s.sceneId); return hash(sceneText(source || {}, project)) === s.sourceFingerprint && production.has(s.sceneId) ? s : { ...s, status: "invalidated", invalidatedReason: "Production or source scene changed." }; }), updatedAt: new Date().toISOString() }; }
