import test from "node:test";
import assert from "node:assert/strict";
import { applyProductionPlan, calculateProductionScore, classifyProductionScene, createProductionPlan, generateProductionDiff, generateProductionReport, getProductionWarnings, migrateProductionPlan, PRODUCTION_MODES, revertProductionPlan, shouldApplyScene } from "../src/lib/aiProductionEngine.js";

const project = { id: "p1", novelId: "n1", chapterId: "c1", scenes: [{ id: "scene_1", text: "The shadow waited in silence behind the door. The truth was close.", timeline: { start: 0, duration: 12 }, metadata: {} }, { id: "scene_2", text: '"Run now!" Mira shouted. The tower exploded.', timeline: { start: 13, duration: 8 }, metadata: {} }], tracks: [{ id: "narrator", clips: [{ id: "c1", sceneId: "scene_1", clipType: "narrator", sourceText: "The shadow waited in silence behind the door.", sourceOrder: 0, start: 0, duration: 5, rate: 1, pitch: 1, volume: .9, voiceId: "piper-a" }, { id: "c2", sceneId: "scene_2", clipType: "dialogue", sourceText: '"Run now!"', sourceOrder: 1, start: 13, duration: 2, rate: 1, pitch: 1, volume: .9, voiceId: "mira-v1", characterId: "mira", manuallyEdited: true }] }] };

test("scene classification and emotional arc are deterministic", () => { const a = classifyProductionScene(project.scenes[0]); assert.deepEqual(a, classifyProductionScene(project.scenes[0])); assert.equal(a.sceneType, "suspense"); assert.equal(a.emotionalArc, "tense"); });
test("plan implements the versioned scene schema and cue metadata", () => { const plan = createProductionPlan(project); assert.equal(plan.version, 2); assert.ok(["productionPlanId", "projectId", "mixerProjectId", "novelId", "chapterId", "mode", "status", "scenes", "transitions", "globalSettings", "confidence", "warnings", "createdAt", "updatedAt"].every((key) => key in plan)); assert.ok(["sceneId", "sceneType", "emotionalArc", "tensionLevel", "pacing", "intensity", "narrationStyle", "ambiencePlan", "musicPlan", "sfxPlan", "pausePlan", "transitionIn", "transitionOut", "confidence", "manuallyLocked"].every((key) => key in plan.scenes[0])); });
test("confidence thresholds honor manual, assisted, and full auto modes", () => { const medium = { confidence: .6 }; const high = { confidence: .9 }; assert.equal(shouldApplyScene(high, PRODUCTION_MODES.MANUAL), false); assert.equal(shouldApplyScene(medium, PRODUCTION_MODES.ASSISTED), true); assert.equal(shouldApplyScene(medium, PRODUCTION_MODES.FULL_AUTO), false); assert.equal(shouldApplyScene(high, PRODUCTION_MODES.FULL_AUTO), true); });
test("application preserves source, order, character voice, and manual edits", () => { const plan = createProductionPlan(project, { mode: PRODUCTION_MODES.ASSISTED }); const applied = applyProductionPlan(project, plan); assert.deepEqual(applied.tracks[0].clips.map((c) => c.sourceText), project.tracks[0].clips.map((c) => c.sourceText)); assert.deepEqual(applied.tracks[0].clips.map((c) => c.sourceOrder), [0, 1]); assert.equal(applied.tracks[0].clips[1].voiceId, "mira-v1"); assert.equal(applied.tracks[0].clips[1].rate, 1); });
test("locked scenes are not overridden", () => { const plan = createProductionPlan(project, { mode: PRODUCTION_MODES.ASSISTED }); plan.scenes[0].manuallyLocked = true; assert.equal(applyProductionPlan(project, plan).tracks[0].clips[0].productionOverride, undefined); });
test("diff and whole, scene, and clip reverts are non-destructive", () => { const plan = createProductionPlan(project, { mode: PRODUCTION_MODES.ASSISTED }); const applied = applyProductionPlan(project, plan); const diff = generateProductionDiff(project, applied); assert.ok(diff.changedClips.length > 0); assert.deepEqual(revertProductionPlan(applied), project); const scene = revertProductionPlan(applied, { sceneId: "scene_1" }); assert.equal(scene.tracks[0].clips[0].productionOverride, undefined); });
test("music, SFX, and speech overlap warnings are generated", () => { const overlap = structuredClone(project); overlap.tracks[0].clips[1].start = 1; const plan = createProductionPlan(overlap); plan.scenes.forEach((scene) => { scene.musicPlan.intensity = .8; }); plan.scenes[0].sfxPlan = Array.from({ length: 4 }, (_, i) => ({ category: String(i) })); const codes = getProductionWarnings(plan, overlap).map((w) => w.code); assert.ok(codes.includes("excessive-music-density")); assert.ok(codes.includes("excessive-sfx-density")); assert.ok(codes.includes("speech-overlap")); });
test("production score and report are stable and complete", () => { const plan = createProductionPlan(project); const score = calculateProductionScore(plan, project); assert.ok(score.overallScore >= 0 && score.overallScore <= 100); const report = generateProductionReport(plan, project); assert.equal(report.sceneBreakdown.length, 2); assert.ok(Array.isArray(report.manualEditsPreserved)); });
test("older plans migrate safely and preserve locks", () => { const migrated = migrateProductionPlan({ version: 1, chapterId: "old", scenes: [{ id: "s", manuallyLocked: true }] }); assert.equal(migrated.version, 2); assert.equal(migrated.scenes[0].sceneId, "s"); assert.equal(migrated.scenes[0].manuallyLocked, true); });
