import test from "node:test";
import assert from "node:assert/strict";
import { buildDuckingEnvelope, buildMixerProject, buildPreviewManifest, effectiveTrackState, encodeWav, migrateMixerProject, MixerExportJob, MIXER_TRACK_ORDER, rebuildChangedTracks } from "../src/lib/audioMixer.js";

const source = { projectId: "p1", novelId: "n1", chapterId: "c1", duration: 20, scenes: [{ id: "s1", timeline: { start: 0, duration: 10 } }, { id: "s2", timeline: { start: 10, duration: 10 } }], tracks: [
  { id: "narrator", type: "narrator", clips: [{ id: "a", clipType: "narrator", sourceOrder: 0, sceneId: "s1", duration: 2, pauseBefore: 500, pauseAfter: 1, audioUrl: "blob:a" }] },
  { id: "character_x", type: "character", clips: [{ id: "b", clipType: "dialogue", sourceOrder: 1, sceneId: "s1", duration: 3, pauseBefore: .5, audioUrl: "blob:b" }] },
  { id: "ambience", type: "ambient", clips: [{ id: "amb", clipType: "ambience", sceneId: "s1", start: 0, duration: 10, title: "rain" }, { id: "amb2", clipType: "ambience", sceneId: "s2", start: 10, duration: 10 }] },
  { id: "music", type: "music", clips: [{ id: "music", clipType: "music", sceneId: "s1", start: 0, duration: 10, volume: .4 }] },
  { id: "sfx", type: "sfx", clips: [{ id: "fx", clipType: "sfx", sceneId: "s1", sourceOrder: 4, start: 4, duration: 2 }] },
] };

test("builds stable ordered tracks and places speech sequentially with pauses", () => { const mix = buildMixerProject(source); assert.deepEqual(mix.tracks.map((t) => t.trackType), MIXER_TRACK_ORDER); const speech = mix.tracks.filter((t) => ["narrator", "character_dialogue"].includes(t.trackType)).flatMap((t) => t.clips).sort((a, b) => a.startTime - b.startTime); assert.equal(speech[0].startTime, .5); assert.equal(speech[1].startTime, 4); assert.ok(speech[0].startTime + speech[0].duration <= speech[1].startTime); assert.equal(mix.tracks.find((t) => t.trackType === "silence_pauses").clips.length, 3); });
test("places scene ambience, music and editable missing SFX", () => { const mix = buildMixerProject(source); const ambience = mix.tracks.find((t) => t.trackType === "ambience").clips; assert.deepEqual(ambience.map((c) => c.startTime), [0, 10]); assert.ok(ambience.every((c) => c.loop && c.missingAudio)); assert.equal(mix.tracks.find((t) => t.trackType === "music").clips[0].volume, .4); assert.equal(mix.tracks.find((t) => t.trackType === "sound_effects").clips[0].missingAudio, true); });
test("ducking envelopes surround speech without modifying clips", () => { const mix = buildMixerProject(source); const original = structuredClone(mix.tracks); const envelope = buildDuckingEnvelope(mix); assert.ok(envelope.some((point) => point.gainDb === -12)); assert.deepEqual(mix.tracks, original); });
test("mute and solo behavior and preview ordering are deterministic", () => { const mix = buildMixerProject(source); mix.tracks[0].solo = true; assert.equal(effectiveTrackState(mix.tracks).filter((t) => t.audible).length, 1); mix.tracks[0].solo = false; mix.tracks[0].muted = true; assert.equal(effectiveTrackState(mix.tracks)[0].audible, false); const manifest = buildPreviewManifest(buildMixerProject(source)); assert.deepEqual(manifest.items.map((c) => c.startTime), [...manifest.items.map((c) => c.startTime)].sort((a, b) => a - b)); assert.ok(manifest.missingAssets.length >= 4); });
test("rebuild preserves unrelated manual edits and invalidates changed clips", () => { const old = buildMixerProject(source); const narrator = old.tracks[0].clips[0]; narrator.volume = .2; narrator.manuallyEdited = true; const rebuilt = rebuildChangedTracks(source, old, ["b"]); assert.equal(rebuilt.tracks[0].clips[0].volume, .2); assert.equal(rebuilt.tracks.find((t) => t.trackType === "character_dialogue").clips[0].manuallyEdited, false); });
test("migration repairs older mixer projects and rejects corruption", () => { const migrated = migrateMixerProject({ version: 0, tracks: [{ type: "narrator", clips: [] }] }); assert.equal(migrated.version, 1); assert.equal(migrated.tracks.length, 7); assert.throws(() => migrateMixerProject({ nope: true }), /Corrupted/); });
test("WAV encoder writes valid metadata", async () => { const blob = encodeWav({ channels: [new Float32Array([0, .5, -1])], sampleRate: 44100 }); const bytes = new Uint8Array(await blob.arrayBuffer()); assert.equal(new TextDecoder().decode(bytes.slice(0, 4)), "RIFF"); assert.equal(new DataView(bytes.buffer).getUint32(24, true), 44100); assert.equal(new DataView(bytes.buffer).getUint16(22, true), 1); });
test("chunked export supports cancellation", async () => { const mix = buildMixerProject({ ...source, duration: 1 }); mix.exportSettings = { ...mix.exportSettings, sampleRate: 100, channelCount: 1, chunkSeconds: .1 }; const job = new MixerExportJob({ onProgress: () => job.cancel() }); await assert.rejects(job.export(mix, async ({ frames }) => [new Float32Array(frames)]), (error) => error.name === "AbortError"); assert.equal(job.running, false); });
