import test from "node:test";
import assert from "node:assert/strict";
import { AnalysisQueue, applyAnalysis, applyCueMatch, canDeleteAsset, checksumBlob, clearAutomaticMatches, createAssetLibrary, createAssetMetadata, createLibraryReport, editAsset, findDuplicates, matchCue, migrateAssetLibrary, replaceAsset, scoreAssetMatch, trackAssetUsage } from "../src/lib/audioAssetLibrary.js";

const asset = (patch = {}) => createAssetMetadata({ assetId: patch.assetId || "a1", fileName: "forest-loop.wav", checksum: "one", duration: 12, assetType: "ambience", tags: ["forest", "outdoor"], categories: ["environment"], moods: ["calm"], environments: ["forest"], intensity: "low", loopCandidate: true, analysisStatus: "complete", ...patch });
test("checksum and exact duplicate detection", async () => { const blob = new Blob(["same"]); const checksum = await checksumBlob(blob); assert.equal(checksum, await checksumBlob(blob)); assert.equal(findDuplicates([asset({ checksum })], asset({ assetId: "a2", checksum }))[0].exact, true); });
test("metadata migration and malformed recovery", () => { const old = { libraryId: "old", version: 0, assets: [{ id: "x", name: "rain.wav" }] }; assert.equal(migrateAssetLibrary(old).version, 1); assert.equal(migrateAssetLibrary("bad").assets.length, 0); });
test("manual tags and fields survive reanalysis", () => { const edited = editAsset(asset(), { tags: ["custom"], intensity: "high" }); const result = applyAnalysis(edited, { duration: 9, tags: ["generated"], loopCandidate: false }); assert.ok(result.tags.includes("custom")); assert.equal(result.intensity, "high"); });
test("exact tags outrank compatible categories", () => { const cue = { requiredAssetTags: ["forest"], category: "ambience" }; const ranked = matchCue(cue, [asset(), asset({ assetId: "a2", tags: [], categories: ["environment"] })]); assert.equal(ranked[0].asset.assetId, "a1"); });
test("compatible category matching contributes score", () => { const score = scoreAssetMatch(asset({ tags: [], categories: ["door"], assetType: "sfx" }), { category: "doors", assetType: "sfx" }); assert.ok(score.categoryScore > 0); });
test("semantic conflicts reject automatic matching", () => { const score = scoreAssetMatch(asset({ tags: ["indoor"] }), { requiredAssetTags: ["outdoor"] }); assert.equal(score.overallScore, 0); assert.equal(applyCueMatch({}, { asset: asset(), score }, { mode: "full-auto" }).assetSelection, undefined); });
test("intensity and loop suitability are scored", () => { const exact = scoreAssetMatch(asset({ intensity: "high" }), { intensity: "high", loop: true }); const wrong = scoreAssetMatch(asset({ intensity: "low", loopCandidate: false }), { intensity: "high", loop: true }); assert.ok(exact.intensityScore > wrong.intensityScore); assert.ok(exact.loopScore > wrong.loopScore); });
test("repetition penalty and favorite bonus are transparent", () => { const normal = scoreAssetMatch(asset({ assetType: "sfx" }), { assetType: "sfx" }); const adjusted = scoreAssetMatch(asset({ assetType: "sfx", favorite: true }), { assetType: "sfx" }, { recentAssetIds: ["a1"] }); assert.equal(adjusted.repetitionPenalty, -.18); assert.equal(adjusted.favoriteBonus, .04); assert.ok(normal.overallScore > adjusted.overallScore); });
test("locked cue is preserved and automatic cue can clear", () => { const locked = { assetSelection: { locked: true, assetId: "a1" } }; assert.equal(applyCueMatch(locked, matchCue({}, [asset()])[0], { mode: "manual" }), locked); assert.equal(clearAutomaticMatches([{ assetSelection: { automatic: true } }])[0].assetSelection, null); });
test("missing and invalid assets are excluded", () => { assert.equal(matchCue({}, [asset({ missing: true }), asset({ assetId: "a2", invalid: true })]).length, 0); });
test("replacement preserves asset id, usage and manual values", () => { const before = editAsset(trackAssetUsage(asset(), { chapterId: "c", sceneId: "s", cueId: "q" }), { displayName: "Mine" }); const next = replaceAsset(before, { fileName: "new.wav", checksum: "new" }); assert.equal(next.assetId, "a1"); assert.equal(next.displayName, "Mine"); assert.equal(next.usage.usageCount, 1); });
test("usage tracking and deletion warning", () => { const used = trackAssetUsage(asset(), { chapterId: "c", sceneId: "s", cueId: "q" }); assert.deepEqual(used.usage.chapters, ["c"]); assert.equal(canDeleteAsset(used).allowed, false); });
test("analysis queue cancellation leaves unfinished work cancelled", async () => { let queue; queue = new AnalysisQueue({ concurrency: 1, analyze: async (item) => { if (item === 1) queue.cancel(); return item; } }); const results = await queue.run([1, 2]); assert.equal(results.find((x) => x.item === 2).status, "cancelled"); });
test("library report summarizes quality, usage and cue coverage", () => { const library = createAssetLibrary({ assets: [asset(), asset({ assetId: "a2", missing: true, checksum: "two" })] }); const report = createLibraryReport(library, [{ assetSelection: { score: { confidence: "high" } } }, {}]); assert.equal(report.totalAssets, 2); assert.equal(report.missingAssets, 1); assert.equal(report.cueCoverage, .5); assert.equal(report.unresolvedCues, 1); });
