import test from "node:test";
import assert from "node:assert/strict";
import { buildBusinessAnalytics, configureProviders, createBillingSchedule, createGift, detectFraud, eligibleAds, evaluatePromotion, exportReport, generateFinancialReport, handlePaymentFailure, redeemReferral } from "../src/lib/commerce.js";

test("configures supported payment adapters", () => { assert.deepEqual(configureProviders([{id:"stripe",enabled:true,currencies:["USD","USD"]}])[0].currencies,["USD"]); assert.throws(()=>configureProviders([{id:"bank"}]),/Unsupported/); });
test("schedules recurring and lifetime billing", () => { assert.match(createBillingSchedule({interval:"quarterly",startedAt:"2026-01-31"}).renewalAt,/2026-05-01/); assert.equal(createBillingSchedule({interval:"lifetime",startedAt:"2026-01-01"}).autoRenew,false); });
test("moves failed billing into grace period with retries",()=>{ const value=handlePaymentFailure({id:"s1"},new Date("2026-01-01"),[1,3],7); assert.equal(value.status,"past_due"); assert.equal(value.retry_at.length,2); assert.match(value.grace_ends_at,/2026-01-08/); });
test("applies campaign eligibility and discount safely",()=>{ const p={active:true,type:"regional",regions:["UA"],percentOff:50}; assert.equal(evaluatePromotion(p,{region:"UA",subtotalCents:1299}).totalCents,649); assert.equal(evaluatePromotion(p,{region:"US",subtotalCents:1299}).eligible,false); });
test("rewards both referral parties",()=>{ const result=redeemReferral({active:true,code:"FRIEND",ownerUserId:"a",inviterBenefit:"month",inviteeBenefit:"trial",redemptions:0,maxRedemptions:2},"b",new Date("2026-01-01")); assert.deepEqual(result.rewards.map(r=>r.userId),["a","b"]); });
test("creates a redeemable gift for another account",()=>{ const gift=createGift({purchaserUserId:"a",recipientUserId:"b",planId:"premium",interval:"yearly"},()=>"token"); assert.equal(gift.token,"token"); assert.throws(()=>createGift({purchaserUserId:"a",recipientUserId:"a",interval:"monthly"})); });
test("enforces ad plan, placement, schedule and frequency",()=>{ const campaign={id:"ad",active:true,eligiblePlans:["basic"],placements:["player"],frequencyLimit:2,startsAt:"2026-01-01",endsAt:"2027-01-01"}; assert.equal(eligibleAds([campaign],{planId:"basic",placement:"player",now:new Date("2026-06-01"),impressions:{ad:1}}).length,1); assert.equal(eligibleAds([campaign],{planId:"premium",placement:"player",now:new Date("2026-06-01")}).length,0); });
test("computes complete business analytics",()=>{ const result=buildBusinessAnalytics({subscriptions:[{status:"active",region:"UA",trialStartedAt:"x",convertedFromTrial:true},{status:"cancelled"}],payments:[{status:"paid",paidAt:"2026-07-20",amountCents:100}],listening:[{minutes:20,bookTitle:"Book",author:"Author",device:"ios"}]},new Date("2026-07-26")); assert.equal(result.monthlyRevenue,100); assert.equal(result.churnRate,.5); assert.equal(result.topAuthors[0].name,"Author"); });
test("generates and exports financial reports",()=>{ const report=generateFinancialReport([{id:"p",createdAt:"2026-07-02",provider:"stripe",currency:"USD",amountCents:1000,taxCents:100,status:"paid"}],{from:"2026-07-01",to:"2026-08-01",period:"monthly"}); assert.equal(report.totals.netCents,900); assert.match(exportReport(report,"csv").data,/grossCents/); assert.equal(exportReport(report,"pdf").renderer,"pdf"); });
test("detects fraud signals",()=>{ const now=new Date().toISOString(); const result=detectFraud({logins:[{at:now,region:"US",concurrentStreams:2}],devices:[],subscriptions:[]}); assert.deepEqual(result.reasons,["account_sharing"]); });
