import test from "node:test";
import assert from "node:assert/strict";
import { applyNarrationOverride, createNarrationPlan, generateNarrationReport, NARRATION_MODES } from "../src/lib/narrationEngine.js";

const text = 'Mara entered the Tower of Ash. “The silver key was yours all along!” he shouted. *I remembered years ago, and wondered why.* Blood covered the sword. I love you... goodbye!';

test("narration generation is deterministic and preserves source exactly", () => { const a = createNarrationPlan(text); const b = createNarrationPlan(text); assert.deepEqual(a, b); assert.equal(a.segments.map((x) => x.source.text).join(""), text); assert.equal(a.source.text, text); });
test("metadata schema and values remain stable", () => { const plan = createNarrationPlan(text); const keys = ["speechRate", "pause", "emphasis", "intensity", "breathing", "pitchModifier", "energy", "whisperLevel", "emotionalWeight"]; assert.deepEqual(Object.keys(plan.segments[0].metadata), keys); assert.deepEqual(plan.segments[0].metadata, createNarrationPlan(text).segments[0].metadata); });
test("natural, suspense, dramatic, emotional, and long pauses are generated", () => { const plan = createNarrationPlan(text, { mode: "dramatic" }); const kinds = plan.segments.map((x) => x.metadata.pause.kind); assert.ok(kinds.includes("suspense")); assert.ok(kinds.includes("emotional")); assert.ok(plan.segments.some((x) => x.metadata.pause.long)); });
test("names, locations, objects, revelations, and emotional words receive emphasis", () => { const all = createNarrationPlan(text).segments.flatMap((x) => x.metadata.emphasis); assert.ok(all.some((x) => x.type === "name")); assert.ok(all.some((x) => x.type === "location")); assert.ok(all.some((x) => x.type === "important_object")); assert.ok(all.some((x) => x.type === "revelation")); assert.ok(all.some((x) => x.type === "emotional_word")); });
test("breathing plan includes inhale, exhale, silent and optional breaths", () => { const long = "I love you! " + "word ".repeat(40) + "goodbye!"; const breaths = createNarrationPlan(long, { level: "scene", mode: "emotional" }).segments[0].metadata.breathing; assert.ok(breaths.some((x) => x.type === "silent_breath")); assert.ok(breaths.some((x) => x.type === "optional_breath")); assert.ok(breaths.some((x) => x.type === "exhale")); assert.ok(createNarrationPlan("A very long ordinary sentence " + "word ".repeat(20), { level: "scene" }).segments[0].metadata.breathing.some((x) => x.type === "inhale")); });
test("all narration modes and granularities are supported", () => { for (const mode of NARRATION_MODES) assert.equal(createNarrationPlan(text, { mode }).mode, mode); for (const level of ["sentence", "paragraph", "scene"]) assert.equal(createNarrationPlan(text, { level }).level, level); });
test("manual expression overrides survive while narrator identity remains locked", () => { const first = createNarrationPlan(text, { narratorVoiceId: "voice-narrator", speakers: [{ start: 0, end: 30, speakerId: "mara", voiceId: "voice-mara" }] }); const changed = applyNarrationOverride(first, first.segments[0].id, { metadata: { speechRate: .61 }, voiceAssignment: "manual-voice", speaker: { speakerId: "mara" } }); const next = createNarrationPlan(text, { previousPlan: changed }); assert.equal(next.segments[0].metadata.speechRate, .61); assert.ok(next.segments.every((segment) => segment.voiceAssignment === "voice-narrator")); assert.ok(next.segments.every((segment) => segment.speaker.speakerId === "narrator")); });
test("dynamic delivery detects core audiobook contexts without changing voice", () => { const sample = 'She smiled with joy. “I love you,” he whispered. Footsteps moved closer. “Attack!” the commander shouted! The battle exploded and soldiers attacked! Tears fell at goodbye.'; const plan = createNarrationPlan(sample, { narratorVoiceId: "one-professional-voice" }); const classes = new Set(plan.segments.flatMap((segment) => segment.classifications)); for (const type of ["narration", "dialogue", "happiness", "romance", "tension", "battle", "sadness"]) assert.ok(classes.has(type), type); assert.ok(plan.segments.some((segment) => segment.metadata.whisperLevel > .7)); assert.ok(plan.segments.some((segment) => segment.performance.shoutingLevel > .7)); assert.deepEqual(new Set(plan.segments.map((segment) => segment.voiceAssignment)), new Set(["one-professional-voice"])); });
test("report summarizes narration without mutating the plan", () => { const plan = createNarrationPlan(text); const before = structuredClone(plan); const report = generateNarrationReport(plan); assert.equal(report.sourcePreserved, true); assert.ok(report.segmentCount > 0); assert.ok(report.emphasisCount > 0); assert.deepEqual(plan, before); });
