import test from "node:test";
import assert from "node:assert/strict";
import { addChapter, approveChapter, archiveNovel, assertAdmin, createNovel, createReport, diagnostics, generateAudiobook, publishNovel, qualityControl, regenerateChapter, reorderChapters, restoreNovel, rollbackNovel } from "../src/lib/publishingStudio.js";
const admin={role:"admin"};
function ready(){let n=createNovel({title:"Book",author:"Author",description:"Description"});n=addChapter(n,{title:"One",audio:"one.mp3",voices:["voice"],assets:[],renderStatus:"completed"});return approveChapter(n,n.chapters[0].id)}
test("publishing runs QC, creates sequential immutable versions, and describes index updates",()=>{let n=ready();let first=publishNovel(n,admin);assert.equal(first.version.number,1);assert.equal(first.novel.status,"Published");assert.deepEqual(first.updates,["catalog","audiobook","metadata","search","cache","latest releases"]);let second=publishNovel(first.novel,admin);assert.equal(second.version.number,2);assert.equal(second.novel.versions.length,2)});
test("rollback restores a selected snapshot but retains version history",()=>{const one=publishNovel(ready(),admin).novel;const changed={...one,title:"Changed"};const two=publishNovel(changed,admin).novel;const rolled=rollbackNovel(two,1,admin);assert.equal(rolled.title,"Book");assert.equal(rolled.currentVersion,1);assert.equal(rolled.versions.length,2)});
test("regenerate preserves old render and invalidates approval",()=>{let n=ready();n={...n,chapters:n.chapters.map(c=>({...c,locked:false}))};const next=regenerateChapter(n,n.chapters[0].id,"two.mp3",admin);assert.equal(next.chapters[0].previousAudio,"one.mp3");assert.equal(next.chapters[0].audio,"two.mp3");assert.equal(next.chapters[0].approved,false)});
test("approval requires audio and locks approved chapter",()=>{const n=addChapter(createNovel({title:"B"}),{title:"One"});assert.throws(()=>approveChapter(n,n.chapters[0].id),/audio is required/);const ok=approveChapter({...n,chapters:n.chapters.map(c=>({...c,audio:"a.mp3"}))},n.chapters[0].id);assert.equal(ok.chapters[0].locked,true)});
test("quality control finds every supported publishing defect",()=>{let n=createNovel({title:""});n=addChapter(n,{title:"Same",assets:[{available:false}],renderStatus:"failed"});n=addChapter(n,{title:"Same",audio:"a",voices:["v"]});const codes=new Set(qualityControl(n).issues.map(i=>i.code));for(const code of ["audio_missing","asset_missing","voice_missing","render_failed","metadata_invalid","duplicate_chapter"])assert.ok(codes.has(code),code)});
test("security denies reader operations",async()=>{assert.throws(()=>assertAdmin({role:"reader"},"publish"),/Administrator/);assert.throws(()=>archiveNovel(ready(),{role:"reader"}),/Administrator/);assert.throws(()=>publishNovel(ready(),{role:"reader"}),/Administrator/);await assert.rejects(()=>generateAudiobook(ready(),{},{role:"reader"}),/Administrator/)});
test("production executes all stages and diagnostics and reports are available",async()=>{const seen=[];const handlers=Object.fromEntries(["Character Analysis","Voice Assignment","Narration","Production","Sound Design","Rendering","Mixing","Export"].map(name=>[name,async n=>{seen.push(name);return n}]));const result=await generateAudiobook(ready(),handlers,admin);assert.equal(result.job.status,"completed");assert.equal(seen.length,8);const report=createReport("production",result.job);const check=diagnostics({novels:[result.novel],jobs:[result.job],reports:[report]});assert.equal(check.healthy,true);assert.equal(check.reports,1)});
test("chapter ordering validates a complete unique sequence",()=>{let n=createNovel({title:"B"});n=addChapter(n,{title:"A"});n=addChapter(n,{title:"B"});const ids=n.chapters.map(c=>c.id);assert.deepEqual(reorderChapters(n,ids.reverse()).chapters.map(c=>c.order),[1,2]);assert.throws(()=>reorderChapters(n,[ids[0],ids[0]]),/exactly once/)});
test("archive and restore preserve previous workflow status",()=>{const n={...ready(),status:"Ready To Publish"};const archived=archiveNovel(n,admin);assert.equal(archived.status,"Archived");assert.equal(restoreNovel(archived).status,"Ready To Publish")});
