import test from "node:test";
import assert from "node:assert/strict";
import { applySoundDesignPlan, calculateSoundDesignScore, classifyAmbience, classifySfx, createSoundDesignPlan, generateSoundDesignDiff, generateSoundDesignReport, getSoundDesignWarnings, invalidateSoundDesignScenes, migrateSoundDesignPlan, revertSoundDesignPlan, shouldApplyCue, SOUND_DESIGN_MODES } from "../src/lib/soundDesignEngine.js";

const project = { id: "p1", novelId: "n1", chapterId: "c1", scenes: [
  { id: "s1", text: "At night rain struck the tavern. Heavy boots approached the door. The truth was revealed.", timeline: { start: 0, duration: 20 }, metadata: { location: "tavern", weather: "rain", timeOfDay: "night" } },
  { id: "s2", text: "The carriage rolled along the forest road. A sword crashed against the gate and everyone froze in shock.", timeline: { start: 20, duration: 20 }, metadata: {} },
], tracks: [{ id: "narrator", clips: [{ id: "voice1", sceneId: "s1", sourceText: "Heavy boots approached the door.", start: 0, duration: 5, clipType: "narrator", manuallyEdited: true }] }] };
const production = { productionPlanId: "prod1", projectId: "p1", novelId: "n1", chapterId: "c1", scenes: [{ sceneId: "s1", sceneType: "suspense", emotionalArc: "tense", intensity: .5, transitionOut: { type: "silence", length: 1 } }, { sceneId: "s2", sceneType: "travel", emotionalArc: "urgency", intensity: .7, transitionOut: { type: "hard cut", length: 0 } }] };
const assets = [{ id: "rain", type: "ambience", category: "rain", tags: ["rain"], reference: "/rain.wav" }, { id: "urgency", type: "music", tags: ["urgency"], reference: "/music.wav" }, { id: "boots", type: "sfx", category: "footsteps", tags: ["footsteps", "boots"], reference: "/boots.wav" }, { id: "door", type: "sfx", category: "doors", tags: ["doors", "door"], reference: "/door.wav" }];
const mixer = { mixerProjectId: "mix1", projectId: "p1", tracks: ["ambience", "music", "sound_effects", "narrator"].map((trackType) => ({ trackId: trackType, trackType, clips: trackType === "narrator" ? [{ clipId: "manual", sceneId: "s1", manuallyEdited: true, startTime: 0, duration: 5 }] : [] })) };

test("ambience and SFX classification are deterministic and source ordered", () => { assert.deepEqual(classifyAmbience(project.scenes[0].text), classifyAmbience(project.scenes[0].text)); assert.equal(classifyAmbience(project.scenes[0].text).category, "rain"); const cues = classifySfx(project.scenes[1].text); assert.deepEqual(cues, classifySfx(project.scenes[1].text)); assert.ok(cues.every((cue, index) => !index || cue.index >= cues[index - 1].index)); });
test("plan supplies the complete versioned schema and scene schema", () => { const plan = createSoundDesignPlan(production, project, { assets }); assert.ok(["soundDesignPlanId", "productionPlanId", "mixerProjectId", "projectId", "novelId", "chapterId", "version", "mode", "status", "scenePlans", "globalSettings", "assetRequirements", "warnings", "confidence", "createdAt", "updatedAt"].every((key) => key in plan)); assert.ok(["sceneId", "location", "environment", "weather", "timeOfDay", "ambienceLayers", "musicCues", "sfxCues", "silenceRegions", "transitionPlan", "dynamicRangePlan", "confidence", "manuallyLocked"].every((key) => key in plan.scenePlans[0])); assert.ok(plan.scenePlans[0].ambienceLayers.length <= 2); });
test("music is restrained and silence protects revelations and shocks", () => { const plan = createSoundDesignPlan(production, project, { assets }); assert.ok(plan.scenePlans.flatMap((s) => s.musicCues).length < plan.scenePlans.length); assert.match(plan.scenePlans[0].silenceRegions[0].reason, /revelation/i); assert.ok(plan.scenePlans[1].silenceRegions.some((r) => /shock/i.test(r.reason))); });
test("asset matching prefers exact tags and marks missing assets", () => { const plan = createSoundDesignPlan(production, project, { assets }); assert.equal(plan.scenePlans[0].ambienceLayers[0].assetReference.id, "rain"); assert.ok(plan.assetRequirements.length > 0); assert.ok(getSoundDesignWarnings(plan).some((warning) => warning.code === "missing-asset")); });
test("confidence thresholds enforce modes", () => { const medium = { confidence: { value: .6 } }; const high = { confidence: { value: .9 } }; assert.equal(shouldApplyCue(high, SOUND_DESIGN_MODES.MANUAL), false); assert.equal(shouldApplyCue(medium, SOUND_DESIGN_MODES.ASSISTED), true); assert.equal(shouldApplyCue(medium, SOUND_DESIGN_MODES.FULL_AUTO), false); assert.equal(shouldApplyCue(high, SOUND_DESIGN_MODES.FULL_AUTO), true); });
test("regeneration preserves selected assets and locked scenes", () => { const first = createSoundDesignPlan(production, project, { assets }); first.scenePlans[0].ambienceLayers[0].assetReference.userSelected = true; first.scenePlans[0].manuallyLocked = true; const second = createSoundDesignPlan(production, project, { assets, previousPlan: first }); assert.deepEqual(second.scenePlans[0], first.scenePlans[0]); });
test("application, diff, cue, scene and full revert are non-destructive", () => { const plan = createSoundDesignPlan(production, project, { assets, mode: SOUND_DESIGN_MODES.ASSISTED }); const applied = applySoundDesignPlan(mixer, plan); assert.equal(applied.tracks.find((t) => t.trackType === "narrator").clips[0].manuallyEdited, true); const diff = generateSoundDesignDiff(mixer, applied); assert.ok(diff.addedCues.length > 0); const cueId = diff.addedCues[0].cueId; assert.ok(revertSoundDesignPlan(applied, { cueId }).tracks.flatMap((t) => t.clips).length < applied.tracks.flatMap((t) => t.clips).length); assert.ok(revertSoundDesignPlan(applied, { sceneId: "s1" }).tracks.flatMap((t) => t.clips).every((c) => !c.soundDesignOverride || c.sceneId !== "s1")); assert.deepEqual(revertSoundDesignPlan(applied), mixer); });
test("density and masking warnings feed bounded scores and report", () => { const plan = createSoundDesignPlan(production, project, { assets }); plan.scenePlans[0].sfxCues.push(...Array.from({ length: 8 }, (_, i) => ({ cueId: `loud${i}`, category: "impacts", timingOffset: i / 10, volume: .9, intensity: .9, requiredAssetTags: [], missingAsset: false, confidence: { value: .8 } }))); const codes = getSoundDesignWarnings(plan).map((w) => w.code); assert.ok(codes.includes("excessive-cue-density")); assert.ok(codes.includes("speech-masking-risk")); const score = calculateSoundDesignScore(plan); assert.ok(score.overallScore >= 0 && score.overallScore <= 100); const report = generateSoundDesignReport(plan); assert.equal(report.sceneBySceneCuePlan.length, 2); assert.ok(Array.isArray(report.silenceSummary)); });
test("migration recovers malformed data and preserves locks", () => { assert.equal(migrateSoundDesignPlan("not json"), null); const migrated = migrateSoundDesignPlan({ version: 0, scenes: [{ id: "legacy", manuallyLocked: true }] }); assert.equal(migrated.version, 1); assert.equal(migrated.scenePlans[0].sceneId, "legacy"); assert.equal(migrated.scenePlans[0].manuallyLocked, true); });
test("only affected unlocked scenes invalidate", () => { const plan = createSoundDesignPlan(production, project, { assets }); plan.scenePlans[0].manuallyLocked = true; const changed = structuredClone(project); changed.scenes[1].text += " Changed."; const invalidated = invalidateSoundDesignScenes(plan, production, changed); assert.equal(invalidated.scenePlans[0].status, undefined); assert.equal(invalidated.scenePlans[1].status, "invalidated"); });
