import test from "node:test";
import assert from "node:assert/strict";
import { analyzeChapterVoice } from "../src/lib/voiceEngine/analyzer.js";
import { directChapterPerformance, hashDirectorContent, markOutdatedPlans } from "../src/lib/voiceDirector/director.js";
const seg=(text,type="narration",extra={})=>({id:crypto.randomUUID(),segmentIndex:extra.segmentIndex??0,segment_type:type,type,text,speaker_id:extra.speakerId|| (type==="narration"?"narrator":"hero"),speaker_name:extra.speakerName|| (type==="narration"?"Оповідач":"Hero"),voice_profile:extra.voiceProfile|| (type==="narration"?"narrator_neutral":"male_young_hero"),emotion:extra.emotion||"neutral",intensity:extra.intensity??0.3});
const cast=[{character_id:"hero",cast_slot:"young_male_hero_01",voice_profile:"male_young_hero",character_role:"protagonist"},{character_id:"old",cast_slot:"elderly_male_01",voice_profile:"male_elder",character_role:"supporting"},{character_id:"woman",cast_slot:"young_female_01",voice_profile:"female_young",character_role:"supporting"}];
function plan(segments){segments.forEach((s,i)=>{s.segmentIndex=i;s.segment_index=i}); return directChapterPerformance({chapterId:"00000000-0000-0000-0000-000000000001",novelId:1,segments,cast,characters:[]});}
test("neutral narration remains narrator and text/order unchanged",()=>{const s=[seg("A quiet road ended near the village.")]; const p=plan(s); assert.equal(p.scenes[0].sceneType,"neutral"); assert.equal(p.segmentSettings[0].castSlot,"narrator_neutral"); assert.equal(s[0].text,"A quiet road ended near the village."); assert.equal(p.segmentSettings[0].segmentIndex,0);});
test("battle and sword cues require combat evidence",()=>{const p=plan([seg("The sword rang as the battle began!", "dialogue", {speakerId:"hero",speakerName:"Hero",emotion:"determined",intensity:.8})]); assert.equal(p.scenes[0].sceneType,"battle"); assert.ok(p.segmentSettings[0].energy>.7); assert.ok(p.segmentSettings[0].soundCues.some(c=>c.type==="sword_clash")); const calm=plan([seg("He argued about dinner.","dialogue")]); assert.notEqual(calm.scenes[0].sceneType,"battle"); assert.equal(calm.segmentSettings[0].soundCues.filter(c=>c.type==="sword_clash").length,0);});
test("horror scene uses slower suspense",()=>{const p=plan([seg("У темному коридорі почувся тихий скрип.",{toString(){return "narration"}}.toString(),{emotion:"mysterious"})]); assert.equal(p.scenes[0].sceneType,"horror"); assert.ok(p.segmentSettings[0].rate<1); assert.ok(p.segmentSettings[0].pauseAfterMs>=700);});
test("romance requires textual evidence",()=>{assert.equal(plan([seg("Він і вона говорили тихо.","dialogue")]).scenes[0].sceneType!=="romance",true); assert.equal(plan([seg("Ніжний поцілунок змусив серце завмерти.")]).scenes[0].sceneType,"romance");});
test("system scene is mechanical",()=>{const p=plan([seg("Система: статус оновлено.","system",{speakerId:"system",voiceProfile:"system_neutral"})]); assert.equal(p.scenes[0].sceneType,"system_notification"); assert.equal(p.segmentSettings[0].deliveryStyle,"mechanical_neutral");});
test("scene boundary detection preserves order",()=>{const p=plan([seg("Quiet start."),seg("The sword struck in battle!", "dialogue", {speakerId:"hero"}),seg("The enemy attacked.")]); assert.deepEqual(p.segmentSettings.map(s=>s.segmentIndex),[0,1,2]); assert.ok(p.scenes.length>=1);});
test("emotion smoothing limits jumps",()=>{const p=plan([seg("calm", "dialogue", {intensity:.1}),seg("rage!!", "dialogue", {speakerId:"old",speakerName:"Old Man",voiceProfile:"male_elder",emotion:"angry",intensity:1})]); assert.ok(Math.abs(p.segmentSettings[1].intensity-p.segmentSettings[0].intensity)<=0.29);});
test("old man, hero, young woman profiles stay safe",()=>{const p=plan([seg("I will win!","dialogue",{speakerId:"hero",emotion:"determined"}),seg("Slow words.","dialogue",{speakerId:"old",speakerName:"Old Man",voiceProfile:"male_elder"}),seg("Calm words.","dialogue",{speakerId:"woman",speakerName:"Mira",voiceProfile:"female_young"})]); assert.ok(p.segmentSettings[0].energy>p.segmentSettings[2].energy); assert.ok(p.segmentSettings[1].rate<1); assert.ok(Math.abs(p.segmentSettings[2].pitch)<=0.35);});
test("pause planning ellipsis and speaker change",()=>{const p=plan([seg("Wait...","dialogue",{speakerId:"hero"}),seg("Yes.","dialogue",{speakerId:"old",speakerName:"Old Man"})]); assert.ok(p.segmentSettings[0].pauseAfterMs>=700); assert.ok(p.segmentSettings[1].pauseBeforeMs>=250);});
test("no excessive sound cues and rain only with evidence",()=>{const p=plan([seg("Rain fell. Rain on every stone. Rain again."),seg("No weather here.")]); assert.ok(p.statistics.soundCueCount<=2); assert.equal(p.segmentSettings[1].soundCues.some(c=>c.type==="rain"),false);});
test("manual overrides preserved and re-analysis marks outdated",()=>{const s=[seg("Rain fell.")]; const old=plan(s); old.segmentSettings[0].manuallyEdited=true; old.segmentSettings[0].rate=.77; const next=directChapterPerformance({chapterId:"c",novelId:1,segments:s,cast,previousPlan:old}); assert.equal(next.segmentSettings[0].rate,.77); const changed=[seg("Different text.")]; const marked=markOutdatedPlans([{contentHash:old.contentHash,status:"ready"}],changed); assert.equal(marked[0].status,"outdated"); assert.notEqual(hashDirectorContent(s),hashDirectorContent(changed));});
test("phase 1 analyzer still returns segments",()=>{const r=analyzeChapterVoice({chapterId:"c",novelId:1,content:"— Хто тут?\n\nСистема: рівень 1"}); assert.ok(r.segments.length>=2);});
