export const DIRECTOR_VERSION = "voice-director-local-v1";
export const sceneCatalog = {
  neutral:{baseRate:1,baseEnergy:0.45,baseIntensity:0.25,narratorStyle:"balanced",pauseMultiplier:1,ambienceProfile:"none",soundDensityLimit:1,description:"Default low-risk narration."},
  dialogue:{baseRate:1,baseEnergy:0.5,baseIntensity:0.35,narratorStyle:"conversational",pauseMultiplier:0.9,ambienceProfile:"quiet_room",soundDensityLimit:1,description:"Character-focused exchange."},
  exposition:{baseRate:0.96,baseEnergy:0.4,baseIntensity:0.25,narratorStyle:"clear_exposition",pauseMultiplier:1.05,ambienceProfile:"none",soundDensityLimit:0,description:"Informational passage."},
  mystery:{baseRate:0.92,baseEnergy:0.38,baseIntensity:0.45,narratorStyle:"measured_intrigue",pauseMultiplier:1.2,ambienceProfile:"quiet_room",soundDensityLimit:2,description:"Uncertain or secretive scene."},
  horror:{baseRate:0.88,baseEnergy:0.34,baseIntensity:0.55,narratorStyle:"slow_suspense",pauseMultiplier:1.35,ambienceProfile:"dungeon",soundDensityLimit:2,description:"Dark threatening suspense."},
  battle:{baseRate:1.12,baseEnergy:0.72,baseIntensity:0.72,narratorStyle:"urgent_action",pauseMultiplier:0.75,ambienceProfile:"none",soundDensityLimit:3,description:"Combat or large violent conflict."},
  chase:{baseRate:1.1,baseEnergy:0.68,baseIntensity:0.65,narratorStyle:"breathless_motion",pauseMultiplier:0.8,ambienceProfile:"none",soundDensityLimit:2,description:"Pursuit and escape."},
  danger:{baseRate:1.02,baseEnergy:0.58,baseIntensity:0.58,narratorStyle:"tense",pauseMultiplier:1,ambienceProfile:"none",soundDensityLimit:2,description:"Immediate threat without full combat."},
  romance:{baseRate:0.94,baseEnergy:0.42,baseIntensity:0.42,narratorStyle:"warm_subtle",pauseMultiplier:1.12,ambienceProfile:"quiet_room",soundDensityLimit:1,description:"Warm intimate emotion without exaggeration."},
  sadness:{baseRate:0.9,baseEnergy:0.32,baseIntensity:0.5,narratorStyle:"soft_grief",pauseMultiplier:1.25,ambienceProfile:"none",soundDensityLimit:1,description:"Loss or grief."},
  comedy:{baseRate:1.08,baseEnergy:0.55,baseIntensity:0.38,narratorStyle:"light_timing",pauseMultiplier:0.82,ambienceProfile:"none",soundDensityLimit:1,description:"Humor with non-cartoonish timing."},
  celebration:{baseRate:1.04,baseEnergy:0.65,baseIntensity:0.5,narratorStyle:"bright",pauseMultiplier:0.9,ambienceProfile:"village",soundDensityLimit:2,description:"Joy, applause, success."},
  discovery:{baseRate:0.98,baseEnergy:0.5,baseIntensity:0.45,narratorStyle:"wonder",pauseMultiplier:1.05,ambienceProfile:"none",soundDensityLimit:1,description:"Reveal or exploration."},
  training:{baseRate:1.04,baseEnergy:0.58,baseIntensity:0.46,narratorStyle:"focused",pauseMultiplier:0.9,ambienceProfile:"none",soundDensityLimit:1,description:"Practice or progression."},
  system_notification:{baseRate:1,baseEnergy:0.42,baseIntensity:0.35,narratorStyle:"mechanical_neutral",pauseMultiplier:0.75,ambienceProfile:"void",soundDensityLimit:0,description:"System/UI message."},
  dream:{baseRate:0.9,baseEnergy:0.35,baseIntensity:0.45,narratorStyle:"distant",pauseMultiplier:1.3,ambienceProfile:"dream",soundDensityLimit:1,description:"Dreamlike sequence."},
  flashback:{baseRate:0.94,baseEnergy:0.38,baseIntensity:0.42,narratorStyle:"remembered",pauseMultiplier:1.15,ambienceProfile:"void",soundDensityLimit:1,description:"Memory or past event."}
};
export const atmosphereProfiles = {
  none:{label:"None",volume:0,fadeInMs:0,fadeOutMs:0,loop:false,description:"No ambience."}, quiet_room:{label:"Quiet room",volume:0.08,fadeInMs:800,fadeOutMs:600,loop:true,description:"Subtle indoor tone."}, city:{label:"City",volume:0.14,fadeInMs:1000,fadeOutMs:800,loop:true,description:"Distant city."}, village:{label:"Village",volume:0.12,fadeInMs:1000,fadeOutMs:800,loop:true,description:"Village life."}, forest_day:{label:"Forest day",volume:0.14,fadeInMs:1200,fadeOutMs:900,loop:true,description:"Birds and leaves."}, forest_night:{label:"Forest night",volume:0.15,fadeInMs:1200,fadeOutMs:900,loop:true,description:"Night forest."}, rain_light:{label:"Light rain",volume:0.16,fadeInMs:1200,fadeOutMs:900,loop:true,description:"Soft rain."}, storm:{label:"Storm",volume:0.2,fadeInMs:1400,fadeOutMs:1000,loop:true,description:"Storm bed."}, cave:{label:"Cave",volume:0.14,fadeInMs:1000,fadeOutMs:900,loop:true,description:"Cave echo."}, battlefield:{label:"Battlefield",volume:0.18,fadeInMs:800,fadeOutMs:800,loop:true,description:"Distant battle."}, ocean:{label:"Ocean",volume:0.15,fadeInMs:1200,fadeOutMs:900,loop:true,description:"Waves."}, fire_camp:{label:"Camp fire",volume:0.12,fadeInMs:900,fadeOutMs:700,loop:true,description:"Small fire."}, palace:{label:"Palace",volume:0.08,fadeInMs:1000,fadeOutMs:800,loop:true,description:"Large hall."}, dungeon:{label:"Dungeon",volume:0.18,fadeInMs:1200,fadeOutMs:900,loop:true,description:"Dark corridor or dungeon."}, dream:{label:"Dream",volume:0.12,fadeInMs:1500,fadeOutMs:1200,loop:true,description:"Abstract dream."}, void:{label:"Void",volume:0.05,fadeInMs:500,fadeOutMs:500,loop:true,description:"Minimal system bed."}
};
