import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { markdownToText, splitIntoChapters, stripMarkup } from "../lib/admin";
import "../styles/AdminPanel.css";

function readFile(file){ return new Promise((resolve,reject)=>{ const reader = new FileReader(); reader.onload=()=>resolve(String(reader.result || "")); reader.onerror=()=>reject(reader.error); reader.readAsText(file); }); }
function normalizeImport(file, raw){ const name=file.name.toLowerCase(); if(name.endsWith(".md")||name.endsWith(".markdown")) return markdownToText(raw); if(name.endsWith(".epub")) return stripMarkup(raw); if(name.endsWith(".pdf")) return raw.replace(/[^\n\r\t -~а-яіїєґё]+/giu, " "); return raw; }

function AdminChapters(){ const navigate=useNavigate(); const [chapters,setChapters]=useState([]); const [query,setQuery]=useState(""); const [novel,setNovel]=useState("all"); const [selected,setSelected]=useState([]); const [dragId,setDragId]=useState(null); useEffect(()=>{ load(); },[]); async function load(){ const {data,error}=await supabase.from("chapters").select("id,novel_id,number,title,content,novels:chapters_novel_id_fkey(id,title)").order("novel_id").order("number"); if(error) alert(error.message); else setChapters(data||[]); } async function del(id){ if(!window.confirm("Видалити главу?")) return; const {error}=await supabase.from("chapters").delete().eq("id",id); if(error) alert(error.message); else load(); } async function bulkDelete(){ if(!selected.length || !window.confirm(`Видалити ${selected.length} глав?`)) return; const {error}=await supabase.from("chapters").delete().in("id", selected); if(error) alert(error.message); else { setSelected([]); load(); } } async function bulkUpload(files){ if(novel === "all") { alert("Оберіть одну новелу перед масовим імпортом."); return; } const rows=[]; let next=(chapters.filter(c=>String(c.novel_id)===novel).at(-1)?.number || 0) + 1; for (const file of files) { const raw=await readFile(file); const pieces=splitIntoChapters(normalizeImport(file, raw), file.name.replace(/\.[^.]+$/, "")); for (const piece of pieces) rows.push({ novel_id:Number(novel), number:next++, title:piece.title, content:piece.content }); } if(!rows.length) return; const {error}=await supabase.from("chapters").insert(rows); if(error) alert(error.message); else load(); } async function moveChapter(targetId){ if(!dragId || dragId===targetId) return; const current=filtered; const from=current.findIndex(c=>c.id===dragId); const to=current.findIndex(c=>c.id===targetId); const reordered=[...current]; const [item]=reordered.splice(from,1); reordered.splice(to,0,item); setChapters((all)=>all.map((c)=>{ const index=reordered.findIndex((r)=>r.id===c.id); return index>=0 ? { ...c, number:index+1 } : c; })); await Promise.all(reordered.map((c,index)=>supabase.from("chapters").update({ number:index+1 }).eq("id", c.id))); setDragId(null); load(); }
const novels=useMemo(()=>[...new Map(chapters.map(c=>[c.novel_id,c.novels?.title||`Новела ${c.novel_id}`])).entries()], [chapters]); const filtered=chapters.filter(c=>(novel==="all"||String(c.novel_id)===novel)&&(!query||[c.title,c.novels?.title].some(v=>String(v||"").toLowerCase().includes(query.toLowerCase())))); return <main className="admin-shell"><div className="admin-header"><div><h1>📖 Глави</h1><p className="admin-muted">Додавання, редагування, drag-and-drop порядок, масовий імпорт і видалення.</p></div><div className="admin-actions"><button onClick={()=>navigate("/admin/chapters/add")}>➕ Додати</button><button className="admin-secondary" onClick={()=>navigate("/admin")}>Назад</button></div></div><section className="admin-card admin-filters"><input placeholder="Пошук глав" value={query} onChange={(e)=>setQuery(e.target.value)}/><select value={novel} onChange={(e)=>setNovel(e.target.value)}><option value="all">Усі новели</option>{novels.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select><label className="admin-import-button">⬆️ Bulk upload<input type="file" multiple accept=".md,.markdown,.txt,.epub,.pdf,text/plain,text/markdown,application/epub+zip,application/pdf" onChange={(e)=>bulkUpload([...e.target.files])}/></label><button className="admin-danger" disabled={!selected.length} onClick={bulkDelete}>🗑 Bulk delete ({selected.length})</button></section><section className="admin-list">{filtered.map(c=><article draggable className="admin-card admin-chapter-row" onDragStart={()=>setDragId(c.id)} onDragOver={(e)=>e.preventDefault()} onDrop={()=>moveChapter(c.id)} style={{gridTemplateColumns:"auto 1fr"}} key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={(e)=>setSelected((ids)=>e.target.checked?[...ids,c.id]:ids.filter(id=>id!==c.id))}/><div><h3>☰ {c.title}</h3><p className="admin-muted">{c.novels?.title || "Новела"} • Глава №{c.number}</p><p>{(c.content||"").slice(0,180)}...</p><div className="admin-card-actions"><button onClick={()=>navigate(`/admin/chapters/edit/${c.id}`)}>✏️ Редагувати</button><button className="admin-danger" onClick={()=>del(c.id)}>🗑 Видалити</button></div></div></article>)}{!filtered.length && <p className="empty-state">Глав не знайдено.</p>}</section></main> }
export default AdminChapters;
