import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import "../styles/AdminPanel.css";

function Admin() {
  const navigate = useNavigate();
  const [novels, setNovels] = useState([]); const [chapters, setChapters] = useState(0); const [readers, setReaders] = useState(0); const [comments, setComments] = useState(0); const [activity, setActivity] = useState([]);
  useEffect(() => { async function loadStats() { const [{ data: novelRows = [] }, { count: chapterCount = 0 }, { count: readerCount = 0 }, { count: commentCount = 0 }] = await Promise.all([supabase.from("novels").select("id,title,status,image,chapters,created_at").order("created_at", { ascending:false }), supabase.from("chapters").select("id", { count: "exact", head: true }), supabase.from("profiles").select("id", { count:"exact", head:true }), supabase.from("comments").select("id", { count:"exact", head:true }).or("status.eq.pending,approved.eq.false")]); setNovels(novelRows || []); setChapters(chapterCount || 0); setReaders(readerCount || 0); setComments(commentCount || 0); setActivity((novelRows || []).slice(0,6).map((n)=>({ id:n.id, text:`${n.title} updated`, at:n.created_at }))); } loadStats(); }, []);
  const statCards = useMemo(() => [["Total novels", novels.length], ["Total chapters", chapters], ["Ongoing novels", novels.filter((n)=>n.status === "Ongoing").length], ["Completed novels", novels.filter((n)=>n.status === "Completed").length], ["Total readers", readers], ["Comments awaiting review", comments]], [novels, chapters, readers, comments]);
  const needsWork = novels.filter((n)=>!n.image || Number(n.chapters || 0) === 0).slice(0,8);
  return <main className="admin-shell"><div className="admin-header"><div><h1>⚙️ Admin Dashboard</h1><p className="admin-muted">Practical operations overview for the NovelVerse library.</p></div><button className="admin-secondary" onClick={() => navigate("/")}>На сайт</button></div><section className="admin-stats-row">{statCards.map(([label, value]) => <article className="admin-stat admin-stat--compact" key={label}><strong>{Number(value || 0).toLocaleString()}</strong><span>{label}</span></article>)}</section><section className="admin-grid"><article className="admin-stat"><h2>Recent admin activity</h2>{activity.length ? activity.map((item)=><p key={item.id} className="admin-muted">• {item.text} {item.at ? new Date(item.at).toLocaleString() : ""}</p>) : <p className="empty-state">No recent activity found.</p>}</article><article className="admin-stat"><h2>Needs attention</h2>{needsWork.length ? needsWork.map((n)=><p key={n.id}><button className="admin-link" onClick={()=>navigate(`/admin/novels/edit/${n.id}`)}>{n.title}</button> <span className="admin-muted">{!n.image ? "missing cover" : ""} {Number(n.chapters || 0) === 0 ? "missing chapters" : ""}</span></p>) : <p className="empty-state">All novels have covers and chapters.</p>}</article><article className="admin-stat"><h2>📚 Новели</h2><p className="admin-muted">Search, filters, pagination and bulk actions.</p><button onClick={() => navigate("/admin/novels")}>Open</button></article><article className="admin-stat"><h2>📖 Глави</h2><p className="admin-muted">Manual editing and batch imports.</p><button onClick={() => navigate("/admin/chapters")}>Open</button></article></section></main>;
}
export default Admin;
