import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { deleteVoiceCharacter, fetchVoiceCharacters, saveVoiceCharacter } from "../lib/voiceEngine/client";
import { voiceProfiles } from "../lib/voiceEngine/voiceProfiles";
const genders=["male","female","neutral","unknown"], ages=["child","teenager","young","adult","elderly","unknown"], roles=["protagonist","supporting","antagonist","narrator","system","creature","unknown"];
export default function AdminCharacters(){ const { novelId }=useParams(); const navigate=useNavigate(); const [novels,setNovels]=useState([]),[rows,setRows]=useState([]),[form,setForm]=useState({novel_id:novelId||"",canonical_name:"",display_name:"",aliases:"",gender:"unknown",age_group:"unknown",character_role:"supporting",voice_profile:"unknown_neutral",manually_verified:true,confidence:1}); const [notice,setNotice]=useState("");
useEffect(()=>{ supabase.from("novels").select("id,title").order("title").then(({data})=>setNovels(data||[]));},[]); useEffect(()=>{ if(form.novel_id) fetchVoiceCharacters(form.novel_id).then(setRows);},[form.novel_id]); function edit(c){ setForm({...c, aliases:(c.aliases||[]).join(", ")}); } async function save(e){ e.preventDefault(); try{ await saveVoiceCharacter(form); setNotice("Character saved."); setRows(await fetchVoiceCharacters(form.novel_id)); }catch(err){ setNotice(err.message); }} async function del(c){ if(!confirm("Delete this unused character? Existing segment references may become unresolved.")) return; await deleteVoiceCharacter(c.id); setRows(await fetchVoiceCharacters(form.novel_id)); } function merge(){ alert("Careful merge phase 1: edit the canonical character aliases, bulk assign segments in Voice Studio, then delete the duplicate after confirmation."); }
return <main className="admin-shell"><div className="admin-header"><h1>🎭 Voice Characters</h1><button onClick={()=>navigate("/admin")}>Back</button></div>{notice&&<p className="admin-toast">{notice}</p>}<form className="admin-form" onSubmit={save}><div className="admin-form-grid"><label>Novel<select required value={form.novel_id} onChange={e=>setForm({...form,novel_id:e.target.value})}><option value="">Choose</option>{novels.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>Canonical<input required value={form.canonical_name||""} onChange={e=>setForm({...form,canonical_name:e.target.value})}/></label><label>Display<input value={form.display_name||""} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label>Aliases<input value={form.aliases||""} onChange={e=>setForm({...form,aliases:e.target.value})}/></label><label>Gender<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}>{genders.map(x=><option key={x}>{x}</option>)}</select></label><label>Age<select value={form.age_group} onChange={e=>setForm({...form,age_group:e.target.value})}>{ages.map(x=><option key={x}>{x}</option>)}</select></label><label>Role<select value={form.character_role} onChange={e=>setForm({...form,character_role:e.target.value})}>{roles.map(x=><option key={x}>{x}</option>)}</select></label><label>Voice<select value={form.voice_profile} onChange={e=>setForm({...form,voice_profile:e.target.value})}>{voiceProfiles.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label><input type="checkbox" checked={!!form.manually_verified} onChange={e=>setForm({...form,manually_verified:e.target.checked})}/> Manually verified</label><label className="admin-full">Description<textarea value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="admin-actions"><button>Save character</button><button type="button" onClick={merge}>Merge guidance</button></div></form><section className="admin-grid">{rows.map(c=><article className="admin-stat" key={c.id}><h3>{c.display_name||c.canonical_name}</h3><p>{c.gender} · {c.age_group} · {c.character_role} · {c.voice_profile}</p><button onClick={()=>edit(c)}>Edit</button><button className="admin-danger" onClick={()=>del(c)}>Delete</button></article>)}</section></main> }
