import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { adminWrite, downloadFile, joinList, normalize, splitList, toCsv } from "../lib/adminContent";
import defaultCover from "../assets/default-cover.svg";
import "../styles/AdminPanel.css";

const PAGE_SIZE = 10;
const sorters = { newest:["created_at", false], updated:["created_at", false], title:["title", true], views:["views", false], rating:["rating", false] };
const hasNoCover = (n) => !n.image;
const hasNoChapters = (n) => Number(n.chapters || n.chapter_count || 0) === 0;

function AdminNovels() {
  const navigate = useNavigate();
  const [novels, setNovels] = useState([]); const [search, setSearch] = useState(""); const [genre, setGenre] = useState("all"); const [author, setAuthor] = useState("all"); const [status, setStatus] = useState("all"); const [missing, setMissing] = useState("all"); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1); const [selected, setSelected] = useState([]); const [toast, setToast] = useState("");
  useEffect(() => { loadNovels(); }, []);
  async function loadNovels() { const { data, error } = await supabase.from("novels").select("*").order("id", { ascending: false }); if (error) setToast(error.message); else setNovels(data || []); }
  const genres = useMemo(() => [...new Set(novels.flatMap((n) => splitList(n.genres)))].sort(), [novels]); const authors = useMemo(() => [...new Set(novels.map((n)=>n.author).filter(Boolean))].sort(), [novels]);
  const filtered = useMemo(() => novels.filter((n) => (!search || [n.title,n.author,n.slug,n.id].some((v)=>normalize(v).includes(normalize(search)))) && (genre === "all" || splitList(n.genres).includes(genre)) && (author === "all" || n.author === author) && (status === "all" || n.status === status) && (missing === "all" || (missing === "cover" ? hasNoCover(n) : hasNoChapters(n)))).sort((a,b)=>{ const [key, asc]=sorters[sort]; return String(a[key] ?? "").localeCompare(String(b[key] ?? ""), undefined, { numeric:true }) * (asc ? 1 : -1); }), [novels, search, genre, author, status, missing, sort]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  function toggleAll(on){ setSelected(on ? visible.map((n)=>n.id) : []); }
  async function mutateSelected(label, action){ if (!selected.length) return; try { await action(); setToast(label); setSelected([]); loadNovels(); } catch (e) { setToast(e.message); } }
  async function changeStatus(value){ mutateSelected(`Updated ${selected.length} novels.`, () => adminWrite(()=>supabase.from("novels").update({ status:value }).in("id", selected))); }
  async function editTaxonomy(mode, field){ const raw = window.prompt(`${mode} comma-separated ${field}`); if (!raw) return; const items = splitList(raw); const chosen = novels.filter((n)=>selected.includes(n.id)); await mutateSelected(`Updated ${field}.`, async()=>{ for (const novel of chosen) { const current = splitList(novel[field]); const next = mode === "Add" ? joinList([...current, ...items]) : joinList(current.filter((x)=>!items.includes(x))); await adminWrite(()=>supabase.from("novels").update({ [field]: next }).eq("id", novel.id)); } }); }
  async function deleteSelected(){ if (!selected.length || !window.confirm(`Delete ${selected.length} novels? WARNING: chapters and comments may remain linked unless database cascade rules delete them. This action does not intentionally delete chapters or comments.`)) return; mutateSelected("Deleted selected novels.", () => adminWrite(()=>supabase.from("novels").delete().in("id", selected))); }
  function exportSelected(type){ const rows = novels.filter((n)=>selected.includes(n.id)); if (type === "json") downloadFile("novels.json", JSON.stringify(rows, null, 2), "application/json"); else downloadFile("novels.csv", toCsv(rows), "text/csv"); }
  return <main className="admin-shell"><div className="admin-header"><div><h1>📚 Content Manager v2</h1><p className="admin-muted">Search, filters, bulk actions, drafts and exports.</p></div><div className="admin-actions"><button onClick={()=>navigate("/admin/novels/add")}>➕ Add</button><button className="admin-secondary" onClick={()=>navigate("/admin")}>Back</button></div></div>{toast && <p className="admin-toast">{toast}</p>}
    <section className="admin-card admin-filters"><input placeholder="Search title, author, slug or ID" value={search} onChange={(e)=>{setSearch(e.target.value); setPage(1);}} /><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">All statuses</option><option>Draft</option><option>Ongoing</option><option>Completed</option><option>Hiatus</option></select><select value={genre} onChange={(e)=>setGenre(e.target.value)}><option value="all">All genres</option>{genres.map((c)=><option key={c}>{c}</option>)}</select><select value={author} onChange={(e)=>setAuthor(e.target.value)}><option value="all">All authors</option>{authors.map((a)=><option key={a}>{a}</option>)}</select><select value={missing} onChange={(e)=>setMissing(e.target.value)}><option value="all">All assets</option><option value="cover">Missing cover</option><option value="chapters">Missing chapters</option></select><select value={sort} onChange={(e)=>setSort(e.target.value)}><option value="newest">Newest</option><option value="updated">Recently updated</option><option value="title">Title</option><option value="views">Views</option><option value="rating">Rating</option></select></section>
    <section className="admin-card admin-bulk"><label><input type="checkbox" checked={visible.length > 0 && visible.every((n)=>selected.includes(n.id))} onChange={(e)=>toggleAll(e.target.checked)} /> Select page</label><button onClick={()=>changeStatus("Ongoing")}>Publish</button><button className="admin-secondary" onClick={()=>changeStatus("Draft")}>Unpublish</button><button onClick={()=>changeStatus(window.prompt("Status", "Completed") || "Completed")}>Change status</button><button onClick={()=>editTaxonomy("Add", "genres")}>Add genres</button><button onClick={()=>editTaxonomy("Remove", "genres")}>Remove genres</button><button onClick={()=>editTaxonomy("Add", "tags")}>Add tags</button><button onClick={()=>exportSelected("json")}>Export JSON</button><button onClick={()=>exportSelected("csv")}>Export CSV</button><button className="admin-danger" onClick={deleteSelected}>Delete selected</button><span className="admin-muted">{selected.length} selected</span></section>
    <section className="admin-list">{visible.map((novel)=><article className="admin-card" key={novel.id}><input type="checkbox" checked={selected.includes(novel.id)} onChange={(e)=>setSelected((ids)=>e.target.checked?[...ids,novel.id]:ids.filter((id)=>id!==novel.id))}/><img src={novel.image || defaultCover} alt=""/><div><h2>{novel.title}</h2><p className="admin-muted">#{novel.id} • {novel.slug || "no-slug"} • {novel.author} • {novel.status} • ⭐ {novel.rating || 0} • 👁 {novel.views || 0}</p><p>{novel.description}</p><div className="admin-chip-list">{hasNoCover(novel)&&<span className="admin-chip">Missing cover</span>}{hasNoChapters(novel)&&<span className="admin-chip">Missing chapters</span>}{splitList(novel.genres).map((g)=><span className="admin-chip" key={g}>{g}</span>)}</div><div className="admin-card-actions"><button onClick={()=>navigate(`/novel/${novel.id}`)}>👁️ Preview</button><button onClick={()=>navigate(`/admin/novels/edit/${novel.id}`)}>✏️ Edit</button></div></div></article>)}{!visible.length && <p className="empty-state">No novels found.</p>}</section><div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Prev</button><span>Page {page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></main>;
}
export default AdminNovels;
