import { useMemo, useState } from "react";
import { applyNarrationOverride, createNarrationPlan, generateNarrationReport, NARRATION_MODES, NARRATION_LEVELS } from "../lib/narrationEngine.js";
import "../styles/NarrationStudio.css";
const SAMPLE = 'Mara entered the Tower of Ash. “The silver key was yours all along!” he shouted. *I remembered that night years ago.* Blood covered the sword. I love you... goodbye!';
export default function NarrationStudio() {
 const [text,setText]=useState(SAMPLE),[mode,setMode]=useState("audiobook"),[level,setLevel]=useState("sentence"),[plan,setPlan]=useState(()=>createNarrationPlan(SAMPLE)),[selected,setSelected]=useState(0); const segment=plan.segments[selected],report=useMemo(()=>generateNarrationReport(plan),[plan]);
 const generate=()=>{setPlan(old=>createNarrationPlan(text,{mode,level,previousPlan:old}));setSelected(0)}; const patch=(key,value)=>setPlan(old=>applyNarrationOverride(old,segment.id,{metadata:{[key]:Number(value)}}));
 const preview=()=>{if(!segment||!("speechSynthesis" in window))return;const u=new SpeechSynthesisUtterance(segment.source.text);u.rate=segment.metadata.speechRate;u.pitch=1+segment.metadata.pitchModifier;u.volume=Math.max(.15,Math.min(1,.45+segment.metadata.energy*.55-segment.metadata.whisperLevel*.25));const voice=window.speechSynthesis.getVoices()[0];if(voice)u.voice=voice;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)};
 return <main className="narration-studio"><header className="narration-hero"><div><span>DYNAMIC NARRATOR ENGINE · V4</span><h1>Narration Studio</h1><p>One narrator. Infinite expression. Tone, timbre and pacing adapt to every line while the voice identity stays locked.</p><div className="identity-lock">◉ Narrator identity locked <small>{plan.narrator.voiceId} · no speaker switching</small></div></div><b>1<small>consistent voice</small></b></header>
 <section className="narration-controls"><label>Performance mode<select value={mode} onChange={e=>setMode(e.target.value)}>{NARRATION_MODES.map(x=><option key={x}>{x}</option>)}</select></label><label>Analysis level<select value={level} onChange={e=>setLevel(e.target.value)}>{NARRATION_LEVELS.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={generate}>Generate narration</button><button onClick={preview}>▶ Preview selection</button></section>
 <section className="studio-grid"><article><h2>Chapter source</h2><textarea aria-label="Chapter source" value={text} onChange={e=>setText(e.target.value)}/><small>{text.length} characters · {plan.source.fingerprint}</small></article><article><h2>Emotion graph</h2><div className="graph">{plan.segments.map(x=><button key={x.id} onClick={()=>setSelected(x.index)} className={selected===x.index?"active":""}><i style={{height:`${x.metadata.emotionalWeight*100}%`}}/><b style={{height:`${x.metadata.energy*100}%`}}/></button>)}</div></article><article><h2>Pause graph</h2><div className="graph pauses">{plan.segments.map(x=><button key={x.id} title={x.metadata.pause.kind} onClick={()=>setSelected(x.index)}><i style={{height:`${Math.min(100,x.metadata.pause.afterMs/10)}%`}}/></button>)}</div></article></section>
 <section className="timeline"><h2>Narration timeline <small>{(plan.timeline.durationMs/1000).toFixed(1)} seconds</small></h2><div>{plan.segments.map(x=><button key={x.id} style={{flex:x.timeline.durationMs}} onClick={()=>setSelected(x.index)} className={selected===x.index?"active":""}><strong>{x.index+1}</strong><span>{x.classifications.join(" · ")}</span><small>{(x.timeline.durationMs/1000).toFixed(1)}s</small></button>)}</div></section>
 {segment&&<section className="studio-grid lower"><article><h2>Narration preview <button onClick={preview}>▶ Listen</button></h2><blockquote>{segment.source.text}</blockquote><div className="delivery-readout"><span><small>Tone</small>{segment.performance.tone}</span><span><small>Timbre</small>{segment.performance.timbre}</span><span><small>Shout</small>{Math.round(segment.performance.shoutingLevel*100)}%</span></div><div className="chips">{segment.classifications.map(x=><span key={x}>{x}</span>)}{segment.metadata.emphasis.map(x=><span className="emphasis" key={`${x.start}-${x.type}`}>{x.text} · {x.type}</span>)}</div><p>{segment.speaker.speakerName} · {segment.voiceAssignment}{segment.manualOverride?" · expression override locked":""}</p></article><article className="inspector"><h2>Real-time expression</h2>{[["speechRate",.6,1.35],["intensity",0,1],["pitchModifier",-.35,.35],["energy",0,1],["whisperLevel",0,1],["emotionalWeight",0,1]].map(([key,min,max])=><label key={key}><span>{key}</span><input type="range" min={min} max={max} step=".01" value={segment.metadata[key]} onChange={e=>patch(key,e.target.value)}/><output>{segment.metadata[key]}</output></label>)}<p>Pause: <b>{segment.metadata.pause.kind} · {segment.metadata.pause.beforeMs}/{segment.metadata.pause.afterMs} ms</b></p><p>Breathing: <b>{segment.metadata.breathing.map(x=>x.type).join(", ")||"none"}</b></p></article><article><h2>Narration report</h2><strong>{report.segmentCount} segments · {report.emphasisCount} emphasis cues · {report.breathCount} breaths</strong><p>{report.pauseSummary.dramatic} dramatic · {report.pauseSummary.suspense} suspense · {report.pauseSummary.emotional} emotional · {report.pauseSummary.long} long pauses</p><p className="safe">✓ One voice identity across every segment</p><p className="safe">✓ Original text and punctuation verified</p></article></section>}</main>;
}
