import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { addChapter, approveChapter, archiveNovel, createNovel, createPublishingStore, createReport, diagnostics, generateAudiobook, PRODUCTION_STAGES, PUBLISHING_STATUSES, publishNovel, qualityControl, regenerateChapter, restoreNovel, rollbackNovel, updateNovel } from "../lib/publishingStudio";
import "../styles/PublishingStudio.css";
const admin={role:"admin"};
function demo(){let n=createNovel({id:"demo",title:"The Glass Horizon",author:"Mira Vale",description:"A courier crosses a world shaped by living stories."});n=addChapter(n,{title:"The Unwritten Gate",content:"The gate opened at midnight.",audio:"/audio/demo.mp3",voices:["narrator"],renderStatus:"completed"});return {...n,status:"Ready For Review"};}
export default function PublishingStudio(){
 const navigate=useNavigate(),store=useMemo(()=>createPublishingStore(),[]);const [state,setState]=useState(()=>{const s=store.read();return s.novels.length?s:{...s,novels:[demo()]}}),[selectedId,setSelectedId]=useState(()=>state.novels[0]?.id),[tab,setTab]=useState("Dashboard"),[notice,setNotice]=useState("");
 const selected=state.novels.find(n=>n.id===selectedId)||state.novels[0];const save=s=>{setState(s);store.write(s)},replace=(novel,extras={})=>save({...state,...extras,novels:state.novels.map(n=>n.id===novel.id?novel:n)});const chapters=state.novels.reduce((a,n)=>a+n.chapters.length,0),failed=state.jobs.filter(j=>j.status==="failed").length;
 function create(){const title=window.prompt("Novel title");if(title){const n=createNovel({title});save({...state,novels:[...state.novels,n]});setSelectedId(n.id);setTab("Novels")}}function edit(){const title=window.prompt("Novel title",selected.title);if(title)replace(updateNovel(selected,{title}))}function remove(){if(window.confirm(`Delete “${selected.title}”?`)){const novels=state.novels.filter(n=>n.id!==selected.id);save({...state,novels});setSelectedId(novels[0]?.id)}}function add(){const title=window.prompt("Chapter title");if(title)replace(addChapter(selected,{title}))}
 async function generate(){setNotice("Production pipeline running…");const r=await generateAudiobook(selected,{},admin);replace(r.novel,{jobs:[r.job,...state.jobs],reports:[createReport("production",r.job),...state.reports]});setNotice("Audiobook generated and ready for review.")}
 function approve(c){try{replace(approveChapter(selected,c.id));setNotice(`${c.title} approved and locked.`)}catch(e){setNotice(e.message)}}function regenerate(c){try{replace(regenerateChapter(selected,c.id,`${c.audio||"render"}?v=${Date.now()}`,admin));setNotice("New render created; previous render retained.")}catch(e){setNotice(e.message)}}
 function publish(){try{const r=publishNovel(selected,admin);replace(r.novel,{publications:[r.version,...state.publications],reports:[createReport("publish",r),createReport("quality",r.quality),...state.reports],cacheRevision:state.cacheRevision+1,searchRevision:state.searchRevision+1});setNotice(`Version ${r.version.number} published. Catalog, audiobook, metadata, search, cache, and latest releases updated.`)}catch(e){setNotice(e.quality?`${e.message} ${e.quality.issues.map(i=>i.message).join(" ")}`:e.message)}}
 const stats=[["Novels",state.novels.length],["Chapters",chapters],["Audiobooks",state.novels.filter(n=>n.status==="Published").length],["Render time",`${state.jobs.length}s`],["Pipeline",state.jobs[0]?.status||"Idle"],["Failed jobs",failed]];
 return <main className="publishing-shell"><header className="publishing-header"><div><span className="eyebrow">NOVELVERSE ADMIN</span><h1>Publishing Studio</h1><p>Produce, review, version, and publish audiobooks from one protected workspace.</p></div><div className="actions"><button className="ghost" onClick={()=>navigate("/admin")}>Admin home</button><button onClick={create}>＋ Create novel</button></div></header><nav className="studio-tabs">{["Dashboard","Novels","Review","Reports","Admin tools"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<section className="studio-stats">{stats.map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong></article>)}</section>
 {tab==="Dashboard"&&<><section className="status-board">{PUBLISHING_STATUSES.map(status=><article key={status}><header><span>● {status}</span><b>{state.novels.filter(n=>n.status===status).length}</b></header>{state.novels.filter(n=>n.status===status).map(n=><button className="novel-tile" onClick={()=>{setSelectedId(n.id);setTab("Novels")}} key={n.id}><strong>{n.title}</strong><small>{n.chapters.length} chapters · v{n.currentVersion||"—"}</small></button>)}</article>)}</section><section className="panel latest"><h2>Latest publications</h2>{state.publications.length?state.publications.map(v=><p key={v.publishedAt}>Version {v.number}<time>{new Date(v.publishedAt).toLocaleString()}</time></p>):<p className="muted">No publications yet.</p>}</section></>}
 {tab==="Novels"&&selected&&<div className="workspace"><aside className="panel picker"><h2>Novels</h2>{state.novels.map(n=><button className={n.id===selected.id?"selected":""} onClick={()=>setSelectedId(n.id)} key={n.id}>{n.title}<small>{n.status}</small></button>)}</aside><section className="panel detail"><div className="panel-title"><div><span className="eyebrow">{selected.status}</span><h2>{selected.title}</h2><p>{selected.author||"Author not set"}</p></div><div className="actions"><button className="ghost" onClick={edit}>Edit</button><button className="danger" onClick={remove}>Delete</button></div></div><div className="actions"><button onClick={generate}>Generate Audiobook</button><button onClick={publish}>Publish</button><button className="ghost" onClick={()=>replace(selected.status==="Archived"?restoreNovel(selected):archiveNovel(selected,admin))}>{selected.status==="Archived"?"Restore":"Archive"}</button></div><div className="pipeline">{PRODUCTION_STAGES.map((s,i)=><div key={s}><span>{i+1}</span><small>{s}</small></div>)}</div><div className="panel-title"><h3>Chapters</h3><button onClick={add}>＋ Add chapter</button></div>{selected.chapters.map(c=><article className="chapter" key={c.id}><b>⋮⋮</b><div><strong>{c.order}. {c.title}</strong><small>{c.audio?"Audio ready":"Audio missing"} · {c.approved?"Approved":"Needs review"}</small></div><em>{c.locked?"Locked":"Unlocked"}</em><button className="ghost" onClick={()=>replace({...selected,chapters:selected.chapters.map(x=>x.id===c.id?{...x,locked:!x.locked}:x)})}>{c.locked?"Unlock":"Lock"}</button></article>)}</section></div>}
 {tab==="Review"&&selected&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">REVIEW STUDIO</span><h2>{selected.title}</h2></div><b className="badge">{qualityControl(selected).passed?"QC passed":`${qualityControl(selected).issues.length} QC issues`}</b></div>{selected.chapters.map(c=><article className="review" key={c.id}><h3>{c.order}. {c.title}</h3><p className="muted">Listen and compare before approval</p><div className="compare"><label>Previous render<audio controls src={c.previousAudio||""}/></label><label>Current render<audio controls src={c.audio||""}/></label></div><div className="actions"><button className="ghost" onClick={()=>regenerate(c)}>Regenerate paragraph</button><button className="ghost" onClick={()=>regenerate(c)}>Regenerate scene</button><button onClick={()=>approve(c)} disabled={c.approved}>{c.approved?"Approved ✓":"Mark approved"}</button></div></article>)}</section>}
 {tab==="Reports"&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">AUDIT TRAIL</span><h2>Reports</h2></div><button onClick={()=>save({...state,reports:[createReport("quality",qualityControl(selected)),...state.reports]})}>Run quality report</button></div><div className="report-grid">{["production","render","publish","quality"].map(type=><article key={type}><span>{type}</span><strong>{state.reports.filter(r=>r.type===type).length}</strong><small>reports</small></article>)}</div>{state.reports.map(r=><details key={r.id}><summary>{r.type} report <time>{new Date(r.createdAt).toLocaleString()}</time></summary><pre>{JSON.stringify(r.payload,null,2)}</pre></details>)}</section>}
 {tab==="Admin tools"&&<section className="panel"><span className="eyebrow">ADMINISTRATORS ONLY</span><h2>System tools</h2><div className="tools"><button onClick={generate}>Regenerate selected audiobook<small>Run the complete pipeline</small></button><button onClick={()=>selected?.chapters[0]&&regenerate(selected.chapters[0])}>Regenerate selected chapter<small>Preserve previous render</small></button><button onClick={()=>{save({...state,cacheRevision:state.cacheRevision+1});setNotice("Cache cleared.")}}>Clear cache<small>Revision {state.cacheRevision}</small></button><button onClick={()=>{const r=createReport("diagnostics",diagnostics(state));save({...state,reports:[r,...state.reports]});setNotice(r.payload.healthy?"Diagnostics passed.":"Failed jobs found.")}}>Diagnostics<small>Check jobs and storage</small></button><button onClick={()=>{save({...state,searchRevision:state.searchRevision+1});setNotice("Search index rebuilt.")}}>Rebuild search index<small>Revision {state.searchRevision}</small></button></div>{selected?.versions.map(v=><button className="ghost version" key={v.number} onClick={()=>replace(rollbackNovel(selected,v.number,admin))}>Rollback to Version {v.number}</button>)}</section>}</main>}
