import { useEffect, useMemo, useRef, useState } from "react";
import { applyVoicePreset, assignVoice, createVoiceReport, createVoiceStudioBackup, importVoicePreset, normalizeVoiceProfile, universalVoiceProfiles, validateVoiceStudio, versionVoiceProfile, voicePresets, voiceProviderAdapters } from "../lib/universalVoiceStudio";
import { defaultPiperVoiceId, getVoiceWorkerHealth, synthesizeVoiceWorkerAudio } from "../lib/voiceWorker";
import "../styles/VoiceStudio.css";

const storageKey = "novelverse.voiceStudio.v2";
const sampleCharacters = [{ id: "kael", display_name: "Kael Thorn", role: "Protagonist" }, { id: "mira", display_name: "Mira Vale", role: "Guide" }, { id: "warden", display_name: "The Warden", role: "Antagonist" }];
const previewSamples = { narrator: "Beyond the last ridge, the forgotten city waited in silence.", character: "We leave before sunrise. No one can know our path.", dialogue: "You came back, Mira said. I always do, Kael replied.", paragraph: "Rain traced silver lines across the window as the old house settled around them.", scene: "The gate exploded inward. Steel rang, footsteps thundered, and the torch went dark." };
function initialState() { try { const saved = JSON.parse(localStorage.getItem(storageKey)); if (saved?.version === 2) return saved; } catch { /* use defaults */ } const profiles = universalVoiceProfiles.slice(0, 6).map(normalizeVoiceProfile); return { version: 2, profiles, assignments: {}, narratorId: "narrator", history: [], favorites: [] }; }

export default function UniversalVoiceStudio() {
 const [studio, setStudio] = useState(initialState); const [tab, setTab] = useState("Narrator"); const [selectedId, setSelectedId] = useState(studio.narratorId || studio.profiles[0]?.id); const [characters] = useState(sampleCharacters); const [search, setSearch] = useState(""); const [checked, setChecked] = useState([]); const [previewType, setPreviewType] = useState("narrator"); const [previewText, setPreviewText] = useState(previewSamples.narrator); const [compare, setCompare] = useState(studio.profiles.slice(0, 2).map(p => p.id)); const [notice, setNotice] = useState("All voice changes are saved locally."); const [backup, setBackup] = useState("");
 const [workerStatus, setWorkerStatus] = useState({ loading: true, online: false, piperAvailable: false, voices: [] }); const previewUrl = useRef();
 const selected = studio.profiles.find(p => p.id === selectedId) || studio.profiles[0]; const issues = useMemo(() => validateVoiceStudio(studio), [studio]); const report = useMemo(() => createVoiceReport({ ...studio, characters }), [studio, characters]);
 function commit(next, message) { localStorage.setItem(storageKey, JSON.stringify(next)); setStudio(next); setNotice(message); }
 function edit(field, value) { const { profile, historyEntry } = versionVoiceProfile(selected, { [field]: ["rate", "pitch", "volume", "energy", "breathing"].includes(field) ? Number(value) : value }); commit({ ...studio, profiles: studio.profiles.map(p => p.id === selected.id ? profile : p), history: [historyEntry, ...studio.history].slice(0, 30) }, `${profile.name} saved as version ${profile.version}.`); }
 function applyPreset(name) { const profile = applyVoicePreset(selected, name); commit({ ...studio, profiles: studio.profiles.map(p => p.id === selected.id ? profile : p) }, `${name} preset applied.`); }
 function doAssign(ids = checked) { if (!ids.length) return; commit({ ...studio, assignments: assignVoice(studio.assignments, ids, selected.id) }, `Assigned ${selected.name} to ${ids.length} character(s).`); setChecked([]); }
 function speak(profile = selected) { if (!("speechSynthesis" in window)) return setNotice("Browser preview is unavailable on this device."); const utterance = new SpeechSynthesisUtterance(previewText); utterance.lang = profile.language; utterance.rate = profile.rate; utterance.pitch = profile.pitch; utterance.volume = profile.volume; speechSynthesis.cancel(); speechSynthesis.speak(utterance); setNotice(`Previewing ${profile.name} · ${previewType}.`); }
 function restore(entry) { const restored = { ...entry.snapshot, version: selected.version + 1 }; commit({ ...studio, profiles: studio.profiles.map(p => p.id === entry.profileId ? restored : p) }, `Restored ${restored.name} from version ${entry.version}.`); }
 useEffect(() => { getVoiceWorkerHealth().then(status => setWorkerStatus({ ...status, loading: false })).catch(() => setWorkerStatus({ loading: false, online: false, piperAvailable: false, voices: [] })); return () => previewUrl.current && URL.revokeObjectURL(previewUrl.current); }, []);
 async function previewPiper() { try { const result = await synthesizeVoiceWorkerAudio({ text: previewText, provider: "piper", voice: defaultPiperVoiceId, language: selected.language, preview: true }); if (previewUrl.current) URL.revokeObjectURL(previewUrl.current); previewUrl.current = URL.createObjectURL(result.blob); await new Audio(previewUrl.current).play(); setNotice("Local Piper preview is playing."); } catch (error) { setNotice(error.message || "Piper preview failed; browser preview remains available."); } }
 const filtered = characters.filter(c => c.display_name.toLowerCase().includes(search.toLowerCase()));
 return <main className="vs-shell">
  <header className="vs-hero"><div><span className="vs-eyebrow">PRODUCTION SUITE / VOICE</span><h1>Universal Voice Studio <b>v2</b></h1><p>Design a consistent cast. Compare performances. Render with confidence.</p></div><div className="vs-worker"><span>Worker {workerStatus.loading ? "checking…" : workerStatus.online ? "online" : "offline"}</span><span>Piper {workerStatus.piperAvailable ? "available" : "unavailable"}</span><span>Available voices: {workerStatus.voices.length}</span><button disabled={!workerStatus.piperAvailable} onClick={previewPiper}>Preview Piper</button></div><div className="vs-ready"><i />{issues.some(x=>x.severity==="error") ? `${issues.length} issues` : "Ready to render"}</div></header>
  <nav className="vs-tabs">{["Narrator","Characters","Voice Profiles","Voice Preview","Voice Comparison","Voice History","Voice Presets"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav>
  <div className="vs-notice">● {notice}</div>
  <section className="vs-layout"><aside className="vs-card vs-sidebar"><div className="vs-title"><h2>Voice Profiles</h2><button onClick={()=>{ const p=normalizeVoiceProfile({id:`voice_${Date.now()}`,name:"New Voice"}); commit({...studio,profiles:[...studio.profiles,p]},"Voice profile created."); setSelectedId(p.id); }}>＋</button></div>{studio.profiles.map(p=><button className={`vs-profile ${p.id===selectedId?"active":""}`} onClick={()=>setSelectedId(p.id)} key={p.id}><span>{p.name.slice(0,1)}</span><div><strong>{p.name}</strong><small>{p.provider} · {p.language.toUpperCase()} · v{p.version}</small></div>{studio.narratorId===p.id&&<em>NARRATOR</em>}</button>)}</aside>
   <div className="vs-main">
    <article className="vs-card"><div className="vs-title"><div><span className="vs-eyebrow">PROFILE EDITOR</span><h2>{selected?.name}</h2></div><button className="vs-preview-button" onClick={()=>speak()}>▶ Preview voice</button></div><div className="vs-form">{[["name","Display name"],["provider","Provider"],["voiceId","Voice ID"],["language","Language"]].map(([key,label])=><label key={key}>{label}{key==="provider"?<select value={selected[key]} onChange={e=>edit(key,e.target.value)}>{voiceProviderAdapters.map(x=><option key={x.id}>{x.id}</option>)}</select>:key==="language"?<select value={selected[key]} onChange={e=>edit(key,e.target.value)}>{["en","uk","ru","es","fr","de","it","pt","ja"].map(x=><option key={x}>{x}</option>)}</select>:<input value={selected[key]} onChange={e=>edit(key,e.target.value)}/>}</label>)}</div><div className="vs-sliders">{[["rate",.5,2],["pitch",.5,2],["volume",0,1],["energy",0,1],["breathing",0,1]].map(([key,min,max])=><label key={key}><span>{key}<b>{selected[key].toFixed(2)}</b></span><input type="range" min={min} max={max} step=".01" value={selected[key]} onChange={e=>edit(key,e.target.value)}/></label>)}</div><div className="vs-form compact">{[["pauseStyle","Pause style",["natural","dramatic","suspenseful","gentle","short"]],["narrationStyle","Narration style",["neutral","narrative","cinematic","intimate","epic","urgent","warm"]],["emotionPreset","Emotion preset",["neutral","calm","happy","sad","angry","afraid","determined","mysterious"]]].map(([key,label,items])=><label key={key}>{label}<select value={selected[key]} onChange={e=>edit(key,e.target.value)}>{items.map(x=><option key={x}>{x}</option>)}</select></label>)}</div></article>
    <article className="vs-card"><div className="vs-title"><h2>Character assignments</h2><button disabled={!checked.length} onClick={()=>doAssign()}>Bulk assign ({checked.length})</button></div><input className="vs-search" placeholder="Search characters…" value={search} onChange={e=>setSearch(e.target.value)}/>{filtered.map(c=>{const a=studio.assignments[c.id]; return <div className="vs-character" key={c.id}><input type="checkbox" checked={checked.includes(c.id)} onChange={()=>setChecked(x=>x.includes(c.id)?x.filter(id=>id!==c.id):[...x,c.id])}/><div><strong>{c.display_name}</strong><small>{c.role}</small></div><select value={a?.profileId||""} onChange={e=>commit({...studio,assignments:assignVoice(studio.assignments,[c.id],e.target.value,{locked:a?.locked})},"Assignment updated.")}><option value="">Missing voice</option>{studio.profiles.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button title="Duplicate voice" onClick={()=>{const p=normalizeVoiceProfile({...selected,id:`${selected.id}_copy_${Date.now()}`,name:`${selected.name} Copy`});commit({...studio,profiles:[...studio.profiles,p]},"Voice duplicated.");}}>⧉</button><button title="Lock assignment" className={a?.locked?"locked":""} onClick={()=>commit({...studio,assignments:{...studio.assignments,[c.id]:{...a,locked:!a?.locked}}},a?.locked?"Assignment unlocked.":"Assignment locked.")}>⌾</button><button onClick={()=>{setPreviewText(`${c.display_name}. ${previewSamples.character}`);speak(studio.profiles.find(p=>p.id===a?.profileId)||selected)}}>▶</button></div>})}</article>
    <article className="vs-card"><div className="vs-title"><h2>Preview & comparison</h2><span className="vs-count">Choose 2–4 voices</span></div><div className="vs-preview-types">{Object.keys(previewSamples).map(x=><button className={previewType===x?"active":""} onClick={()=>{setPreviewType(x);setPreviewText(previewSamples[x]);}} key={x}>{x}</button>)}</div><textarea value={previewText} onChange={e=>setPreviewText(e.target.value)}/><div className="vs-compare">{studio.profiles.map(p=><label key={p.id}><input type="checkbox" checked={compare.includes(p.id)} disabled={!compare.includes(p.id)&&compare.length>=4} onChange={()=>setCompare(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/>{p.name}<button onClick={()=>speak(p)}>▶</button><button className={studio.favorites.includes(p.id)?"favorite":""} onClick={()=>commit({...studio,favorites:studio.favorites.includes(p.id)?studio.favorites.filter(x=>x!==p.id):[...studio.favorites,p.id]},"Favorites updated.")}>★</button><button onClick={()=>commit({...studio,narratorId:p.id},`${p.name} marked as default narrator.`)}>Default</button></label>)}</div></article>
    <article className="vs-card"><h2>Presets</h2><div className="vs-presets">{Object.keys(voicePresets).map(name=><button onClick={()=>applyPreset(name)} key={name}><span>◈</span><strong>{name}</strong><small>Apply to {selected.name}</small></button>)}</div></article>
    <div className="vs-duo"><article className="vs-card"><h2>Validation & reports</h2><h3>Conflicts</h3>{issues.length?issues.map((x,i)=><p className={`vs-issue ${x.severity}`} key={i}>● {x.message}</p>):<p className="vs-good">✓ No blocking conflicts</p>}<h3>Cast report</h3><p>{report.assignedVoices.length} assigned · {report.unusedVoices.length} unused voices</p>{report.recommendations.map(x=><p className="vs-tip" key={x}>→ {x}</p>)}</article><article className="vs-card"><h2>History & persistence</h2><div className="vs-actions"><button onClick={()=>setBackup(JSON.stringify(createVoiceStudioBackup(studio),null,2))}>Create backup</button><button disabled={!backup} onClick={()=>{const next=importVoicePreset(backup);commit(next,"Backup restored and migrated to v2.")}}>Restore</button></div><textarea placeholder="Versioned backup JSON" value={backup} onChange={e=>setBackup(e.target.value)}/>{studio.history.slice(0,4).map((h,i)=><div className="vs-history" key={`${h.profileId}-${i}`}><span>{h.snapshot.name} · v{h.version}</span><button onClick={()=>restore(h)}>Restore previous</button></div>)}</article></div>
   </div></section>
 </main>;
}
