import { useEffect, useMemo, useRef, useState } from "react";
import { AnalysisQueue, ASSET_TYPES, applyAnalysis, canDeleteAsset, checksumBlob, createAssetMetadata, createLibraryReport, decodeAndAnalyze, editAsset, findDuplicates, matchCue, migrateAssetLibrary, replaceAsset, sanitizeFileName, validateImportFile } from "../lib/audioAssetLibrary";
import { createAssetStorage, MemoryAssetStorage } from "../lib/audioAssetStorage";

const storage = createAssetStorage();
const planCues = (plan) => (plan?.scenePlans || []).flatMap((scene) => [...(scene.ambienceLayers || []), ...(scene.musicCues || []), ...(scene.sfxCues || [])]);
const download = (value, name) => { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };

export default function AssetLibrary({ soundPlan, onSoundPlanChange }) {
  const [open, setOpen] = useState(false); const [library, setLibrary] = useState(() => storage.loadLibrary()); const [selected, setSelected] = useState([]); const [query, setQuery] = useState(""); const [type, setType] = useState(""); const [flag, setFlag] = useState(""); const [message, setMessage] = useState(storage instanceof MemoryAssetStorage ? "IndexedDB unavailable: binary files persist only for this session." : "Library ready."); const [progress, setProgress] = useState({}); const [matches, setMatches] = useState({}); const [preview, setPreview] = useState({ assetId: "", time: 0, volume: 1, loop: false });
  const filesRef = useRef(); const folderRef = useRef(); const metadataRef = useRef(); const replaceRef = useRef(); const queueRef = useRef(); const playerRef = useRef({}); const cues = useMemo(() => planCues(soundPlan), [soundPlan]);
  const visible = useMemo(() => library.assets.filter((asset) => (!query || `${asset.displayName} ${asset.tags.join(" ")} ${asset.moods.join(" ")} ${asset.environments.join(" ")}`.toLowerCase().includes(query.toLowerCase())) && (!type || asset.assetType === type) && (!flag || (flag === "favorite" ? asset.favorite : flag === "unused" ? !asset.usage?.usageCount : asset[flag]))), [library, query, type, flag]);
  useEffect(() => () => { playerRef.current.audio?.pause(); if (playerRef.current.url) URL.revokeObjectURL(playerRef.current.url); }, []);
  function persist(next) { const saved = storage.saveLibrary({ ...next, tags: [...new Set(next.assets.flatMap((asset) => asset.tags))] }); setLibrary(saved); }
  function patch(assetId, values) { persist({ ...library, assets: library.assets.map((asset) => asset.assetId === assetId ? editAsset(asset, values) : asset) }); }
  async function importFiles(list) { const imported = []; for (const file of [...list]) try { const info = validateImportFile(file); const checksum = await checksumBlob(file); const draft = createAssetMetadata({ fileName: info.name, mimeType: file.type, sizeBytes: file.size, checksum }); const duplicate = findDuplicates([...library.assets, ...imported], draft).find((x) => x.exact); if (duplicate && !window.confirm(`${info.name} duplicates ${duplicate.asset.displayName}. Keep both?`)) continue; imported.push({ ...draft, objectReference: await storage.putBlob(draft.assetId, file) }); } catch (error) { setMessage(`${sanitizeFileName(file.name)}: ${error.message}`); } if (imported.length) { persist({ ...library, assets: [...library.assets, ...imported] }); setSelected(imported.map((x) => x.assetId)); setMessage(`Imported ${imported.length} file(s). Format support is confirmed only after browser decoding.`); } }
  async function analyze(ids = selected) { const assets = library.assets.filter((x) => ids.includes(x.assetId)); const Context = window.AudioContext || window.webkitAudioContext; if (!assets.length) return; if (!Context) { setMessage("Web Audio API unavailable."); return; } const context = new Context(); const queue = new AnalysisQueue({ concurrency: 2, onProgress: setProgress, analyze: async (asset) => applyAnalysis(asset, await decodeAndAnalyze(await storage.getBlob(asset.objectReference), context), { collectionName: library.collections.find((x) => x.collectionId === asset.collectionId)?.name }) }); queueRef.current = queue; const results = await queue.run(assets); await context.close(); const indexed = new Map(results.map((x) => [x.item.assetId, x])); persist({ ...library, assets: library.assets.map((asset) => { const result = indexed.get(asset.assetId); return !result ? asset : result.status === "complete" ? result.value : { ...asset, invalid: result.status === "failed", analysisStatus: result.status, analysisError: result.error?.message || "Analysis cancelled." }; }) }); setMessage(queue.cancelled ? "Analysis cancelled; unfinished items may be resumed." : "Analysis complete."); }
  function stop() { playerRef.current.audio?.pause(); if (playerRef.current.url) URL.revokeObjectURL(playerRef.current.url); playerRef.current = {}; setPreview((x) => ({ ...x, assetId: "", time: 0 })); }
  async function play(asset) { try { stop(); const url = URL.createObjectURL(await storage.getBlob(asset.objectReference)); const audio = new Audio(url); audio.volume = preview.volume; audio.loop = preview.loop; audio.ontimeupdate = () => setPreview((x) => ({ ...x, time: audio.currentTime })); playerRef.current = { audio, url }; await audio.play(); setPreview((x) => ({ ...x, assetId: asset.assetId })); } catch (error) { patch(asset.assetId, { missing: true }); setMessage(`Preview failed: ${error.message}`); } }
  function remove(asset) { const check = canDeleteAsset(asset); if (!check.allowed && !window.confirm(check.warning)) return; if (!window.confirm(`Remove ${asset.displayName}?`)) return; storage.deleteBlob(asset.objectReference).catch(() => {}); persist({ ...library, assets: library.assets.filter((x) => x.assetId !== asset.assetId) }); }
  async function replace(event) { const file = event.target.files?.[0], asset = library.assets.find((x) => x.assetId === selected[0]); if (!file || !asset) return; try { const info = validateImportFile(file), checksum = await checksumBlob(file), objectReference = await storage.putBlob(asset.assetId, file); persist({ ...library, assets: library.assets.map((x) => x.assetId === asset.assetId ? replaceAsset(x, { fileName: info.name, mimeType: file.type, sizeBytes: file.size, checksum, objectReference }) : x) }); setMessage("Replacement preserved the assetId, references, and manual edits; reanalysis is pending."); } catch (error) { setMessage(error.message); } }
  function addCollection() { const name = window.prompt("Collection name"); if (name) persist({ ...library, collections: [...library.collections, { collectionId: `collection_${Date.now()}`, name: name.trim() }] }); }
  function removeCollection(item) { if (window.confirm(`Remove ${item.name} without deleting its assets?`)) persist({ ...library, collections: library.collections.filter((x) => x.collectionId !== item.collectionId), assets: library.assets.map((x) => x.collectionId === item.collectionId ? { ...x, collectionId: "" } : x) }); }
  function buildMatches() { setMatches(Object.fromEntries(cues.filter((cue) => !cue.assetSelection?.locked).map((cue) => [cue.cueId, matchCue(cue, library.assets, { recentAssetIds: cues.map((x) => x.assetSelection?.assetId).filter(Boolean).slice(-4) }).slice(0, 3)]))); setMessage("Matched unresolved cues; locked decisions were preserved."); }
  function applyMatch(cue, candidate) { const update = (item) => item.cueId === cue.cueId ? { ...item, assetReference: { id: candidate.asset.assetId, userSelected: true }, assetSelection: { assetId: candidate.asset.assetId, locked: true, automatic: false, score: candidate.score }, missingAsset: false } : item; onSoundPlanChange?.({ ...soundPlan, scenePlans: soundPlan.scenePlans.map((scene) => ({ ...scene, ambienceLayers: scene.ambienceLayers.map(update), musicCues: scene.musicCues.map(update), sfxCues: scene.sfxCues.map(update) })) }); }
  function clearAuto() { const clear = (items) => items.map((cue) => cue.assetSelection?.automatic && !cue.assetSelection.locked ? { ...cue, assetSelection: null, assetReference: null, missingAsset: true } : cue); onSoundPlanChange?.({ ...soundPlan, scenePlans: soundPlan.scenePlans.map((scene) => ({ ...scene, ambienceLayers: clear(scene.ambienceLayers), musicCues: clear(scene.musicCues), sfxCues: clear(scene.sfxCues) })) }); }
  async function importMetadata(event) { try { persist(migrateAssetLibrary(await event.target.files[0].text())); setMessage("Metadata imported; binary references are verified on use."); } catch { setMessage("Malformed metadata recovered safely."); } }
  return <section className="studio-panel asset-library"><div className="asset-heading"><div><p className="eyebrow">AI Asset Matching &amp; Library Engine v1</p><h2>Local audio asset library</h2></div><button onClick={() => setOpen(!open)}>{open ? "Close Asset Library" : "Open Asset Library"}</button></div>{open && <><p className="asset-message">{message}</p><div className="asset-actions"><button onClick={() => filesRef.current.click()}>Import Audio Files</button><button onClick={() => folderRef.current.click()}>Import Folder</button><button disabled={selected.length !== 1} onClick={() => replaceRef.current.click()}>Replace Asset</button><button disabled={!selected.length} onClick={() => analyze()}>Analyze Selected</button><button onClick={() => analyze(library.assets.map((x) => x.assetId))}>Analyze All</button><button onClick={() => queueRef.current?.cancel()}>Cancel Analysis</button><button onClick={buildMatches}>Match Missing Cues</button><button onClick={clearAuto}>Clear Automatic Matches</button><button onClick={() => download({ ...library, report: createLibraryReport(library, cues) }, `asset-library-${library.libraryId}.json`)}>Export Library Metadata</button><button onClick={() => metadataRef.current.click()}>Import Library Metadata</button></div>
  <input ref={filesRef} hidden multiple type="file" accept=".wav,.mp3,.m4a,.ogg,.flac,audio/*" onChange={(e) => importFiles(e.target.files)} /><input ref={folderRef} hidden multiple type="file" accept="audio/*" webkitdirectory="" onChange={(e) => importFiles(e.target.files)} /><input ref={replaceRef} hidden type="file" accept="audio/*" onChange={replace} /><input ref={metadataRef} hidden type="file" accept="application/json" onChange={importMetadata} />{progress.total > 0 && <p><progress max="1" value={progress.progress || 0} /> {progress.completed}/{progress.total}</p>}
  <div className="asset-filters"><input placeholder="Search assets, tags, moods" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={type} onChange={(e) => setType(e.target.value)}><option value="">All types</option>{ASSET_TYPES.map((x) => <option key={x}>{x}</option>)}</select><select value={flag} onChange={(e) => setFlag(e.target.value)}><option value="">All assets</option><option value="favorite">Favorites</option><option value="unused">Unmatched / unused</option><option value="loopCandidate">Loop candidates</option><option value="missing">Missing</option><option value="invalid">Invalid</option></select><button onClick={addCollection}>Create collection</button></div><div className="collection-list">{library.collections.map((item) => <span key={item.collectionId}>{item.name}<button onClick={() => { const name = window.prompt("Rename collection", item.name); if (name) persist({ ...library, collections: library.collections.map((x) => x === item ? { ...x, name } : x) }); }}>Rename</button><button onClick={() => removeCollection(item)}>Remove</button></span>)}<span>★ Favorites</span><span>Recently imported</span></div>
  <div className="asset-table">{visible.map((asset) => <article className={selected.includes(asset.assetId) ? "selected" : ""} key={asset.assetId}><input type="checkbox" checked={selected.includes(asset.assetId)} onChange={() => setSelected((x) => x.includes(asset.assetId) ? x.filter((id) => id !== asset.assetId) : [...x, asset.assetId])} /><div className="asset-waveform">{(asset.waveformSummary.length ? asset.waveformSummary : Array(24).fill(.08)).map((value, index) => <i key={index} style={{ height: `${Math.max(3, value * 38)}px` }} />)}</div><label>Name<input value={asset.displayName} onChange={(e) => patch(asset.assetId, { displayName: e.target.value })} /></label><label>Type<select value={asset.assetType} onChange={(e) => patch(asset.assetId, { assetType: e.target.value })}>{ASSET_TYPES.map((x) => <option key={x}>{x}</option>)}</select></label><label>Tags<input value={asset.tags.join(", ")} onChange={(e) => patch(asset.assetId, { tags: e.target.value.split(",") })} /></label><label>Mood<input value={asset.moods.join(", ")} onChange={(e) => patch(asset.assetId, { moods: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) })} /></label><label>Environment<input value={asset.environments.join(", ")} onChange={(e) => patch(asset.assetId, { environments: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) })} /></label><label>Intensity<select value={asset.intensity} onChange={(e) => patch(asset.assetId, { intensity: e.target.value })}><option>low</option><option>medium</option><option>high</option></select></label><label>Collection<select value={asset.collectionId} onChange={(e) => patch(asset.assetId, { collectionId: e.target.value })}><option value="">None</option>{library.collections.map((x) => <option key={x.collectionId} value={x.collectionId}>{x.name}</option>)}</select></label><label><input type="checkbox" checked={asset.favorite} onChange={(e) => patch(asset.assetId, { favorite: e.target.checked })} /> Favorite</label><label><input type="checkbox" checked={asset.loopCandidate} onChange={(e) => patch(asset.assetId, { loopCandidate: e.target.checked })} /> Loop</label><small>{asset.duration.toFixed(2)}s · {asset.sampleRate || "?"} Hz · {asset.channelCount || "?"} ch · {asset.analysisStatus}{asset.tagSuggestions[0] && ` · suggestion ${asset.tagSuggestions[0].tag} ${Math.round(asset.tagSuggestions[0].confidence * 100)}% (${asset.tagSuggestions[0].reason})`}</small><div><button onClick={() => play(asset)}>Play</button><button onClick={() => playerRef.current.audio?.pause()}>Pause</button><button onClick={stop}>Stop</button><button onClick={() => analyze([asset.assetId])}>Analyze Asset</button><button onClick={() => remove(asset)}>Remove Asset</button></div></article>)}</div>
  {preview.assetId && <div className="asset-preview"><label>Seek <input type="range" min="0" max={library.assets.find((x) => x.assetId === preview.assetId)?.duration || 1} step=".1" value={preview.time} onChange={(e) => { const time = Number(e.target.value); playerRef.current.audio.currentTime = time; setPreview((x) => ({ ...x, time })); }} /></label><label>Volume <input type="range" min="0" max="1" step=".05" value={preview.volume} onChange={(e) => { const volume = Number(e.target.value); playerRef.current.audio.volume = volume; setPreview((x) => ({ ...x, volume })); }} /></label><label><input type="checkbox" checked={preview.loop} onChange={(e) => { playerRef.current.audio.loop = e.target.checked; setPreview((x) => ({ ...x, loop: e.target.checked })); }} /> Loop</label></div>}
  {!!cues.length && <div className="cue-matches"><h3>Cue matching</h3>{cues.map((cue) => <article key={cue.cueId}><strong>{cue.category || cue.type || "Cue"}</strong> · Requirement: {(cue.requiredAssetTags || []).join(", ") || "category"} · Current: {cue.assetSelection?.assetId || cue.assetReference?.id || "unresolved"} {cue.assetSelection?.locked && "🔒"}{(matches[cue.cueId] || []).map((candidate) => <div key={candidate.asset.assetId}><b>{candidate.asset.displayName}</b> {Math.round(candidate.score.overallScore * 100)}% {candidate.score.confidence}<small>{candidate.score.reasons.join(" ")}</small><button onClick={() => play(candidate.asset)}>Preview</button><button onClick={() => applyMatch(cue, candidate)}>Apply &amp; lock</button><button onClick={() => setMatches((x) => ({ ...x, [cue.cueId]: matchCue({ ...cue, requiredAssetTags: candidate.asset.tags }, library.assets).slice(0, 3) }))}>Find similar</button></div>)}</article>)}</div>}<pre className="library-report">{JSON.stringify(createLibraryReport(library, cues), null, 2)}</pre></>}</section>;
}
