import { useCallback, useEffect, useRef, useState } from "react";
import { AGE_RATINGS, BOOK_STATUSES, LANGUAGES, TRANSLATION_STATUSES, createBook, deleteManagedBook, duplicateChapter, loadManagedBooks, reorderChapters, saveManagedBook, uploadBookAsset, validateBook } from "../lib/bookManagement";
import { isSupabaseConfigured } from "../lib/supabase";

const list = (value) => value.split(",").map((item) => item.trim()).filter(Boolean);
const chapterDraftKey = (bookId, chapterId) => `novelverse.chapter-draft.${bookId}.${chapterId}`;

export default function BookManagement({ onBooksChange }) {
  const [books, setBooks] = useState([]), [selectedId, setSelectedId] = useState(""), [tab, setTab] = useState("Metadata"), [chapterId, setChapterId] = useState("");
  const [notice, setNotice] = useState(""), [errors, setErrors] = useState({}), [saving, setSaving] = useState(false), [query, setQuery] = useState("");
  const timer = useRef();
  const selected = books.find((book) => book.id === selectedId);
  const chapter = selected?.chapters.find((item) => item.id === chapterId);
  const update = (patch) => setBooks((items) => items.map((book) => book.id === selectedId ? { ...book, ...patch } : book));
  const updateChapter = (patch) => update({ chapters: selected.chapters.map((item) => item.id === chapterId ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item) });
  const flash = useCallback((message) => { setNotice(message); window.clearTimeout(timer.current); timer.current = window.setTimeout(() => setNotice(""), 2800); }, []);

  useEffect(() => { loadManagedBooks().then((items) => { setBooks(items); setSelectedId(items[0]?.id || ""); onBooksChange?.(items); }).catch((error) => flash(error.message)); return () => window.clearTimeout(timer.current); }, [flash, onBooksChange]);
  useEffect(() => { if (!chapter) return; const id = window.setTimeout(() => { localStorage.setItem(chapterDraftKey(selectedId, chapter.id), JSON.stringify(chapter)); flash("Chapter autosaved"); }, 900); return () => window.clearTimeout(id); }, [chapter, flash, selectedId]);

  const persist = async () => { const found = validateBook(selected); setErrors(found); if (Object.keys(found).length) return; setSaving(true); try { await saveManagedBook(selected, books); onBooksChange?.(books); flash("All changes saved"); } catch (error) { flash(error.message); } finally { setSaving(false); } };
  const add = () => { const book = createBook(); setBooks((items) => [book, ...items]); setSelectedId(book.id); setTab("Metadata"); flash("New draft created"); };
  const remove = async () => { if (!confirm(`Delete “${selected.title}” and all of its chapters?`)) return; const remaining = books.filter((book) => book.id !== selectedId); await deleteManagedBook(selectedId, remaining); setBooks(remaining); setSelectedId(remaining[0]?.id || ""); onBooksChange?.(remaining); };
  const asset = async (kind, file) => { if (!file) return; try { const url = await uploadBookAsset(selected.id, kind, file); update({ [`${kind}Url`]: url }); flash(`${kind === "cover" ? "Cover" : "Banner"} uploaded`); } catch (error) { flash(error.message); } };
  const addChapter = () => { const item = { id: crypto.randomUUID(), title: `Chapter ${selected.chapters.length + 1}`, content: "<p>Start writing…</p>", audioStatus: "Missing", audioUrl: "", updatedAt: new Date().toISOString() }; update({ chapters: [...selected.chapters, item] }); setChapterId(item.id); };
  const audio = (id, action) => update({ chapters: selected.chapters.map((item) => item.id === id ? { ...item, audioStatus: action === "delete" ? "Missing" : "Ready", audioUrl: action === "delete" ? "" : item.audioUrl } : item) });
  const shown = books.filter((book) => `${book.title} ${book.author}`.toLowerCase().includes(query.toLowerCase()));

  return <section className="book-cms">
    {notice && <div className="cms-toast" role="status">✓ {notice}</div>}
    <div className="cms-toolbar"><div><h2>Book library</h2><p>{books.length} projects · {isSupabaseConfigured ? "Supabase connected" : "Local workspace"}</p></div><label className="cms-search">⌕<input aria-label="Search books" placeholder="Search title or author" value={query} onChange={(e) => setQuery(e.target.value)} /></label><button onClick={add}>＋ Create book</button></div>
    <div className="cms-layout"><aside className="cms-books">{shown.map((book) => <button key={book.id} className={book.id === selectedId ? "selected" : ""} onClick={() => { setSelectedId(book.id); setChapterId(""); }}><span className="cms-cover" style={book.coverUrl ? { backgroundImage: `url(${book.coverUrl})` } : {}}>{!book.coverUrl && book.title.slice(0, 2).toUpperCase()}</span><span><b>{book.title}</b><small>{book.author || "Author not set"}</small><em>{book.status}</em></span></button>)}</aside>
    {selected ? <main className="cms-editor"><header className="cms-editor-head"><div><span className="cms-eyebrow">CONTENT MANAGEMENT / {selected.status.toUpperCase()}</span><h2>{selected.title}</h2><p>{selected.chapters.length} chapters · {selected.language} · {selected.ageRating}</p></div><div><button className="cms-danger" onClick={remove}>Delete</button><button onClick={persist} disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></div></header>
      <nav className="cms-tabs">{["Metadata", "Chapters", "Audio", "Languages", "Publishing"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
      {tab === "Metadata" && <div className="cms-form"><div className="asset-upload cover-upload" style={selected.coverUrl ? { backgroundImage: `url(${selected.coverUrl})` } : {}}><b>Cover art</b><span>Recommended 1600 × 2400</span><label>Upload cover<input type="file" accept="image/*" onChange={(e) => asset("cover", e.target.files[0])}/></label></div><div className="asset-upload banner-upload" style={selected.bannerUrl ? { backgroundImage: `url(${selected.bannerUrl})` } : {}}><b>Book banner</b><span>Recommended 2400 × 900</span><label>Upload banner<input type="file" accept="image/*" onChange={(e) => asset("banner", e.target.files[0])}/></label></div><label>Title<input value={selected.title} onChange={(e) => update({ title: e.target.value })}/>{errors.title && <small>{errors.title}</small>}</label><label>Author<input value={selected.author} onChange={(e) => update({ author: e.target.value })}/>{errors.author && <small>{errors.author}</small>}</label><label>Language<select value={selected.language} onChange={(e) => update({ language: e.target.value })}>{LANGUAGES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Age rating<select value={selected.ageRating} onChange={(e) => update({ ageRating: e.target.value })}>{AGE_RATINGS.map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Genres<input value={selected.genres.join(", ")} onChange={(e) => update({ genres: list(e.target.value) })} placeholder="Fantasy, Mystery"/></label><label className="wide">Tags<input value={selected.tags.join(", ")} onChange={(e) => update({ tags: list(e.target.value) })} placeholder="found family, magic"/></label><label className="wide">Description<textarea rows="6" value={selected.description} onChange={(e) => update({ description: e.target.value })}/></label></div>}
      {tab === "Chapters" && <div className="chapter-manager"><aside><div><h3>Chapters</h3><button onClick={addChapter}>＋ Add</button></div>{selected.chapters.map((item, index) => <button className={chapterId === item.id ? "active" : ""} key={item.id} onClick={() => setChapterId(item.id)}><i>⋮⋮</i><span><b>{index + 1}. {item.title}</b><small>{item.audioStatus} · {item.content.replace(/<[^>]+>/g, "").length} chars</small></span></button>)}</aside>{chapter ? <article className="chapter-editor"><div className="chapter-actions"><button onClick={() => update({ chapters: reorderChapters(selected.chapters, selected.chapters.indexOf(chapter), selected.chapters.indexOf(chapter) - 1) })}>↑ Move up</button><button onClick={() => update({ chapters: reorderChapters(selected.chapters, selected.chapters.indexOf(chapter), selected.chapters.indexOf(chapter) + 1) })}>↓ Move down</button><button onClick={() => update({ chapters: [...selected.chapters, duplicateChapter(chapter)] })}>Duplicate</button><button className="cms-danger" onClick={() => { update({ chapters: selected.chapters.filter((item) => item.id !== chapter.id) }); setChapterId(""); }}>Delete</button></div><label>Chapter title<input value={chapter.title} onChange={(e) => updateChapter({ title: e.target.value })}/></label><div className="rich-toolbar"><button onMouseDown={(e) => { e.preventDefault(); document.execCommand("bold"); }}>B</button><button onMouseDown={(e) => { e.preventDefault(); document.execCommand("italic"); }}><i>I</i></button><button onMouseDown={(e) => { e.preventDefault(); document.execCommand("formatBlock", false, "h2"); }}>H2</button><span>Autosave on · {new Date(chapter.updatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div><div className="cms-rich" contentEditable suppressContentEditableWarning dangerouslySetInnerHTML={{ __html: chapter.content }} onInput={(e) => updateChapter({ content: e.currentTarget.innerHTML })}/></article> : <div className="cms-empty"><b>Select a chapter</b><p>Create, edit, duplicate and reorder chapters from this workspace.</p><button onClick={addChapter}>Create first chapter</button></div>}</div>}
      {tab === "Audio" && <div className="audio-manager"><div className="audio-callout"><div><b>Generate the complete audiobook</b><p>Queue narration for every chapter without ready audio.</p></div><button onClick={() => { update({ chapters: selected.chapters.map((item) => ({ ...item, audioStatus: "Ready" })) }); flash("Whole book queued for generation"); }}>Generate whole book</button></div>{selected.chapters.map((item, index) => <article key={item.id}><span>▶</span><div><b>{index + 1}. {item.title}</b><small>{item.audioStatus === "Ready" ? "Audio ready for preview" : "No generated audio"}</small></div><em className={item.audioStatus.toLowerCase()}>{item.audioStatus}</em>{item.audioStatus === "Ready" && <button onClick={() => flash(`Previewing ${item.title}`)}>Preview</button>}<button onClick={() => audio(item.id, "generate")}>{item.audioStatus === "Ready" ? "Regenerate" : "Generate"}</button>{item.audioStatus === "Ready" && <button className="cms-danger" onClick={() => audio(item.id, "delete")}>Delete</button>}</article>)}</div>}
      {tab === "Languages" && <div className="language-manager"><div className="panel-heading"><div><h3>Language versions</h3><p>Track every translation from first draft through final review.</p></div><button onClick={() => update({ versions: [...selected.versions, { id: crypto.randomUUID(), language: "Spanish", status: "Not started" }] })}>＋ Add language</button></div>{selected.versions.map((version) => <article key={version.id}><select value={version.language} onChange={(e) => update({ versions: selected.versions.map((item) => item.id === version.id ? { ...item, language: e.target.value } : item) })}>{LANGUAGES.map((item) => <option key={item}>{item}</option>)}</select><select value={version.status} onChange={(e) => update({ versions: selected.versions.map((item) => item.id === version.id ? { ...item, status: e.target.value } : item) })}>{TRANSLATION_STATUSES.map((item) => <option key={item}>{item}</option>)}</select><progress value={TRANSLATION_STATUSES.indexOf(version.status)} max="3"/><button className="cms-danger" onClick={() => update({ versions: selected.versions.filter((item) => item.id !== version.id) })}>Remove</button></article>)}</div>}
      {tab === "Publishing" && <div className="publishing-manager"><h3>Publishing workflow</h3><p>Choose the next lifecycle stage. Scheduled books require a future publication date.</p><div className="workflow">{BOOK_STATUSES.map((status, index) => <button className={selected.status === status ? "active" : ""} key={status} onClick={() => update({ status })}><i>{index + 1}</i><b>{status}</b><small>{["Private working copy", "Ready for editorial review", "Publish automatically", "Live for readers", "Hidden, safely retained"][index]}</small></button>)}</div>{selected.status === "Scheduled" && <label>Publication date and time<input type="datetime-local" value={selected.scheduledAt} onChange={(e) => update({ scheduledAt: e.target.value })}/>{errors.scheduledAt && <small>{errors.scheduledAt}</small>}</label>}<div className="publish-summary"><b>Release readiness</b><span>{selected.title && selected.author ? "✓ Metadata complete" : "○ Metadata incomplete"}</span><span>{selected.chapters.length ? `✓ ${selected.chapters.length} chapters` : "○ Add chapters"}</span><span>{selected.chapters.every((item) => item.audioStatus === "Ready") ? "✓ Audio complete" : "○ Audio generation pending"}</span></div></div>}
    </main> : <div className="cms-empty"><b>No books yet</b><button onClick={add}>Create your first book</button></div>}</div>
  </section>;
}
