import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import RichTextEditor from "./RichTextEditor";
const empty = { novel_id:"", title:"", number:"", content:"" };
function htmlToText(html="") { return html.replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>/gi,"\n\n").replace(/<[^>]+>/g,"").trim(); }
function ChapterForm({ initialChapter, chapterId }) { const navigate=useNavigate(); const [form,setForm]=useState(()=>({...empty,...(initialChapter||{})})); const [novels,setNovels]=useState([]); const [saving,setSaving]=useState(false); useEffect(()=>{ supabase.from("novels").select("id,title").order("title").then(({data})=>setNovels(data||[])); },[]);  function field(n,v){setForm(f=>({...f,[n]:v}))} async function save(e){ e.preventDefault(); setSaving(true); const payload={ novel_id:Number(form.novel_id), title:form.title, number:Number(form.number), content: htmlToText(form.content) }; const result = chapterId ? await supabase.from("chapters").update(payload).eq("id", chapterId) : await supabase.from("chapters").insert(payload); setSaving(false); if(result.error) alert(result.error.message); else navigate("/admin/chapters"); }
return <form className="admin-form" onSubmit={save}><div className="admin-form-grid"><label>Новела<select required value={form.novel_id} onChange={(e)=>field("novel_id", e.target.value)}><option value="">Оберіть новелу</option>{novels.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>Номер глави<input type="number" required value={form.number} onChange={(e)=>field("number", e.target.value)} /></label><label className="admin-full">Назва глави<input required value={form.title} onChange={(e)=>field("title", e.target.value)} /></label><label className="admin-full">Вміст глави<RichTextEditor value={form.content} onChange={(value)=>field("content", value)} /></label></div><div className="admin-actions"><button disabled={saving}>{saving?"Збереження...":"💾 Зберегти"}</button><button type="button" className="admin-secondary" onClick={()=>navigate("/admin/chapters")}>Скасувати</button></div></form> }
export default ChapterForm;
