import { useMemo, useState } from "react";
import { analyzeEmotions, applyEmotionOverride, createEmotionReport, createEmotionStorage, createEmotionTimeline, EMOTIONS } from "../lib/emotionEngine";

export default function EmotionStudio({ chapter }) {
  const storage = useMemo(() => createEmotionStorage(), []);
  const [items, setItems] = useState(() => analyzeEmotions(chapter?.content || "", storage.load(chapter?.id)));
  const [cursor, setCursor] = useState(0); const timeline = createEmotionTimeline(items); const report = createEmotionReport(items); const current = items[cursor];
  function patch(id, value) { setItems((rows) => applyEmotionOverride(rows, id, value)); }
  function save() { storage.save(chapter.id, items); }
  function regenerate() { setItems((rows) => analyzeEmotions(chapter?.content || "", rows)); }
  function preview() { if (!current || !("speechSynthesis" in window)) return; const utterance = new SpeechSynthesisUtterance(current.text); utterance.pitch = Math.max(0, Math.min(2, 1 + current.metadata.pitchModifier / 100)); utterance.rate = Math.max(.5, Math.min(2, 1 + current.metadata.rateModifier / 100)); utterance.volume = Math.max(.2, current.metadata.energy / 100); window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); }
  return <section className="admin-form emotion-studio"><h2>💓 Emotion Studio</h2><p className="admin-muted">Sentence-level expressive metadata. Analysis never rewrites the original chapter text; locked manual overrides survive regeneration.</p><div className="admin-actions"><button type="button" onClick={regenerate}>Analyze emotions</button><button type="button" onClick={save}>Save overrides</button><button type="button" disabled={!current} onClick={preview}>Preview emotion</button></div>
    <h3>Emotion Timeline</h3><div className="emotion-timeline">{timeline.map((point, index) => <button type="button" key={point.id} className={`emotion-point emotion-${point.emotion} ${index === cursor ? "selected" : ""}`} style={{ height: `${Math.max(28, point.intensity)}px` }} title={`${point.emotion} ${point.intensity}%`} onClick={() => setCursor(index)}><span>{point.emotion}</span><b>{point.intensity}</b>{point.manualOverride && " 🔒"}</button>)}</div>
    {current && <><h3>Emotion Preview & Override</h3><div className="admin-form-grid"><strong>Sentence {cursor + 1}</strong><span className="admin-full">{current.text}</span><label>Emotion<select value={current.emotion} onChange={(event) => patch(current.id, { emotion: event.target.value })}>{EMOTIONS.map((emotion) => <option key={emotion}>{emotion}</option>)}</select></label><label>Intensity <input type="range" min="0" max="100" value={current.intensity} onChange={(event) => patch(current.id, { intensity: Number(event.target.value) })} /> {current.intensity}</label>{Object.entries(current.metadata).map(([key, value]) => key === "emphasis" ? <label key={key}>Emphasis<select value={value} onChange={(event) => patch(current.id, { metadata: { emphasis: event.target.value } })}><option>none</option><option>light</option><option>moderate</option><option>strong</option></select></label> : <label key={key}>{key} <input type="number" min="-30" max="100" value={value} onChange={(event) => patch(current.id, { metadata: { [key]: Number(event.target.value) } })} /></label>)}<span className="admin-full">Contexts: {Object.entries(current.contexts).filter(([, active]) => active).map(([name]) => name).join(", ") || "none"}</span></div></>}
    <h3>Emotion Report</h3><div className="admin-warning"><strong>{report.sentences} sentences</strong> · average intensity {report.averageIntensity}% · {report.manualOverrides} manual overrides · peak {report.peak ? `${report.peak.emotion} ${report.peak.intensity}%` : "none"}<br />{Object.entries(report.emotions).filter(([, count]) => count).map(([name, count]) => `${name}: ${count}`).join(" · ")}<br />Contexts: {Object.entries(report.contexts).filter(([, count]) => count).map(([name, count]) => `${name}: ${count}`).join(" · ") || "none"}</div>
  </section>;
}
