import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { slugify } from "../lib/admin";

const emptyNovel = { title:"", author:"", description:"", rating:"", chapters:"", image:"", genres:"", category:"", tags:"", status:"Ongoing", views:0, bookmarks:0 };
function NovelForm({ initialNovel, novelId }) {
  const navigate = useNavigate(); const [form, setForm] = useState(() => ({ ...emptyNovel, ...(initialNovel || {}) })); const [coverFile, setCoverFile] = useState(null); const [saving, setSaving] = useState(false);
  function field(name, value){ setForm((f)=>({ ...f, [name]: value })); }
  async function uploadCover(){ if (!coverFile) return form.image; const path = `${Date.now()}-${slugify(coverFile.name)}`; const { error } = await supabase.storage.from("covers").upload(path, coverFile); if (error) throw error; return supabase.storage.from("covers").getPublicUrl(path).data.publicUrl; }
  async function save(e){ e.preventDefault(); setSaving(true); try { const image = await uploadCover(); const payload = { ...form, image, rating:Number(form.rating)||0, chapters:Number(form.chapters)||0, views:Number(form.views)||0, bookmarks:Number(form.bookmarks)||0 }; const result = novelId ? await supabase.from("novels").update(payload).eq("id", novelId) : await supabase.from("novels").insert(payload); if (result.error) throw result.error; navigate("/admin/novels"); } catch (error) { alert(error.message); } finally { setSaving(false); } }
  return <form className="admin-form" onSubmit={save}><div className="admin-form-grid"><label>Назва<input required value={form.title} onChange={(e)=>field("title", e.target.value)} /></label><label>Автор<input required value={form.author} onChange={(e)=>field("author", e.target.value)} /></label><label className="admin-full">Опис<textarea rows={6} required value={form.description} onChange={(e)=>field("description", e.target.value)} /></label><label>Категорія<input value={form.category || ""} onChange={(e)=>field("category", e.target.value)} placeholder="Fantasy" /></label><label>Жанри<input value={form.genres || ""} onChange={(e)=>field("genres", e.target.value)} placeholder="Action, Adventure" /></label><label className="admin-full">Теги<input value={form.tags || ""} onChange={(e)=>field("tags", e.target.value)} placeholder="magic, academy" /></label><label>Статус<select value={form.status || "Ongoing"} onChange={(e)=>field("status", e.target.value)}><option>Ongoing</option><option>Completed</option><option>Hiatus</option></select></label><label>Рейтинг<input type="number" step="0.1" value={form.rating} onChange={(e)=>field("rating", e.target.value)} /></label><label>Кількість глав<input type="number" value={form.chapters} onChange={(e)=>field("chapters", e.target.value)} /></label><label>Перегляди<input type="number" value={form.views} onChange={(e)=>field("views", e.target.value)} /></label><label>Закладки<input type="number" value={form.bookmarks} onChange={(e)=>field("bookmarks", e.target.value)} /></label><label className="admin-full">Обкладинка Supabase Storage<input type="file" accept="image/*" onChange={(e)=>setCoverFile(e.target.files?.[0] || null)} /></label></div>{form.image && <img style={{ width: 140, borderRadius: 12 }} src={form.image} alt="Поточна обкладинка" />}<div className="admin-actions"><button disabled={saving}>{saving ? "Збереження..." : "💾 Зберегти"}</button><button type="button" className="admin-secondary" onClick={()=>navigate("/admin/novels")}>Скасувати</button></div></form>;
}
export default NovelForm;
