import { useMemo, useState } from "react";
import { ambientLibrary, buildCinematicTimeline, cinematicLayers, cinematicMoods, cinematicSceneTypes, previewCinematicScene } from "../lib/cinematicSceneEngine";

export default function SceneStudio({ chapter }) {
  const [selectedScene, setSelectedScene] = useState(0);
  const timeline = useMemo(() => buildCinematicTimeline(chapter?.content || ""), [chapter?.content]);
  const preview = useMemo(() => previewCinematicScene(chapter?.content || "", selectedScene), [chapter?.content, selectedScene]);
  const reusableAssets = useMemo(() => [...new Set(timeline.flatMap((scene) => scene.layers.map((layer) => layer.asset).filter(Boolean)))], [timeline]);

  return <section className="admin-form scene-studio"><h2>🎞️ Scene Studio</h2><p className="admin-muted">Cinematic Scene Engine detects scene type, mood, ambience, effects, layers, ducking automation and reusable assets before full chapter rendering.</p><div className="admin-actions"><button type="button" disabled={!preview}>Preview one scene</button><button type="button" disabled={!timeline.length}>Render whole chapter timeline</button><span>{timeline.length} scenes · {reusableAssets.length} cached assets</span></div><div className="admin-chip-list">{cinematicSceneTypes.map((type) => <span className="admin-chip" key={type}>{type}</span>)}</div><h3>Timeline</h3><div className="admin-chip-list" style={{ overflowX: "auto", flexWrap: "nowrap" }}>{timeline.map((scene, index) => <button type="button" className="admin-chip" key={scene.id} onClick={() => setSelectedScene(index)}>#{index + 1} {scene.sceneType} · {scene.mood} · {Math.round(scene.confidence * 100)}%</button>)}</div>{preview && <><h3>Layer editor</h3><div className="admin-form-grid"><strong>{preview.title}</strong><span>{preview.sceneType}</span><span>{preview.mood}</span><span>{preview.duration}s</span>{cinematicLayers.map((layer) => <span key={layer}>{layer}</span>)}</div><h3>Volume editor</h3>{preview.layers.map((layer, index) => <div className="admin-form-grid" key={`${layer.layer}-${index}`}><strong>{layer.layer}</strong><span>{layer.role}</span><span>{layer.asset || "generated silence"}</span><label>Volume <input type="range" min="0" max="1" step="0.01" readOnly value={layer.volume} /></label><span>{layer.automation?.length ? "Ducks under dialogue, then restores ambience" : "Static volume"}</span></div>)}<h3>Preview</h3><p className="admin-warning">Narrator ↓ Ambient ↓ Dialogue ↓ Effects ↓ Music ↓ Next scene. Mood <strong>{preview.mood}</strong> influences music bed, ambience volume and voice energy.</p></>}<h3>Ambient Library</h3><div className="admin-form-grid">{Object.entries(ambientLibrary).map(([category, assets]) => <div key={category}><strong>{category}</strong><p className="admin-muted">{Object.keys(assets).join(", ")}</p></div>)}</div><h3>Emotional mixing</h3><p className="admin-muted">Supported moods: {cinematicMoods.join(", ")}.</p><h3>Cache</h3><p className="admin-muted">Reusable ambience/effects/music: {reusableAssets.join(", ") || "none yet"}. Assets are referenced by stable keys so files are reused and never duplicated.</p></section>;
}
