import { useEffect, useMemo, useState } from "react";
import { analyzeChapterVoice } from "../lib/voiceEngine/analyzer";
import { analyzeChapterOnServer, fetchChapterVoiceSegments, fetchVoiceCharacters, saveVoiceSegmentEdits } from "../lib/voiceEngine/client";
import { voiceProfiles, getPreviewSettings } from "../lib/voiceEngine/voiceProfiles";
const segmentTypes = ["narration","dialogue","thought","system","sound_effect"]; const emotions = ["neutral","calm","happy","sad","angry","afraid","surprised","determined","sarcastic","mysterious","tired","excited"];
function dbToUi(s) { return { ...s, type: s.segment_type, speakerId: s.speaker_id, speakerName: s.speaker_name, voiceProfile: s.voice_profile, segmentIndex: s.segment_index }; }
export default function VoiceStudio({ chapter }) {
 const [segments,setSegments]=useState([]),[characters,setCharacters]=useState([]),[notice,setNotice]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState(false),[bulkSpeaker,setBulkSpeaker]=useState(""),[bulkVoice,setBulkVoice]=useState("");
 useEffect(()=>{ if(!chapter?.id) return; Promise.all([fetchChapterVoiceSegments(chapter.id), fetchVoiceCharacters(chapter.novel_id)]).then(([s,c])=>{setSegments(s.map(dbToUi));setCharacters(c);});},[chapter?.id, chapter?.novel_id]);
 const stats=useMemo(()=>({total:segments.length, unresolved:segments.filter(s=>s.type==="dialogue"&&!s.speakerId&&!s.speaker_id).length, avg: segments.length ? (segments.reduce((a,s)=>a+Number(s.confidence||0),0)/segments.length).toFixed(2):"0"}),[segments]);
 const shown=segments.filter(s=> filter==="unresolved" ? s.type==="dialogue"&&!s.speakerId&&!s.speaker_id : filter==="all" || (s.speakerName||s.speaker_name)===filter);
 function localAnalyze(){ const r=analyzeChapterVoice({chapterId:chapter.id, novelId:chapter.novel_id, content:chapter.content, knownCharacters:characters}); setSegments(r.segments); setCharacters((c)=>[...c,...r.characters]); setNotice(`Local preview: ${r.statistics.totalSegments} segments, ${r.statistics.unresolvedSpeakers} unresolved.`); }
 async function serverAnalyze(force=false){ if(force && !confirm("Overwrite automated segments? Manual edits are preserved unless forced by the server.")) return; setBusy(true); try{ const r=await analyzeChapterOnServer(chapter.id,{force}); setNotice(`Saved analysis: ${r.statistics?.totalSegments || 0} segments.`); const fresh=await fetchChapterVoiceSegments(chapter.id); setSegments(fresh.map(dbToUi)); }catch(e){ setNotice(e.message || "Analysis failed safely."); } finally{ setBusy(false); } }
 function update(i,k,v){ setSegments((rows)=>rows.map((s,idx)=>idx===i?{...s,[k]:v, manually_edited:true}:s)); }
 async function save(){ setBusy(true); try{ await saveVoiceSegmentEdits(segments.filter(s=>s.id && !String(s.id).includes("-"))); setNotice("Manual corrections saved."); }catch(e){ setNotice(e.message); } finally{ setBusy(false); } }
 function preview(s){ if(!("speechSynthesis" in window)) return; const u=new SpeechSynthesisUtterance(s.text); const p=getPreviewSettings(s.voiceProfile||s.voice_profile); u.pitch=p.pitch; u.rate=p.rate; window.speechSynthesis.cancel(); window.speechSynthesis.speak(u); }
 function bulk(){ setSegments(rows=>rows.map(s=> shown.includes(s)?{...s, speakerName:bulkSpeaker||s.speakerName, speakerId:bulkSpeaker?bulkSpeaker.toLowerCase().replace(/\W+/g,"_"):s.speakerId, voiceProfile:bulkVoice||s.voiceProfile, manually_edited:true}:s)); }
 return <section className="admin-form"><h2>🎙️ Voice Studio</h2>{notice&&<p className="admin-toast">{notice}</p>}<div className="admin-actions"><button type="button" onClick={localAnalyze}>Analyze locally</button><button type="button" disabled={busy} onClick={()=>serverAnalyze(false)}>Analyze chapter</button><button type="button" disabled={busy} onClick={()=>serverAnalyze(true)}>Re-analyze</button><button type="button" disabled={busy} onClick={save}>Save manual corrections</button></div><p className="admin-muted">Segments: {stats.total} · Unresolved: {stats.unresolved} · Average confidence: {stats.avg}. Browser SpeechSynthesis preview approximates pitch/rate only.</p><div className="admin-actions"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All speakers</option><option value="unresolved">Unresolved only</option>{[...new Set(segments.map(s=>s.speakerName).filter(Boolean))].map(n=><option key={n}>{n}</option>)}</select><input placeholder="Bulk speaker" value={bulkSpeaker} onChange={e=>setBulkSpeaker(e.target.value)}/><select value={bulkVoice} onChange={e=>setBulkVoice(e.target.value)}><option value="">Bulk voice profile</option>{voiceProfiles.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select><button type="button" onClick={bulk}>Apply bulk</button></div><h3>Detected characters</h3><div className="admin-chip-list">{characters.map((c,i)=><span className="admin-chip" key={c.id||c.canonicalName||i}>{c.display_name||c.displayName||c.canonical_name} · {c.voice_profile||c.voiceProfile}</span>)}</div><h3>Segments</h3>{shown.map((s,i)=><div className="admin-form-grid" key={s.id||i}><select value={s.type||s.segment_type} onChange={e=>update(i,"type",e.target.value)}>{segmentTypes.map(t=><option key={t}>{t}</option>)}</select><input value={s.speakerName||""} onChange={e=>update(i,"speakerName",e.target.value)} placeholder="Speaker"/><select value={s.voiceProfile||"unknown_neutral"} onChange={e=>update(i,"voiceProfile",e.target.value)}>{voiceProfiles.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select><select value={s.emotion||"neutral"} onChange={e=>update(i,"emotion",e.target.value)}>{emotions.map(e=><option key={e}>{e}</option>)}</select><input type="range" min="0" max="1" step="0.05" value={s.intensity||0} onChange={e=>update(i,"intensity",e.target.value)}/><textarea className="admin-full" value={s.text||""} onChange={e=>update(i,"text",e.target.value)}/><button type="button" onClick={()=>preview(s)}>Preview Device Voice</button></div>)}</section>;
}
