import { voiceCastSlots, voiceCastSlotMap } from "./castSlots.js";

const riskySingleTokens = new Set(["лін", "линь", "пан", "пані", "містер", "міс", "фань"]);
const norm = (value = "") => String(value).toLowerCase().normalize("NFKC").replace(/[’'`ʼ]/g, "").replace(/[.,!?;:()\[\]{}«»“”„\-—–]/g, " ").replace(/\s+/g, " ").trim();
const stripTitles = (value) => norm(value).replace(/^(молодий|старий|пан|пані|лорд|леді|майстер|містер|міс|панич)\s+/iu, "").trim();
const tokens = (value) => stripTitles(value).split(" ").filter(Boolean);
export function normalizeCharacterName(value) { return stripTitles(value).replace(/и/g, "і").replace(/ь/g, ""); }
export function makeCastEntry(novelId, character, slot, source = "automatic") { return { novel_id: novelId, character_id: character.id, cast_slot: slot.id, voice_profile: character.voice_profile || character.voiceProfile || slot.defaultVoiceProfile, provider_voice_id: null, cloned_voice_id: null, language: character.language || null, gender: character.gender || slot.gender, age_group: character.age_group || character.ageGroup || slot.ageGroup, character_role: character.character_role || character.characterRole || "unknown", ...slot.acoustic, pitch_offset: slot.acoustic.pitchOffset, rate_offset: slot.acoustic.rateOffset, manually_locked: false, assignment_source: source, confidence: Number(character.confidence ?? 0.5), notes: "Assigned by deterministic NovelVerse cast memory." }; }
function compatible(slot, c) { const g = c.gender || c.genderGroup || "unknown"; const a = c.age_group || c.ageGroup || "unknown"; const r = c.character_role || c.characterRole || "unknown"; if (r === "narrator") return slot.id.startsWith("narrator_"); if (r === "system") return slot.id === "system_01"; if (g !== "unknown" && slot.gender !== "unknown" && slot.gender !== g) return false; if (a !== "unknown" && slot.ageGroup !== "unknown" && slot.ageGroup !== a) return false; return slot.compatibleRoles.includes(r) || slot.compatibleRoles.includes("unknown") || slot.compatibleRoles.includes("supporting"); }
function score(slot, c) { let s = 0; if (slot.gender === (c.gender || "unknown")) s += 4; if (slot.ageGroup === (c.age_group || c.ageGroup || "unknown")) s += 5; if (slot.compatibleRoles.includes(c.character_role || c.characterRole || "unknown")) s += 4; if ((c.character_role || c.characterRole) === "protagonist" && slot.id.includes("hero")) s += 10; return s; }
export function assignNovelVoiceCast({ novelId, characters = [], existingCast = [] }) { const warnings = []; const byCharacter = new Map(existingCast.map((e) => [String(e.character_id ?? e.characterId), e])); const used = new Set(existingCast.map((e) => e.cast_slot ?? e.castSlot).filter(Boolean)); const cast = []; for (const c of characters) { if (!c?.id) continue; const previous = byCharacter.get(String(c.id)); if (previous) { cast.push(previous); continue; } let candidates = voiceCastSlots.filter((slot) => compatible(slot, c)).sort((a,b)=>score(b,c)-score(a,c)||a.id.localeCompare(b.id)); const role = c.character_role || c.characterRole; if (role === "narrator") candidates = [voiceCastSlotMap.narrator_main]; if (role === "system" || c.id === "system") candidates = [voiceCastSlotMap.system_01]; if ((c.gender === "unknown" || role === "unknown") && !candidates.length) candidates = [voiceCastSlotMap.unknown_01]; let selected = candidates.find((slot) => slot.shareable || !used.has(slot.id)) || candidates.find((slot) => slot.shareable) || voiceCastSlotMap.unknown_01; if (!selected) { warnings.push(`No compatible voice cast slot for ${c.display_name || c.displayName || c.canonical_name || c.canonicalName}.`); selected = voiceCastSlotMap.unknown_01; } if (selected.exclusive && used.has(selected.id)) warnings.push(`Exclusive cast slot ${selected.id} is already assigned in this novel.`); used.add(selected.id); cast.push(makeCastEntry(novelId, c, selected)); } return { cast, warnings }; }
export function resolveCharacterAlias(input, characters = [], manualAliases = {}) { const wanted = normalizeCharacterName(input); if (!wanted) return { character: null, confidence: 0, risky: false }; for (const [alias, id] of Object.entries(manualAliases)) if (normalizeCharacterName(alias) === wanted) return { character: characters.find((c)=>String(c.id)===String(id)) || null, confidence: 1, risky: false, source: "manual" }; let best = { character: null, confidence: 0, risky: false }; for (const c of characters) { const names = [c.canonical_name, c.canonicalName, c.display_name, c.displayName, ...(c.aliases || [])].filter(Boolean); for (const name of names) { const n = normalizeCharacterName(name); if (n === wanted) return { character: c, confidence: 0.96, risky: false, source: "exact" }; const nt = tokens(n), wt = tokens(wanted); const overlap = wt.filter((t) => nt.includes(t)); const risky = wt.length === 1 && (riskySingleTokens.has(wt[0]) || nt.length > 2 || overlap.length < nt.length); const confidence = risky ? 0.48 : overlap.length >= Math.min(2, nt.length, wt.length) ? 0.82 : 0; if (confidence > best.confidence) best = { character: c, confidence, risky, source: "alias" }; } } return best.risky || best.confidence < 0.75 ? { ...best, character: null } : best; }
export function validateVoiceCast({ cast = [], characters = [], segments = [] }) { const warnings = []; const byChar = new Map(); const byCharacterEntry = new Map(); const bySlot = new Map(); cast.forEach((e) => { const cid = String(e.character_id ?? e.characterId); const slot = e.cast_slot ?? e.castSlot; if (byChar.has(cid) && byChar.get(cid) !== slot) warnings.push("one_character_multiple_cast_slots"); byChar.set(cid, slot); byCharacterEntry.set(cid, e); const list = bySlot.get(slot) || []; list.push(e); bySlot.set(slot, list); const slotDef = voiceCastSlotMap[slot]; if (slotDef && e.age_group === "child" && slotDef.ageGroup === "elderly") warnings.push("elderly_profile_assigned_to_child_character"); if (slotDef && e.age_group === "elderly" && ["child", "young"].includes(slotDef.ageGroup)) warnings.push("incompatible_age_profile_combination"); }); bySlot.forEach((list, slot) => { const def = voiceCastSlotMap[slot]; if (def?.exclusive && list.length > 1) warnings.push("exclusive_cast_slot_assigned_to_several_characters"); }); characters.forEach((c) => { if (c.id && !byChar.has(String(c.id))) warnings.push("missing_cast_record"); }); segments.forEach((s) => { if (s.segment_type === "narration" && s.speaker_id) warnings.push("narrator_segment_assigned_to_character_voice"); const castEntry = byCharacterEntry.get(String(s.speaker_id)); if (castEntry && s.voice_profile && s.voice_profile !== castEntry.voice_profile && castEntry.manually_locked) warnings.push("segment_profile_differs_from_locked_cast"); }); return [...new Set(warnings)]; }
export function resolveProviderVoice({ castEntry, provider, language }) { const mapping = castEntry?.provider_voice_mappings?.[provider]?.[language] || castEntry?.provider_voice_mappings?.[provider] || castEntry?.provider_voice_id || castEntry?.cloned_voice_id; return mapping ? { status: "configured", provider, voiceId: mapping } : { status: "provider_voice_not_configured", provider, voiceId: null }; }
async function getSupabase() { return (await import("../supabase.js")).supabase; }
export async function getNovelVoiceCast(novelId) { if (!novelId) return []; const supabase = await getSupabase(); const { data, error } = await supabase.from("novel_voice_cast").select("*").eq("novel_id", novelId).order("cast_slot"); if (error) return []; return data || []; }
export async function getCharacterCast(characterId) { const supabase = await getSupabase(); const { data, error } = await supabase.from("novel_voice_cast").select("*").eq("character_id", characterId).maybeSingle(); if (error) return null; return data; }
export async function assignCharacterVoice(entry) { const supabase = await getSupabase(); const { data, error } = await supabase.from("novel_voice_cast").upsert(entry).select("*").single(); if (error) throw error; return data; }
export const lockCharacterVoice = async (id) => (await getSupabase()).from("novel_voice_cast").update({ manually_locked: true, assignment_source: "manual" }).eq("id", id);
export const unlockCharacterVoice = async (id) => (await getSupabase()).from("novel_voice_cast").update({ manually_locked: false }).eq("id", id);
export const updateCastParameters = async (id, values) => (await getSupabase()).from("novel_voice_cast").update(values).eq("id", id);
export async function mergeCharacters({ sourceCharacterId, targetCharacterId }) { if (!sourceCharacterId || !targetCharacterId || sourceCharacterId === targetCharacterId) throw new Error("Select two different characters to merge."); const supabase = await getSupabase(); await supabase.from("chapter_voice_segments").update({ speaker_id: targetCharacterId }).eq("speaker_id", sourceCharacterId); await supabase.from("novel_voice_cast").delete().eq("character_id", sourceCharacterId); await supabase.from("voice_characters").delete().eq("id", sourceCharacterId); return { sourceCharacterId, targetCharacterId }; }
