export const AI_BRAIN_VERSION = "ai-brain-v1";
export const RELATIONSHIP_TYPES = ["ally","enemy","family","parent","child","sibling","mentor","student","romantic","rival","servant","master","unknown"];
const now=()=>new Date().toISOString();
const norm=(s="")=>String(s).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/\b(the|young|master|brother|sister|lord|lady|immortal|emperor|elder|sect|sir|mr|mrs|miss)\b/g," ").replace(/[^a-zа-яіїєґё0-9]+/giu," ").trim();
const titleRx=/\b(Young Master|Brother|Sister|Lord|Lady|Elder|The Immortal Emperor|Immortal Emperor|Master)\s+([A-ZА-ЯІЇЄҐ][\p{L}'-]+)/gu;
const nameRx=/\b([A-ZА-ЯІЇЄҐ][\p{L}'-]+(?:\s+[A-ZА-ЯІЇЄҐ][\p{L}'-]+){0,2})\b/gu;
export function createLocalAiBrainProvider(){return {analyzeChapter,extractCharacters,resolveAliases,extractRelationships,extractCharacterStates,buildVoiceEvolution,buildStoryContext};}
export async function analyzeChapter(input){const provider=createLocalAiBrainProvider(); const characters=provider.extractCharacters(input); const aliases=provider.resolveAliases({characters,existingCharacters:input.existingCharacters||[],chapterNumber:input.chapterNumber}); const states=provider.extractCharacterStates({...input,characters}); const relationships=provider.extractRelationships({...input,characters}); const voiceEvolution=states.map(s=>({character_id:s.character_id,chapter_id:s.chapter_id,chapter_number:s.chapter_number,modifiers:provider.buildVoiceEvolution({state:s,previousState:(input.previousStates||[]).find(p=>p.character_id===s.character_id)})})); const context=provider.buildStoryContext({...input,characters,states,relationships}); const warnings=detectContradictions({characters:[...(input.existingCharacters||[]),...characters],states:[...(input.previousStates||[]),...states],relationships,chapterNumber:input.chapterNumber}); return {version:AI_BRAIN_VERSION,characters,aliases,states,relationships,voiceEvolution,context,warnings};}
export function extractCharacters({novelId,chapterId,chapterNumber=1,text=""}={}){const found=new Map(); for(const rx of [titleRx,nameRx]){let m; while((m=rx.exec(text))){const raw=(m[0]||"").trim(); if(raw.length<3||/^(Chapter|System|The End)$/i.test(raw))continue; const canonical=raw.replace(/^(Young Master|Brother|Sister|Lord|Lady|Elder|The)\s+/i,"").trim(); const key=norm(canonical); if(!found.has(key)) found.set(key,{id:`char_${key.replace(/\s+/g,"_")}`,novel_id:novelId,canonical_name:canonical,aliases:[raw].filter(a=>norm(a)!==key),gender:"unknown",estimated_age:null,role:"unknown",species:"human",personality_traits:[],speaking_style:"neutral",emotional_baseline:"neutral",first_appearance_chapter:chapterNumber,last_seen_chapter:chapterNumber,confidence:0.62,created_at:now(),updated_at:now(),chapter_id:chapterId}); else if(raw!==canonical) found.get(key).aliases=[...new Set([...found.get(key).aliases,raw])]; }} return [...found.values()];}
export function resolveAliases({characters=[],existingCharacters=[],chapterNumber=1}={}){const merged=[],reviewQueue=[]; for(const c of characters){let best=null,bestScore=0; for(const e of existingCharacters){const names=[e.canonical_name,...(e.aliases||[])]; const score=Math.max(...names.map(n=>aliasScore(c.canonical_name,n)),0); if(score>bestScore){best=e;bestScore=score;}} if(bestScore>=0.86) merged.push({from:c.id,to:best.id,confidence:bestScore,aliases:[c.canonical_name,...c.aliases],chapter_number:chapterNumber}); else if(bestScore>=0.55) reviewQueue.push({candidate_character_id:c.id,matched_character_id:best?.id,type:"possible_alias",confidence:Number(bestScore.toFixed(2)),status:"open",chapter_number:chapterNumber,notes:`Possible alias: ${c.canonical_name} → ${best?.canonical_name}`}); } return {merged,reviewQueue};}
export function aliasScore(a,b){const na=norm(a), nb=norm(b); if(!na||!nb)return 0; if(na===nb)return 1; if(na.includes(nb)||nb.includes(na))return .82; const as=new Set(na.split(" ")), bs=new Set(nb.split(" ")); const overlap=[...as].filter(x=>bs.has(x)).length/Math.max(as.size,bs.size); return Number(overlap.toFixed(2));}
export function extractRelationships({text="",characters=[],chapterNumber=1}={}){const out=[]; const lower=text.toLowerCase(); const pairs=(type,words)=>{if(words.some(w=>lower.includes(w))&&characters.length>=2) out.push({source_character_id:characters[0].id,target_character_id:characters[1].id,type,strength:type==="enemy"?.7:.55,confidence:.58,first_detected_chapter:chapterNumber,last_updated_chapter:chapterNumber,active:true,notes:`Deterministic ${type} signal.`});}; pairs("enemy",["enemy","rival","attacked","betrayed"]); pairs("ally",["ally","friend","helped","protected"]); pairs("mentor",["mentor","teacher","disciple","student"]); pairs("family",["father","mother","brother","sister","family"]); return out;}
export function extractCharacterStates({chapterId,chapterNumber=1,text="",characters=[]}={}){const lower=text.toLowerCase(); return characters.map(c=>({character_id:c.id,chapter_id:chapterId,chapter_number:chapterNumber,age:/child|boy|girl|young/i.test(text)?"young":null,physical_state:/wound|injur|bleed|поран/i.test(lower)?"wounded":"normal",emotional_state:/angry|rage|furious/i.test(lower)?"angry":/afraid|fear|timid/i.test(lower)?"afraid":"neutral",social_status:/emperor|immortal/i.test(c.canonical_name)?"sovereign":"unknown",power_level:/immortal|ascend|transform/i.test(lower)?"transformed":"normal",injuries:/wound|injur|bleed/i.test(lower)?["injury_detected"]:[],transformations:/immortal|ascend|became young|transformed/i.test(lower)?["transformation_detected"]:[],voice_age:/elderly|old/i.test(lower)?"elderly":/child|young/i.test(lower)?"young":"adult",voice_depth:null,voice_energy:null,voice_stability:/unstable|mad|rage/i.test(lower)?"unstable":"stable",notes:"Deterministic local analysis state."}));}
export function buildVoiceEvolution({state={},previousState=null}={}){const temp=(state.injuries||[]).length>0; const transformed=(state.transformations||[]).length>0; return {pitch_offset:state.voice_age==="young"?.08:state.voice_age==="elderly"?-.06:0,speed_offset:temp?-.12:transformed?.04:0,energy_offset:state.emotional_state==="angry"?.14:temp?-.2:0,breathiness:temp?.24:0,roughness:temp?.18:state.voice_stability==="unstable"?.16:0,confidence:state.emotional_state==="afraid"?-.18:transformed?.12:0,emotional_control:state.voice_stability==="unstable"?-.25:0,change_type:temp?"temporary":transformed?"permanent":"gradual",previous_chapter:previousState?.chapter_number};}
export function buildStoryContext({novelId,chapterId,chapterNumber=1,text="",characters=[],states=[],relationships=[]}={}){const sentences=text.split(/[.!?]\s+/).filter(Boolean).slice(-5); return {novel_id:novelId,chapter_id:chapterId,chapter_number:chapterNumber,important_recent_events:sentences,active_characters:characters.map(c=>c.id),unresolved_conflicts:relationships.filter(r=>r.type==="enemy"||r.type==="rival"),current_relationships:relationships,current_character_states:states,relevant_locations:[],chronology_markers:[`chapter_${chapterNumber}`],summary_version:AI_BRAIN_VERSION};}
export function detectContradictions({characters=[],states=[]}={}){const warnings=[]; const by=new Map(); for(const s of states){const list=by.get(s.character_id)||[]; const prev=list.at(-1); if(prev&&prev.age&&s.age&&String(s.age)<String(prev.age)) warnings.push({type:"age_regression",severity:"warning",character_id:s.character_id,message:"Age appears to move backwards without an explicit explanation."}); if(prev?.physical_state==="dead"&&s.physical_state!=="dead") warnings.push({type:"dead_character_alive",severity:"warning",character_id:s.character_id,message:"Dead character appears alive."}); list.push(s); by.set(s.character_id,list);} const names=new Map(); for(const c of characters){const k=norm(c.canonical_name); if(names.has(k)&&names.get(k)!==c.id) warnings.push({type:"duplicate_identity",severity:"warning",character_id:c.id,message:"Two records share the same normalized identity."}); names.set(k,c.id);} return warnings;}
