create table if not exists public.chapter_director_plans (
  id uuid primary key default gen_random_uuid(), chapter_id uuid not null references public.chapters(id) on delete cascade, novel_id bigint not null references public.novels(id) on delete cascade,
  analysis_version text, director_version text not null, language text, scene_count integer not null default 0 check (scene_count >= 0), total_segments integer not null default 0 check (total_segments >= 0), average_intensity numeric not null default 0 check (average_intensity >= 0 and average_intensity <= 1), status text not null default 'draft' check (status in ('draft','ready','invalid','outdated')), warnings jsonb not null default '[]'::jsonb, statistics jsonb not null default '{}'::jsonb, content_hash text not null, manually_edited boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid null references auth.users(id) on delete set null);
create unique index if not exists chapter_director_one_ready_hash_idx on public.chapter_director_plans(chapter_id, content_hash) where status = 'ready';
create index if not exists chapter_director_chapter_status_idx on public.chapter_director_plans(chapter_id,status,updated_at desc);
create index if not exists chapter_director_novel_idx on public.chapter_director_plans(novel_id,updated_at desc);
create table if not exists public.director_scenes (
  id uuid primary key default gen_random_uuid(), director_plan_id uuid not null references public.chapter_director_plans(id) on delete cascade, chapter_id uuid not null references public.chapters(id) on delete cascade, novel_id bigint not null references public.novels(id) on delete cascade, scene_index integer not null check (scene_index >= 0), scene_type text not null, title text, start_segment_index integer not null check (start_segment_index >= 0), end_segment_index integer not null check (end_segment_index >= start_segment_index), intensity numeric not null default 0 check (intensity >= 0 and intensity <= 1), pace text not null default 'moderate' check (pace in ('slow','moderate','fast')), atmosphere_profile text, music_profile text, ambience_volume numeric not null default 0 check (ambience_volume >= 0 and ambience_volume <= 1), notes text, manually_edited boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(director_plan_id, scene_index));
create index if not exists director_scenes_plan_idx on public.director_scenes(director_plan_id, scene_index);
create index if not exists director_scenes_chapter_idx on public.director_scenes(chapter_id, scene_index);
create table if not exists public.director_segment_settings (
  id uuid primary key default gen_random_uuid(), director_plan_id uuid not null references public.chapter_director_plans(id) on delete cascade, scene_id uuid null references public.director_scenes(id) on delete set null, voice_segment_id uuid not null references public.chapter_voice_segments(id) on delete cascade, segment_index integer not null check (segment_index >= 0), cast_slot text, voice_profile text, emotion text, intensity numeric check (intensity is null or (intensity >= 0 and intensity <= 1)), delivery_style text, rate numeric not null default 1 check (rate >= 0.6 and rate <= 1.35), pitch numeric not null default 0 check (pitch >= -0.35 and pitch <= 0.35), energy numeric not null default 0.5 check (energy >= 0 and energy <= 1), volume numeric not null default 1 check (volume >= 0 and volume <= 1), pause_before_ms integer not null default 0 check (pause_before_ms >= 0 and pause_before_ms <= 1800), pause_after_ms integer not null default 0 check (pause_after_ms >= 0 and pause_after_ms <= 1800), emphasis jsonb not null default '[]'::jsonb, sound_cues jsonb not null default '[]'::jsonb, manually_edited boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(director_plan_id, segment_index));
create index if not exists director_segment_plan_idx on public.director_segment_settings(director_plan_id, segment_index);
create index if not exists director_segment_scene_idx on public.director_segment_settings(scene_id, segment_index);
create index if not exists director_segment_voice_idx on public.director_segment_settings(voice_segment_id);
drop trigger if exists set_chapter_director_plans_updated_at on public.chapter_director_plans; create trigger set_chapter_director_plans_updated_at before update on public.chapter_director_plans for each row execute function public.set_voice_engine_updated_at();
drop trigger if exists set_director_scenes_updated_at on public.director_scenes; create trigger set_director_scenes_updated_at before update on public.director_scenes for each row execute function public.set_voice_engine_updated_at();
drop trigger if exists set_director_segment_settings_updated_at on public.director_segment_settings; create trigger set_director_segment_settings_updated_at before update on public.director_segment_settings for each row execute function public.set_voice_engine_updated_at();
alter table public.chapter_director_plans enable row level security; alter table public.director_scenes enable row level security; alter table public.director_segment_settings enable row level security;
drop policy if exists "Ready director plans are readable" on public.chapter_director_plans; create policy "Ready director plans are readable" on public.chapter_director_plans for select using (status = 'ready' or public.is_admin());
drop policy if exists "Admins manage director plans" on public.chapter_director_plans; create policy "Admins manage director plans" on public.chapter_director_plans for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Ready director scenes are readable" on public.director_scenes; create policy "Ready director scenes are readable" on public.director_scenes for select using (exists (select 1 from public.chapter_director_plans p where p.id = director_plan_id and p.status = 'ready') or public.is_admin());
drop policy if exists "Admins manage director scenes" on public.director_scenes; create policy "Admins manage director scenes" on public.director_scenes for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Ready director segment settings are readable" on public.director_segment_settings; create policy "Ready director segment settings are readable" on public.director_segment_settings for select using (exists (select 1 from public.chapter_director_plans p where p.id = director_plan_id and p.status = 'ready') or public.is_admin());
drop policy if exists "Admins manage director segment settings" on public.director_segment_settings; create policy "Admins manage director segment settings" on public.director_segment_settings for all using (public.is_admin()) with check (public.is_admin());
