create table if not exists public.character_profiles (
  id uuid primary key default gen_random_uuid(), novel_id bigint not null references public.novels(id) on delete cascade, canonical_name text not null, aliases text[] not null default '{}', gender text default 'unknown', estimated_age text, role text default 'unknown', species text default 'human', personality_traits text[] not null default '{}', speaking_style text default 'neutral', emotional_baseline text default 'neutral', first_appearance_chapter integer, last_seen_chapter integer, confidence numeric(4,3) not null default 0.5, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(novel_id, canonical_name)
);
create table if not exists public.character_aliases (id uuid primary key default gen_random_uuid(), character_id uuid not null references public.character_profiles(id) on delete cascade, alias text not null, alias_type text default 'name', confidence numeric(4,3) not null default 0.5, active boolean not null default true, created_at timestamptz not null default now(), unique(character_id, alias));
create table if not exists public.character_states (id uuid primary key default gen_random_uuid(), character_id uuid not null references public.character_profiles(id) on delete cascade, chapter_id bigint references public.chapters(id) on delete set null, chapter_number integer not null, age text, physical_state text, emotional_state text, social_status text, power_level text, injuries text[] not null default '{}', transformations text[] not null default '{}', voice_age text, voice_depth text, voice_energy text, voice_stability text, notes text, created_at timestamptz not null default now());
create table if not exists public.character_relationships (id uuid primary key default gen_random_uuid(), source_character_id uuid not null references public.character_profiles(id) on delete cascade, target_character_id uuid not null references public.character_profiles(id) on delete cascade, type text not null check (type in ('ally','enemy','family','parent','child','sibling','mentor','student','romantic','rival','servant','master','unknown')), strength numeric(4,3) not null default 0.5, confidence numeric(4,3) not null default 0.5, first_detected_chapter integer, last_updated_chapter integer, active boolean not null default true, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(source_character_id <> target_character_id));
create table if not exists public.story_contexts (id uuid primary key default gen_random_uuid(), novel_id bigint not null references public.novels(id) on delete cascade, chapter_id bigint references public.chapters(id) on delete cascade, chapter_number integer not null, important_recent_events jsonb not null default '[]', active_characters jsonb not null default '[]', unresolved_conflicts jsonb not null default '[]', current_relationships jsonb not null default '[]', current_character_states jsonb not null default '[]', relevant_locations jsonb not null default '[]', chronology_markers jsonb not null default '[]', summary_version text not null default 'ai-brain-v1', created_at timestamptz not null default now());
create table if not exists public.identity_review_queue (id uuid primary key default gen_random_uuid(), novel_id bigint references public.novels(id) on delete cascade, candidate_character_id uuid references public.character_profiles(id) on delete cascade, matched_character_id uuid references public.character_profiles(id) on delete cascade, type text not null default 'possible_alias', confidence numeric(4,3) not null default 0.5, status text not null default 'open', chapter_number integer, notes text, created_at timestamptz not null default now(), resolved_at timestamptz);
create table if not exists public.analysis_warnings (id uuid primary key default gen_random_uuid(), novel_id bigint references public.novels(id) on delete cascade, chapter_id bigint references public.chapters(id) on delete cascade, character_id uuid references public.character_profiles(id) on delete set null, type text not null, severity text not null default 'warning', message text not null, active boolean not null default true, created_at timestamptz not null default now());
create index if not exists idx_character_profiles_novel on public.character_profiles(novel_id);
create index if not exists idx_character_aliases_character on public.character_aliases(character_id);
create index if not exists idx_character_states_character_chapter on public.character_states(character_id, chapter_number desc);
create index if not exists idx_character_relationships_source on public.character_relationships(source_character_id, active);
create index if not exists idx_story_contexts_novel_chapter on public.story_contexts(novel_id, chapter_number desc);
create index if not exists idx_identity_review_queue_status on public.identity_review_queue(status, novel_id);
create index if not exists idx_analysis_warnings_active on public.analysis_warnings(active, novel_id);
alter table public.character_profiles enable row level security; alter table public.character_aliases enable row level security; alter table public.character_states enable row level security; alter table public.character_relationships enable row level security; alter table public.story_contexts enable row level security; alter table public.identity_review_queue enable row level security; alter table public.analysis_warnings enable row level security;
create policy "Public can read ai brain profiles" on public.character_profiles for select using (true);
create policy "Public can read ai brain aliases" on public.character_aliases for select using (true);
create policy "Public can read ai brain states" on public.character_states for select using (true);
create policy "Public can read ai brain relationships" on public.character_relationships for select using (true);
create policy "Public can read story contexts" on public.story_contexts for select using (true);
create policy "Admins manage ai brain profiles" on public.character_profiles for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage ai brain aliases" on public.character_aliases for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage ai brain states" on public.character_states for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage ai brain relationships" on public.character_relationships for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage story contexts" on public.story_contexts for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage identity queue" on public.identity_review_queue for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage analysis warnings" on public.analysis_warnings for all using (public.is_admin()) with check (public.is_admin());
