-- NovelVerse Creator Portal production upgrade.
--
-- This migration intentionally keeps `novels` as the canonical book table.  It
-- is safe to apply to both the legacy reader schema and a partially upgraded
-- Creator Portal database.  All DDL is additive and every data backfill is
-- repeatable; no legacy column or row is removed.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Canonical books and chapters
-- ---------------------------------------------------------------------------

create table if not exists public.novels (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null default '',
  description text not null default '',
  created_at timestamptz not null default now()
);

alter table public.novels add column if not exists owner_id uuid;
alter table public.novels add column if not exists genres text[] not null default '{}';
alter table public.novels add column if not exists tags text[] not null default '{}';
alter table public.novels add column if not exists language text not null default 'English';
alter table public.novels add column if not exists age_rating text not null default '13+';
alter table public.novels add column if not exists status text not null default 'Draft';
alter table public.novels add column if not exists cover_url text;
alter table public.novels add column if not exists banner_url text;
alter table public.novels add column if not exists scheduled_at timestamptz;
alter table public.novels add column if not exists published_at timestamptz;
alter table public.novels add column if not exists created_at timestamptz not null default now();
alter table public.novels add column if not exists updated_at timestamptz not null default now();
alter table public.novels alter column owner_id set default auth.uid();

-- Preserve legacy cover images while making them available to Creator Portal.
do $migration$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'novels' and column_name = 'image'
  ) then
    execute $sql$update public.novels
      set cover_url = image
      where cover_url is null and image is not null$sql$;
  end if;
end
$migration$;

create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  novel_id bigint,
  number integer,
  title text not null default '',
  content text not null default '',
  created_at timestamptz not null default now()
);

alter table public.chapters add column if not exists novel_id bigint;
alter table public.chapters add column if not exists number integer;
alter table public.chapters add column if not exists title text not null default '';
alter table public.chapters add column if not exists content text not null default '';
alter table public.chapters add column if not exists position integer;
alter table public.chapters add column if not exists status text not null default 'Draft';
alter table public.chapters add column if not exists audio_status text not null default 'Missing';
alter table public.chapters add column if not exists audio_url text;
alter table public.chapters add column if not exists created_at timestamptz not null default now();
alter table public.chapters add column if not exists updated_at timestamptz not null default now();

-- Existing reader chapters use `number`; Creator Portal uses `position`.
-- Populate both directions so either client remains able to order every row.
update public.chapters set position = number where position is null and number is not null;
with missing_positions as (
  select id, row_number() over (partition by novel_id order by created_at, id)::integer as inferred
  from public.chapters
  where position is null
)
update public.chapters c set position = m.inferred
from missing_positions m where c.id = m.id;
update public.chapters set number = position where number is null and position is not null;

-- Add foreign keys separately so a legacy table which predates the constraints
-- is upgraded too.  NOT VALID avoids a long blocking validation scan; the data
-- is validated immediately after orphan detection, without deleting anything.
do $migration$
begin
  if not exists (select 1 from pg_constraint where conrelid = 'public.novels'::regclass and conname = 'novels_owner_id_fkey') then
    alter table public.novels add constraint novels_owner_id_fkey
      foreign key (owner_id) references auth.users(id) on delete set null not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.chapters'::regclass and conname = 'chapters_novel_id_fkey') then
    alter table public.chapters add constraint chapters_novel_id_fkey
      foreign key (novel_id) references public.novels(id) on delete cascade not valid;
  end if;
end
$migration$;

-- Surface corrupt legacy relationships instead of silently deleting manuscript
-- data.  A production operator receives the offending IDs in the SQL error.
do $migration$
declare orphan_ids text;
begin
  select string_agg(c.id::text, ', ' order by c.id) into orphan_ids
  from public.chapters c left join public.novels n on n.id = c.novel_id
  where c.novel_id is not null and n.id is null;
  if orphan_ids is not null then
    raise exception 'Creator Portal migration stopped: orphan chapters: %', orphan_ids;
  end if;
  alter table public.novels validate constraint novels_owner_id_fkey;
  alter table public.chapters validate constraint chapters_novel_id_fkey;
end
$migration$;

create index if not exists novels_owner_updated_idx on public.novels(owner_id, updated_at desc);
create index if not exists novels_status_published_idx on public.novels(status, published_at desc);
create index if not exists novels_scheduled_idx on public.novels(scheduled_at) where scheduled_at is not null;
-- Legacy production schemas store genres as text, which has no default GIN
-- operator class.  Preserve that column and only add the array index when the
-- existing type supports it.
do $migration$
declare
  genres_type oid;
begin
  select attribute.atttypid into genres_type
  from pg_attribute attribute
  where attribute.attrelid = 'public.novels'::regclass
    and attribute.attname = 'genres'
    and not attribute.attisdropped;

  if genres_type = 'text[]'::regtype::oid then
    create index if not exists novels_genres_idx on public.novels using gin(genres);
  elsif genres_type = 'text'::regtype::oid then
    raise notice 'Skipping novels_genres_idx because public.novels.genres is text';
  end if;
end
$migration$;
create index if not exists novels_tags_idx on public.novels using gin(tags);
create index if not exists chapters_novel_position_idx on public.chapters(novel_id, position);
-- Do not impose uniqueness on legacy chapter numbers: imported editions can
-- legitimately contain duplicates and the migration must never discard them.
create index if not exists chapters_novel_number_idx
  on public.chapters(novel_id, number) where novel_id is not null and number is not null;

-- ---------------------------------------------------------------------------
-- Publishing history.  The current status remains on novels for compatibility;
-- this append-only relation provides scheduling/audit data for Creator Portal.
-- ---------------------------------------------------------------------------

create table if not exists public.publication_events (
  id uuid primary key default gen_random_uuid(),
  novel_id bigint not null references public.novels(id) on delete cascade,
  from_status text,
  to_status text not null,
  scheduled_at timestamptz,
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists publication_events_novel_created_idx
  on public.publication_events(novel_id, created_at desc);
create index if not exists publication_events_schedule_idx
  on public.publication_events(scheduled_at) where scheduled_at is not null and published_at is null;

-- Seed exactly one migration event per existing novel.  The stable UUID derived
-- from the bigint ID makes this backfill idempotent without modifying the novel.
insert into public.publication_events (id, novel_id, to_status, scheduled_at, published_at, metadata)
select (
         substr(md5('novelverse-publication:' || n.id::text), 1, 8) || '-' ||
         substr(md5('novelverse-publication:' || n.id::text), 9, 4) || '-4' ||
         substr(md5('novelverse-publication:' || n.id::text), 14, 3) || '-8' ||
         substr(md5('novelverse-publication:' || n.id::text), 18, 3) || '-' ||
         substr(md5('novelverse-publication:' || n.id::text), 21, 12)
       )::uuid,
       n.id, n.status, n.scheduled_at, n.published_at, '{"source":"production-upgrade"}'::jsonb
from public.novels n
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Audio generation and durable output metadata
-- ---------------------------------------------------------------------------

create table if not exists public.chapter_audio (
  id uuid primary key default gen_random_uuid(),
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  novel_id bigint not null references public.novels(id) on delete cascade,
  language text not null default 'auto',
  voice_id text not null default 'default',
  provider text not null default 'unconfigured',
  status text not null default 'pending',
  storage_path text,
  duration_seconds numeric(10,2),
  file_size bigint,
  content_hash text not null,
  error_message text,
  bitrate integer,
  sample_rate integer,
  waveform jsonb not null default '[]'::jsonb,
  render_version text,
  cast_version text,
  director_version text,
  signed_asset_metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (chapter_id, language, voice_id, content_hash)
);

-- A partially applied audio migration is upgraded in place.
alter table public.chapter_audio add column if not exists bitrate integer;
alter table public.chapter_audio add column if not exists sample_rate integer;
alter table public.chapter_audio add column if not exists waveform jsonb not null default '[]'::jsonb;
alter table public.chapter_audio add column if not exists render_version text;
alter table public.chapter_audio add column if not exists cast_version text;
alter table public.chapter_audio add column if not exists director_version text;
alter table public.chapter_audio add column if not exists signed_asset_metadata jsonb not null default '{}'::jsonb;

create table if not exists public.audio_render_jobs (
  id uuid primary key default gen_random_uuid(),
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  novel_id bigint not null references public.novels(id) on delete cascade,
  language text not null default 'auto',
  provider text not null,
  status text not null default 'pending',
  priority integer not null default 5,
  retry_count integer not null default 0,
  total_segments integer not null default 0,
  current_segment_index integer not null default 0,
  progress_percent integer not null default 0,
  cache_key text,
  preview_scope jsonb,
  error_code text,
  error_message text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.audio_render_jobs add column if not exists total_segments integer not null default 0;
alter table public.audio_render_jobs add column if not exists current_segment_index integer not null default 0;
alter table public.audio_render_jobs add column if not exists progress_percent integer not null default 0;
alter table public.audio_render_jobs add column if not exists cache_key text;
alter table public.audio_render_jobs add column if not exists preview_scope jsonb;
alter table public.audio_render_jobs add column if not exists error_code text;
alter table public.audio_render_jobs add column if not exists error_message text;

create table if not exists public.audio_render_segments (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references public.audio_render_jobs(id) on delete set null,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  segment_index integer not null,
  input_hash text not null unique,
  provider text not null,
  provider_version text not null,
  status text not null default 'pending',
  storage_path text,
  duration_seconds numeric,
  waveform jsonb not null default '[]'::jsonb,
  render_version text not null,
  retry_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.audio_render_segments add column if not exists retry_count integer not null default 0;
alter table public.audio_render_segments add column if not exists error_message text;

create index if not exists chapter_audio_chapter_status_idx on public.chapter_audio(chapter_id, status, updated_at desc);
create index if not exists chapter_audio_novel_idx on public.chapter_audio(novel_id, language, voice_id);
create index if not exists chapter_audio_ready_idx on public.chapter_audio(chapter_id) where status = 'ready';
create index if not exists audio_render_jobs_status_priority_idx on public.audio_render_jobs(status, priority desc, created_at);
create index if not exists audio_render_jobs_chapter_idx on public.audio_render_jobs(chapter_id, language, provider);
create index if not exists audio_render_jobs_created_by_idx on public.audio_render_jobs(created_by, created_at desc);
create index if not exists audio_render_segments_job_index on public.audio_render_segments(job_id, segment_index);
create index if not exists audio_render_segments_chapter_idx on public.audio_render_segments(chapter_id, segment_index);

-- ---------------------------------------------------------------------------
-- Timestamps, storage and access control
-- ---------------------------------------------------------------------------

-- Keep the authorization helper self-contained so this single migration can be
-- applied even when the older production-readiness migration was not deployed.
create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false)
      or coalesce((auth.jwt() -> 'app_metadata' ->> 'is_admin') = 'true', false)
      or exists (
        select 1 from public.user_roles r
        where r.user_id = auth.uid() and r.role = 'admin'
      );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.set_creator_portal_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists novels_creator_updated_at on public.novels;
create trigger novels_creator_updated_at before update on public.novels
for each row execute function public.set_creator_portal_updated_at();
drop trigger if exists chapters_creator_updated_at on public.chapters;
create trigger chapters_creator_updated_at before update on public.chapters
for each row execute function public.set_creator_portal_updated_at();
drop trigger if exists chapter_audio_creator_updated_at on public.chapter_audio;
create trigger chapter_audio_creator_updated_at before update on public.chapter_audio
for each row execute function public.set_creator_portal_updated_at();
drop trigger if exists audio_jobs_creator_updated_at on public.audio_render_jobs;
create trigger audio_jobs_creator_updated_at before update on public.audio_render_jobs
for each row execute function public.set_creator_portal_updated_at();

insert into storage.buckets (id, name, public)
values ('book-assets', 'book-assets', true)
on conflict (id) do update set public = excluded.public;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('chapter-audio', 'chapter-audio', false, 524288000, array['audio/mpeg','audio/mp3','audio/wav','audio/ogg'])
on conflict (id) do nothing;

alter table public.novels enable row level security;
alter table public.chapters enable row level security;
alter table public.user_roles enable row level security;
alter table public.publication_events enable row level security;
alter table public.chapter_audio enable row level security;
alter table public.audio_render_jobs enable row level security;
alter table public.audio_render_segments enable row level security;

drop policy if exists "Owners manage novels" on public.novels;
create policy "Owners manage novels" on public.novels for all to authenticated
using (owner_id = auth.uid() or public.is_admin())
with check (owner_id = auth.uid() or public.is_admin());
drop policy if exists "Anyone can view published novels" on public.novels;
create policy "Anyone can view published novels" on public.novels for select
using (lower(status) = 'published');

drop policy if exists "Owners manage chapters" on public.chapters;
create policy "Owners manage chapters" on public.chapters for all to authenticated
using (exists (select 1 from public.novels n where n.id = novel_id and (n.owner_id = auth.uid() or public.is_admin())))
with check (exists (select 1 from public.novels n where n.id = novel_id and (n.owner_id = auth.uid() or public.is_admin())));
drop policy if exists "Anyone can view chapters of published books" on public.chapters;
create policy "Anyone can view chapters of published books" on public.chapters for select
using (exists (select 1 from public.novels n where n.id = novel_id and lower(n.status) = 'published'));

drop policy if exists "Owners manage publication events" on public.publication_events;
create policy "Owners manage publication events" on public.publication_events for all to authenticated
using (exists (select 1 from public.novels n where n.id = novel_id and (n.owner_id = auth.uid() or public.is_admin())))
with check (exists (select 1 from public.novels n where n.id = novel_id and (n.owner_id = auth.uid() or public.is_admin())));

drop policy if exists "Ready chapter audio metadata is readable" on public.chapter_audio;
create policy "Ready chapter audio metadata is readable" on public.chapter_audio for select
using (status = 'ready' or public.is_admin());
drop policy if exists "Admins manage chapter audio" on public.chapter_audio;
create policy "Admins manage chapter audio" on public.chapter_audio for all to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins manage audio render jobs" on public.audio_render_jobs;
create policy "Admins manage audio render jobs" on public.audio_render_jobs for all to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Readers view rendered audio segments" on public.audio_render_segments;
create policy "Readers view rendered audio segments" on public.audio_render_segments for select
using (status = 'rendered' or public.is_admin());
drop policy if exists "Admins manage audio render segments" on public.audio_render_segments;
create policy "Admins manage audio render segments" on public.audio_render_segments for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Owners upload book assets" on storage.objects;
create policy "Owners upload book assets" on storage.objects for insert to authenticated
with check (bucket_id = 'book-assets');
drop policy if exists "Owners update book assets" on storage.objects;
create policy "Owners update book assets" on storage.objects for update to authenticated
using (bucket_id = 'book-assets') with check (bucket_id = 'book-assets');
drop policy if exists "Owners delete book assets" on storage.objects;
create policy "Owners delete book assets" on storage.objects for delete to authenticated
using (bucket_id = 'book-assets');

commit;
